---
title: "R Notebook"
output: html_notebook
---

```{r libraries and conections}
options(java.parameters = "-Xmx32000m")
options(scipen = 999)
pacman::p_load(googlesheets,zoo,openxlsx,stringr,splitstackshape,plyr,dplyr,sqldf,stringdist,fuzzyjoin,data.table,svMisc,tidyverse,RJDBC,xlsx)

#połączenie z bazą PBL
#jdbcDriver =JDBC("oracle.jdbc.OracleDriver",classPath="C:/Users/cezar/Documents/R/ojdbc6.jar")
#jdbcDriver =JDBC("oracle.jdbc.OracleDriver",classPath="E:/Cezary/Documents/ojdbc6.jar")
jdbcDriver =JDBC("oracle.jdbc.OracleDriver",classPath="C:/Users/Cezary/Downloads/ojdbc6.jar")
PBL <- dbConnect(jdbcDriver, "jdbc:oracle:thin:@//pbl.ibl.poznan.pl:1521/xe", "IBL_SELECT", "CR333444")
trim <- function (x) gsub("^\\s+|\\s+$", "", x)
pbl_hp <- read.csv2("C:/Users/Cezary/Desktop/pbl_subject_headings.csv", encoding = "Windows-1250", header = TRUE, stringsAsFactors = FALSE)
```

```{r pbl books}
pbl_books1 <- dbGetQuery(PBL,
                        "select z.za_zapis_id \"rekord_id\", z.za_type \"typ\", rz.rz_rodzaj_id \"rodzaj_zapisu_id\", rz.rz_nazwa \"rodzaj_zapisu\", dz.dz_dzial_id \"dzial_id\", dz.dz_nazwa \"dzial\", to_char(tw.tw_tworca_id) \"tworca_id\", tw.tw_nazwisko \"tworca_nazwisko\",
                          tw.tw_imie \"tworca_imie\", to_char(a.am_autor_id) \"autor_id\", a.am_nazwisko \"autor_nazwisko\", 
                          a.am_imie \"autor_imie\", z.za_tytul \"tytul\", z.za_opis_wspoltworcow \"wspoltworcy\", fo.fo_nazwa \"funkcja_osoby\", 
                          to_char(os.os_osoba_id) \"wspoltworca_id\", os.os_nazwisko \"wspoltworca_nazwisko\", os.os_imie \"wspoltworca_imie\", 
                          z.za_adnotacje \"adnotacja\", w.wy_nazwa \"wydawnictwo\", w.wy_miasto \"miejscowosc\", z.za_rok_wydania \"rok_wydania\", z.za_opis_fizyczny_ksiazki \"opis_fizyczny\", z.za_uzytk_wpisal, z.za_ro_rok, z.za_tytul_oryginalu, z.za_wydanie, z.za_instytucja, z.za_seria_wydawnicza, z.za_te_teatr_id,z.ZA_UZYTK_WPIS_DATA,z.ZA_UZYTK_MOD_DATA
                        from pbl_zapisy z
                        join IBL_OWNER.pbl_zapisy_tworcy zt on zt.zatw_za_zapis_id=z.za_zapis_id
                        join IBL_OWNER.pbl_tworcy tw on zt.zatw_tw_tworca_id=tw.tw_tworca_id
                        join IBL_OWNER.pbl_zapisy_autorzy za on za.zaam_za_zapis_id=z.za_zapis_id
                        join IBL_OWNER.pbl_autorzy a on za.zaam_am_autor_id=a.am_autor_id
                        join IBL_OWNER.pbl_zapisy_wydawnictwa zw on zw.zawy_za_zapis_id=z.za_zapis_id 
						join IBL_OWNER.pbl_wydawnictwa w on zw.zawy_wy_wydawnictwo_id=w.wy_wydawnictwo_id
                        join IBL_OWNER.pbl_dzialy dz on dz.dz_dzial_id=z.za_dz_dzial1_id
                        join IBL_OWNER.pbl_rodzaje_zapisow rz on rz.rz_rodzaj_id=z.za_rz_rodzaj1_id
                        join IBL_OWNER.pbl_udzialy_osob uo on uo.uo_za_zapis_id = z.za_zapis_id
                        join IBL_OWNER.pbl_osoby os on uo.uo_os_osoba_id=os.os_osoba_id
                        join IBL_OWNER.pbl_funkcje_osob fo on fo.fo_symbol=uo.uo_fo_symbol
						            where (z.za_status_imp is null OR z.za_status_imp like 'IOK')
						            and z.za_type like 'KS'")
pbl_books2 <- dbGetQuery(PBL,
                        "select z.za_zapis_id \"rekord_id\", z.za_type \"typ\", rz.rz_rodzaj_id \"rodzaj_zapisu_id\", rz.rz_nazwa \"rodzaj_zapisu\", dz.dz_dzial_id \"dzial_id\", dz.dz_nazwa \"dzial\", to_char(tw.tw_tworca_id) \"tworca_id\", tw.tw_nazwisko \"tworca_nazwisko\",
                          tw.tw_imie \"tworca_imie\", to_char(a.am_autor_id) \"autor_id\", a.am_nazwisko \"autor_nazwisko\", 
                          a.am_imie \"autor_imie\", z.za_tytul \"tytul\", z.za_opis_wspoltworcow \"wspoltworcy\", fo.fo_nazwa \"funkcja_osoby\", 
                          to_char(os.os_osoba_id) \"wspoltworca_id\", os.os_nazwisko \"wspoltworca_nazwisko\", os.os_imie \"wspoltworca_imie\", 
                          z.za_adnotacje \"adnotacja\", to_char(null) \"wydawnictwo\", to_char(null) \"miejscowosc\", z.za_rok_wydania \"rok_wydania\", z.za_opis_fizyczny_ksiazki \"opis_fizyczny\", z.za_uzytk_wpisal, z.za_ro_rok, z.za_tytul_oryginalu, z.za_wydanie, z.za_instytucja, z.za_seria_wydawnicza, z.za_te_teatr_id,z.ZA_UZYTK_WPIS_DATA,z.ZA_UZYTK_MOD_DATA
                        from pbl_zapisy z
                        join IBL_OWNER.pbl_zapisy_tworcy zt on zt.zatw_za_zapis_id=z.za_zapis_id
                        join IBL_OWNER.pbl_tworcy tw on zt.zatw_tw_tworca_id=tw.tw_tworca_id
                        join IBL_OWNER.pbl_zapisy_autorzy za on za.zaam_za_zapis_id=z.za_zapis_id
                        join IBL_OWNER.pbl_autorzy a on za.zaam_am_autor_id=a.am_autor_id
                        join IBL_OWNER.pbl_dzialy dz on dz.dz_dzial_id=z.za_dz_dzial1_id
                        join IBL_OWNER.pbl_rodzaje_zapisow rz on rz.rz_rodzaj_id=z.za_rz_rodzaj1_id
                        join IBL_OWNER.pbl_udzialy_osob uo on uo.uo_za_zapis_id = z.za_zapis_id
                        join IBL_OWNER.pbl_osoby os on uo.uo_os_osoba_id=os.os_osoba_id
                        join IBL_OWNER.pbl_funkcje_osob fo on fo.fo_symbol=uo.uo_fo_symbol
						where (z.za_status_imp is null OR z.za_status_imp like 'IOK')
						and z.za_type like 'KS'")
pbl_books3 <- dbGetQuery(PBL,
                          "select z.za_zapis_id \"rekord_id\", z.za_type \"typ\", rz.rz_rodzaj_id \"rodzaj_zapisu_id\", rz.rz_nazwa \"rodzaj_zapisu\", 
                            dz.dz_dzial_id \"dzial_id\", dz.dz_nazwa \"dzial\", to_char(tw.tw_tworca_id) \"tworca_id\", tw.tw_nazwisko \"tworca_nazwisko\",
                            tw.tw_imie \"tworca_imie\", to_char(a.am_autor_id) \"autor_id\", a.am_nazwisko \"autor_nazwisko\", 
                            a.am_imie \"autor_imie\", z.za_tytul \"tytul\", z.za_opis_wspoltworcow \"wspoltworcy\", to_char(null) \"funkcja_osoby\", 
                            to_char(null) \"wspoltworca_id\", to_char(null) \"wspoltworca_nazwisko\", to_char(null) \"wspoltworca_imie\", 
                            z.za_adnotacje \"adnotacja\", w.wy_nazwa \"wydawnictwo\", w.wy_miasto \"miejscowosc\", z.za_rok_wydania \"rok_wydania\", z.za_opis_fizyczny_ksiazki \"opis_fizyczny\", z.za_uzytk_wpisal, z.za_ro_rok, z.za_tytul_oryginalu, z.za_wydanie, z.za_instytucja, z.za_seria_wydawnicza, z.za_te_teatr_id,z.ZA_UZYTK_WPIS_DATA,z.ZA_UZYTK_MOD_DATA
                          from pbl_zapisy z
                          join IBL_OWNER.pbl_zapisy_tworcy zt on zt.zatw_za_zapis_id=z.za_zapis_id
                          join IBL_OWNER.pbl_tworcy tw on zt.zatw_tw_tworca_id=tw.tw_tworca_id
                          join IBL_OWNER.pbl_zapisy_autorzy za on za.zaam_za_zapis_id=z.za_zapis_id
                          join IBL_OWNER.pbl_autorzy a on za.zaam_am_autor_id=a.am_autor_id
                          join IBL_OWNER.pbl_zapisy_wydawnictwa zw on zw.zawy_za_zapis_id=z.za_zapis_id 
						  join IBL_OWNER.pbl_wydawnictwa w on zw.zawy_wy_wydawnictwo_id=w.wy_wydawnictwo_id
                          join IBL_OWNER.pbl_dzialy dz on dz.dz_dzial_id=z.za_dz_dzial1_id
                          join IBL_OWNER.pbl_rodzaje_zapisow rz on rz.rz_rodzaj_id=z.za_rz_rodzaj1_id
						  where (z.za_status_imp is null OR z.za_status_imp like 'IOK')
						  and z.za_type like 'KS'")
pbl_books4 <- dbGetQuery(PBL,
                        "select z.za_zapis_id \"rekord_id\", z.za_type \"typ\", rz.rz_rodzaj_id \"rodzaj_zapisu_id\", rz.rz_nazwa \"rodzaj_zapisu\", dz.dz_dzial_id \"dzial_id\", dz.dz_nazwa \"dzial\", to_char(tw.tw_tworca_id) \"tworca_id\", tw.tw_nazwisko \"tworca_nazwisko\",
                          tw.tw_imie \"tworca_imie\", to_char(a.am_autor_id) \"autor_id\", a.am_nazwisko \"autor_nazwisko\", 
                          a.am_imie \"autor_imie\", z.za_tytul \"tytul\", z.za_opis_wspoltworcow \"wspoltworcy\", to_char(null) \"funkcja_osoby\", 
                          to_char(null) \"wspoltworca_id\", to_char(null) \"wspoltworca_nazwisko\", to_char(null) \"wspoltworca_imie\", 
                          z.za_adnotacje \"adnotacja\", to_char(null) \"wydawnictwo\", to_char(null) \"miejscowosc\", z.za_rok_wydania \"rok_wydania\", z.za_opis_fizyczny_ksiazki \"opis_fizyczny\", z.za_uzytk_wpisal, z.za_ro_rok, z.za_tytul_oryginalu, z.za_wydanie, z.za_instytucja, z.za_seria_wydawnicza, z.za_te_teatr_id,z.ZA_UZYTK_WPIS_DATA,z.ZA_UZYTK_MOD_DATA
                        from pbl_zapisy z
                        join IBL_OWNER.pbl_zapisy_tworcy zt on zt.zatw_za_zapis_id=z.za_zapis_id
                        join IBL_OWNER.pbl_tworcy tw on zt.zatw_tw_tworca_id=tw.tw_tworca_id
                        join IBL_OWNER.pbl_zapisy_autorzy za on za.zaam_za_zapis_id=z.za_zapis_id
                        join IBL_OWNER.pbl_autorzy a on za.zaam_am_autor_id=a.am_autor_id
                        join IBL_OWNER.pbl_dzialy dz on dz.dz_dzial_id=z.za_dz_dzial1_id
                        join IBL_OWNER.pbl_rodzaje_zapisow rz on rz.rz_rodzaj_id=z.za_rz_rodzaj1_id
            						where (z.za_status_imp is null OR z.za_status_imp like 'IOK')
            						and z.za_type like 'KS'")
pbl_books5 <- dbGetQuery(PBL,
                            "select z.za_zapis_id \"rekord_id\", z.za_type \"typ\", rz.rz_rodzaj_id \"rodzaj_zapisu_id\", rz.rz_nazwa \"rodzaj_zapisu\", 
                                    dz.dz_dzial_id \"dzial_id\", dz.dz_nazwa \"dzial\", to_char(tw.tw_tworca_id) \"tworca_id\", tw.tw_nazwisko \"tworca_nazwisko\",
                                    tw.tw_imie \"tworca_imie\", to_char(null) \"autor_id\", to_char(null) \"autor_nazwisko\", 
                                    to_char(null) \"autor_imie\", z.za_tytul \"tytul\", z.za_opis_wspoltworcow \"wspoltworcy\", fo.fo_nazwa \"funkcja_osoby\", 
                                    to_char(os.os_osoba_id) \"wspoltworca_id\", os.os_nazwisko \"wspoltworca_nazwisko\", os.os_imie \"wspoltworca_imie\", 
                                    z.za_adnotacje \"adnotacja\", w.wy_nazwa \"wydawnictwo\", w.wy_miasto \"miejscowosc\", z.za_rok_wydania \"rok_wydania\", z.za_opis_fizyczny_ksiazki \"opis_fizyczny\", z.za_uzytk_wpisal, z.za_ro_rok, z.za_tytul_oryginalu, z.za_wydanie, z.za_instytucja, z.za_seria_wydawnicza, z.za_te_teatr_id ,z.ZA_UZYTK_WPIS_DATA,z.ZA_UZYTK_MOD_DATA
                            from pbl_zapisy z
                            join IBL_OWNER.pbl_zapisy_tworcy zt on zt.zatw_za_zapis_id=z.za_zapis_id
                            join IBL_OWNER.pbl_tworcy tw on zt.zatw_tw_tworca_id=tw.tw_tworca_id
                            join IBL_OWNER.pbl_zapisy_wydawnictwa zw on zw.zawy_za_zapis_id=z.za_zapis_id 
							join IBL_OWNER.pbl_wydawnictwa w on zw.zawy_wy_wydawnictwo_id=w.wy_wydawnictwo_id
                            join IBL_OWNER.pbl_dzialy dz on dz.dz_dzial_id=z.za_dz_dzial1_id
                            join IBL_OWNER.pbl_rodzaje_zapisow rz on rz.rz_rodzaj_id=z.za_rz_rodzaj1_id
                            join IBL_OWNER.pbl_udzialy_osob uo on uo.uo_za_zapis_id = z.za_zapis_id
                            join IBL_OWNER.pbl_osoby os on uo.uo_os_osoba_id=os.os_osoba_id
                            join IBL_OWNER.pbl_funkcje_osob fo on fo.fo_symbol=uo.uo_fo_symbol
							where (z.za_status_imp is null OR z.za_status_imp like 'IOK')
							and z.za_type like 'KS'")
pbl_books6 <- dbGetQuery(PBL,
                         "select z.za_zapis_id \"rekord_id\", z.za_type \"typ\", rz.rz_rodzaj_id \"rodzaj_zapisu_id\", rz.rz_nazwa \"rodzaj_zapisu\", dz.dz_dzial_id \"dzial_id\", dz.dz_nazwa \"dzial\", to_char(tw.tw_tworca_id) \"tworca_id\", tw.tw_nazwisko \"tworca_nazwisko\",
                          tw.tw_imie \"tworca_imie\", to_char(null) \"autor_id\", to_char(null) \"autor_nazwisko\", 
                          to_char(null) \"autor_imie\", z.za_tytul \"tytul\", z.za_opis_wspoltworcow \"wspoltworcy\", fo.fo_nazwa \"funkcja_osoby\", 
                          to_char(os.os_osoba_id) \"wspoltworca_id\", os.os_nazwisko \"wspoltworca_nazwisko\", os.os_imie \"wspoltworca_imie\", 
                          z.za_adnotacje \"adnotacja\", to_char(null) \"wydawnictwo\", to_char(null) \"miejscowosc\", z.za_rok_wydania \"rok_wydania\", z.za_opis_fizyczny_ksiazki \"opis_fizyczny\", z.za_uzytk_wpisal, z.za_ro_rok, z.za_tytul_oryginalu, z.za_wydanie, z.za_instytucja, z.za_seria_wydawnicza, z.za_te_teatr_id,z.ZA_UZYTK_WPIS_DATA,z.ZA_UZYTK_MOD_DATA
                        from pbl_zapisy z
                        join IBL_OWNER.pbl_zapisy_tworcy zt on zt.zatw_za_zapis_id=z.za_zapis_id
                        join IBL_OWNER.pbl_tworcy tw on zt.zatw_tw_tworca_id=tw.tw_tworca_id
                        join IBL_OWNER.pbl_dzialy dz on dz.dz_dzial_id=z.za_dz_dzial1_id
                        join IBL_OWNER.pbl_rodzaje_zapisow rz on rz.rz_rodzaj_id=z.za_rz_rodzaj1_id
                        join IBL_OWNER.pbl_udzialy_osob uo on uo.uo_za_zapis_id = z.za_zapis_id
                        join IBL_OWNER.pbl_osoby os on uo.uo_os_osoba_id=os.os_osoba_id
                        join IBL_OWNER.pbl_funkcje_osob fo on fo.fo_symbol=uo.uo_fo_symbol
						            where (z.za_status_imp is null OR z.za_status_imp like 'IOK')
						            and z.za_type like 'KS'")
pbl_books7 <- dbGetQuery(PBL,
                            "select z.za_zapis_id \"rekord_id\", z.za_type \"typ\", rz.rz_rodzaj_id \"rodzaj_zapisu_id\", rz.rz_nazwa \"rodzaj_zapisu\", 
                                    dz.dz_dzial_id \"dzial_id\", dz.dz_nazwa \"dzial\", to_char(tw.tw_tworca_id) \"tworca_id\", tw.tw_nazwisko \"tworca_nazwisko\",
                                    tw.tw_imie \"tworca_imie\", to_char(null) \"autor_id\", to_char(null) \"autor_nazwisko\", 
                                    to_char(null) \"autor_imie\", z.za_tytul \"tytul\", z.za_opis_wspoltworcow \"wspoltworcy\", to_char(null) \"funkcja_osoby\", 
                                    to_char(null) \"wspoltworca_id\", to_char(null) \"wspoltworca_nazwisko\", to_char(null) \"wspoltworca_imie\", 
                                    z.za_adnotacje \"adnotacja\", w.wy_nazwa \"wydawnictwo\", w.wy_miasto \"miejscowosc\", z.za_rok_wydania \"rok_wydania\", z.za_opis_fizyczny_ksiazki \"opis_fizyczny\", z.za_uzytk_wpisal, z.za_ro_rok, z.za_tytul_oryginalu, z.za_wydanie, z.za_instytucja, z.za_seria_wydawnicza, z.za_te_teatr_id ,z.ZA_UZYTK_WPIS_DATA,z.ZA_UZYTK_MOD_DATA
                            from pbl_zapisy z
                            join IBL_OWNER.pbl_zapisy_tworcy zt on zt.zatw_za_zapis_id=z.za_zapis_id
                            join IBL_OWNER.pbl_tworcy tw on zt.zatw_tw_tworca_id=tw.tw_tworca_id
                            join IBL_OWNER.pbl_zapisy_wydawnictwa zw on zw.zawy_za_zapis_id=z.za_zapis_id 
							join IBL_OWNER.pbl_wydawnictwa w on zw.zawy_wy_wydawnictwo_id=w.wy_wydawnictwo_id
                            join IBL_OWNER.pbl_dzialy dz on dz.dz_dzial_id=z.za_dz_dzial1_id
                            join IBL_OWNER.pbl_rodzaje_zapisow rz on rz.rz_rodzaj_id=z.za_rz_rodzaj1_id
							where (z.za_status_imp is null OR z.za_status_imp like 'IOK')
							and z.za_type like 'KS'")
pbl_books8 <- dbGetQuery(PBL,
                            "select z.za_zapis_id \"rekord_id\", z.za_type \"typ\", rz.rz_rodzaj_id \"rodzaj_zapisu_id\", rz.rz_nazwa \"rodzaj_zapisu\", 
                                    dz.dz_dzial_id \"dzial_id\", dz.dz_nazwa \"dzial\", to_char(tw.tw_tworca_id) \"tworca_id\", tw.tw_nazwisko \"tworca_nazwisko\",
                                    tw.tw_imie \"tworca_imie\", to_char(null) \"autor_id\", to_char(null) \"autor_nazwisko\", 
                                    to_char(null) \"autor_imie\", z.za_tytul \"tytul\", z.za_opis_wspoltworcow \"wspoltworcy\", to_char(null) \"funkcja_osoby\", 
                                    to_char(null) \"wspoltworca_id\", to_char(null) \"wspoltworca_nazwisko\", to_char(null) \"wspoltworca_imie\", 
                                    z.za_adnotacje \"adnotacja\", to_char(null) \"wydawnictwo\", to_char(null) \"miejscowosc\", z.za_rok_wydania \"rok_wydania\", z.za_opis_fizyczny_ksiazki \"opis_fizyczny\", z.za_uzytk_wpisal, z.za_ro_rok, z.za_tytul_oryginalu, z.za_wydanie, z.za_instytucja, z.za_seria_wydawnicza, z.za_te_teatr_id ,z.ZA_UZYTK_WPIS_DATA,z.ZA_UZYTK_MOD_DATA
                            from pbl_zapisy z
                            join IBL_OWNER.pbl_zapisy_tworcy zt on zt.zatw_za_zapis_id=z.za_zapis_id
                            join IBL_OWNER.pbl_tworcy tw on zt.zatw_tw_tworca_id=tw.tw_tworca_id
                            join IBL_OWNER.pbl_dzialy dz on dz.dz_dzial_id=z.za_dz_dzial1_id
                            join IBL_OWNER.pbl_rodzaje_zapisow rz on rz.rz_rodzaj_id=z.za_rz_rodzaj1_id
							where (z.za_status_imp is null OR z.za_status_imp like 'IOK')
							and z.za_type like 'KS'")
pbl_books <- sqldf("select *
              from pbl_books1 a
              UNION
              select *
              from pbl_books2 b
              where b.rekord_id not in (select a.rekord_id
              from pbl_books1 a)")
pbl_books <- sqldf("select *
                      from pbl_books a
                      UNION
                      select * 
                      from pbl_books3 b
                      where b.rekord_id not in (select a.rekord_id
                      from pbl_books a)")
pbl_books <- sqldf("select *
                      from pbl_books a
                      UNION
                      select *
                      from pbl_books4 b
                      where b.rekord_id not in (select a.rekord_id
                      from pbl_books a)")
pbl_books <- sqldf("select *
                      from pbl_books a
                      UNION
                      select *
                      from pbl_books5 b
                      where b.rekord_id not in (select a.rekord_id
                      from pbl_books a)")
pbl_books <- sqldf("select *
                      from pbl_books a
                      UNION
                      select *
                      from pbl_books6 b
                      where b.rekord_id not in (select a.rekord_id
                      from pbl_books a)")
pbl_books <- sqldf("select *
                      from pbl_books a
                      UNION
                      select *
                      from pbl_books7 b
                      where b.rekord_id not in (select a.rekord_id
                      from pbl_books a)")
pbl_books <- sqldf("select *
                      from pbl_books a
                      UNION
                      select *
                      from pbl_books8 b
                      where b.rekord_id not in (select a.rekord_id
                      from pbl_books a)")
pbl_books1 <- dbGetQuery(PBL,
                        "select z.za_zapis_id \"rekord_id\", z.za_type \"typ\", rz.rz_rodzaj_id \"rodzaj_zapisu_id\", rz.rz_nazwa \"rodzaj_zapisu\", 
                          dz.dz_dzial_id \"dzial_id\", dz.dz_nazwa \"dzial\", to_char(null) \"tworca_id\", to_char(null) \"tworca_nazwisko\",
                          to_char(null) \"tworca_imie\", to_char(a.am_autor_id) \"autor_id\", a.am_nazwisko \"autor_nazwisko\", 
                          a.am_imie \"autor_imie\", z.za_tytul \"tytul\", z.za_opis_wspoltworcow \"wspoltworcy\", fo.fo_nazwa \"funkcja_osoby\", 
                          to_char(os.os_osoba_id) \"wspoltworca_id\", os.os_nazwisko \"wspoltworca_nazwisko\", os.os_imie \"wspoltworca_imie\", 
                          z.za_adnotacje \"adnotacja\", w.wy_nazwa \"wydawnictwo\", w.wy_miasto \"miejscowosc\", z.za_rok_wydania \"rok_wydania\", z.za_opis_fizyczny_ksiazki \"opis_fizyczny\", z.za_uzytk_wpisal, z.za_ro_rok, z.za_tytul_oryginalu, z.za_wydanie, z.za_instytucja, z.za_seria_wydawnicza, z.za_te_teatr_id,z.ZA_UZYTK_WPIS_DATA,z.ZA_UZYTK_MOD_DATA
                        from pbl_zapisy z
                        join IBL_OWNER.pbl_zapisy_autorzy za on za.zaam_za_zapis_id=z.za_zapis_id
                        join IBL_OWNER.pbl_autorzy a on za.zaam_am_autor_id=a.am_autor_id
                        join IBL_OWNER.pbl_zapisy_wydawnictwa zw on zw.zawy_za_zapis_id=z.za_zapis_id 
						join IBL_OWNER.pbl_wydawnictwa w on zw.zawy_wy_wydawnictwo_id=w.wy_wydawnictwo_id
                        join IBL_OWNER.pbl_dzialy dz on dz.dz_dzial_id=z.za_dz_dzial1_id
                        join IBL_OWNER.pbl_rodzaje_zapisow rz on rz.rz_rodzaj_id=z.za_rz_rodzaj1_id
                        join IBL_OWNER.pbl_udzialy_osob uo on uo.uo_za_zapis_id = z.za_zapis_id
                        join IBL_OWNER.pbl_osoby os on uo.uo_os_osoba_id=os.os_osoba_id
                        join IBL_OWNER.pbl_funkcje_osob fo on fo.fo_symbol=uo.uo_fo_symbol
						where (z.za_status_imp is null OR z.za_status_imp like 'IOK')
						and z.za_type like 'KS'")
pbl_books2 <- dbGetQuery(PBL,
                          "select z.za_zapis_id \"rekord_id\", z.za_type \"typ\", rz.rz_rodzaj_id \"rodzaj_zapisu_id\", rz.rz_nazwa \"rodzaj_zapisu\", 
                            dz.dz_dzial_id \"dzial_id\", dz.dz_nazwa \"dzial\", to_char(null) \"tworca_id\", to_char(null) \"tworca_nazwisko\",
                            to_char(null) \"tworca_imie\", to_char(a.am_autor_id) \"autor_id\", a.am_nazwisko \"autor_nazwisko\", 
                            a.am_imie \"autor_imie\", z.za_tytul \"tytul\", z.za_opis_wspoltworcow \"wspoltworcy\", to_char(null) \"funkcja_osoby\", 
                            to_char(null) \"wspoltworca_id\", to_char(null) \"wspoltworca_nazwisko\", to_char(null) \"wspoltworca_imie\", 
                            z.za_adnotacje \"adnotacja\", w.wy_nazwa \"wydawnictwo\", w.wy_miasto \"miejscowosc\", z.za_rok_wydania \"rok_wydania\", z.za_opis_fizyczny_ksiazki \"opis_fizyczny\", z.za_uzytk_wpisal, z.za_ro_rok, z.za_tytul_oryginalu, z.za_wydanie, z.za_instytucja, z.za_seria_wydawnicza, z.za_te_teatr_id,z.ZA_UZYTK_WPIS_DATA,z.ZA_UZYTK_MOD_DATA
                          from pbl_zapisy z
                          join IBL_OWNER.pbl_zapisy_autorzy za on za.zaam_za_zapis_id=z.za_zapis_id
                          join IBL_OWNER.pbl_autorzy a on za.zaam_am_autor_id=a.am_autor_id
                          join IBL_OWNER.pbl_zapisy_wydawnictwa zw on zw.zawy_za_zapis_id=z.za_zapis_id 
						  join IBL_OWNER.pbl_wydawnictwa w on zw.zawy_wy_wydawnictwo_id=w.wy_wydawnictwo_id
                          join IBL_OWNER.pbl_dzialy dz on dz.dz_dzial_id=z.za_dz_dzial1_id
                          join IBL_OWNER.pbl_rodzaje_zapisow rz on rz.rz_rodzaj_id=z.za_rz_rodzaj1_id
						  where (z.za_status_imp is null OR z.za_status_imp like 'IOK')
						  and z.za_type like 'KS'")
pbl_books3 <- dbGetQuery(PBL,
                        "select z.za_zapis_id \"rekord_id\", z.za_type \"typ\", rz.rz_rodzaj_id \"rodzaj_zapisu_id\", rz.rz_nazwa \"rodzaj_zapisu\", 
                          dz.dz_dzial_id \"dzial_id\", dz.dz_nazwa \"dzial\", to_char(null) \"tworca_id\", to_char(null) \"tworca_nazwisko\",
                          to_char(null) \"tworca_imie\", to_char(a.am_autor_id) \"autor_id\", a.am_nazwisko \"autor_nazwisko\", 
                          a.am_imie \"autor_imie\", z.za_tytul \"tytul\", z.za_opis_wspoltworcow \"wspoltworcy\", fo.fo_nazwa \"funkcja_osoby\", 
                          to_char(os.os_osoba_id) \"wspoltworca_id\", os.os_nazwisko \"wspoltworca_nazwisko\", os.os_imie \"wspoltworca_imie\", 
                          z.za_adnotacje \"adnotacja\", to_char(null) \"wydawnictwo\", to_char(null) \"miejscowosc\", z.za_rok_wydania \"rok_wydania\", z.za_opis_fizyczny_ksiazki \"opis_fizyczny\", z.za_uzytk_wpisal, z.za_ro_rok, z.za_tytul_oryginalu, z.za_wydanie, z.za_instytucja, z.za_seria_wydawnicza, z.za_te_teatr_id,z.ZA_UZYTK_WPIS_DATA,z.ZA_UZYTK_MOD_DATA
                        from pbl_zapisy z
                        join IBL_OWNER.pbl_zapisy_autorzy za on za.zaam_za_zapis_id=z.za_zapis_id
                        join IBL_OWNER.pbl_autorzy a on za.zaam_am_autor_id=a.am_autor_id
                        join IBL_OWNER.pbl_dzialy dz on dz.dz_dzial_id=z.za_dz_dzial1_id
                        join IBL_OWNER.pbl_rodzaje_zapisow rz on rz.rz_rodzaj_id=z.za_rz_rodzaj1_id
                        join IBL_OWNER.pbl_udzialy_osob uo on uo.uo_za_zapis_id = z.za_zapis_id
                        join IBL_OWNER.pbl_osoby os on uo.uo_os_osoba_id=os.os_osoba_id
                        join IBL_OWNER.pbl_funkcje_osob fo on fo.fo_symbol=uo.uo_fo_symbol
						where (z.za_status_imp is null OR z.za_status_imp like 'IOK')
						and z.za_type like 'KS'")
pbl_books4 <- dbGetQuery(PBL,
                        "select z.za_zapis_id \"rekord_id\", z.za_type \"typ\", rz.rz_rodzaj_id \"rodzaj_zapisu_id\", rz.rz_nazwa \"rodzaj_zapisu\", 
                          dz.dz_dzial_id \"dzial_id\", dz.dz_nazwa \"dzial\", to_char(null) \"tworca_id\", to_char(null) \"tworca_nazwisko\",
                          to_char(null) \"tworca_imie\", to_char(a.am_autor_id) \"autor_id\", a.am_nazwisko \"autor_nazwisko\", 
                          a.am_imie \"autor_imie\", z.za_tytul \"tytul\", z.za_opis_wspoltworcow \"wspoltworcy\", to_char(null) \"funkcja_osoby\", 
                          to_char(null) \"wspoltworca_id\", to_char(null) \"wspoltworca_nazwisko\", to_char(null) \"wspoltworca_imie\", 
                          z.za_adnotacje \"adnotacja\", to_char(null) \"wydawnictwo\", to_char(null) \"miejscowosc\", z.za_rok_wydania \"rok_wydania\", z.za_opis_fizyczny_ksiazki \"opis_fizyczny\", z.za_uzytk_wpisal, z.za_ro_rok, z.za_tytul_oryginalu, z.za_wydanie, z.za_instytucja, z.za_seria_wydawnicza, z.za_te_teatr_id,z.ZA_UZYTK_WPIS_DATA,z.ZA_UZYTK_MOD_DATA
                        from pbl_zapisy z
                        join IBL_OWNER.pbl_zapisy_autorzy za on za.zaam_za_zapis_id=z.za_zapis_id
                        join IBL_OWNER.pbl_autorzy a on za.zaam_am_autor_id=a.am_autor_id
                        join IBL_OWNER.pbl_dzialy dz on dz.dz_dzial_id=z.za_dz_dzial1_id
                        join IBL_OWNER.pbl_rodzaje_zapisow rz on rz.rz_rodzaj_id=z.za_rz_rodzaj1_id
						            where (z.za_status_imp is null OR z.za_status_imp like 'IOK')
						            and z.za_type like 'KS'")
pbl_books5 <- dbGetQuery(PBL,
                            "select z.za_zapis_id \"rekord_id\", z.za_type \"typ\", rz.rz_rodzaj_id \"rodzaj_zapisu_id\", rz.rz_nazwa \"rodzaj_zapisu\", 
                                    dz.dz_dzial_id \"dzial_id\", dz.dz_nazwa \"dzial\", to_char(null) \"tworca_id\", to_char(null) \"tworca_nazwisko\",
                                    to_char(null) \"tworca_imie\", to_char(null) \"autor_id\", to_char(null) \"autor_nazwisko\", 
                                    to_char(null) \"autor_imie\", z.za_tytul \"tytul\", z.za_opis_wspoltworcow \"wspoltworcy\", fo.fo_nazwa \"funkcja_osoby\", 
                                    to_char(os.os_osoba_id) \"wspoltworca_id\", os.os_nazwisko \"wspoltworca_nazwisko\", os.os_imie \"wspoltworca_imie\", 
                                    z.za_adnotacje \"adnotacja\", w.wy_nazwa \"wydawnictwo\", w.wy_miasto \"miejscowosc\", z.za_rok_wydania \"rok_wydania\", z.za_opis_fizyczny_ksiazki \"opis_fizyczny\", z.za_uzytk_wpisal, z.za_ro_rok, z.za_tytul_oryginalu, z.za_wydanie, z.za_instytucja, z.za_seria_wydawnicza, z.za_te_teatr_id,z.ZA_UZYTK_WPIS_DATA,z.ZA_UZYTK_MOD_DATA
                            from pbl_zapisy z
                            join IBL_OWNER.pbl_zapisy_wydawnictwa zw on zw.zawy_za_zapis_id=z.za_zapis_id 
							join IBL_OWNER.pbl_wydawnictwa w on zw.zawy_wy_wydawnictwo_id=w.wy_wydawnictwo_id
                            join IBL_OWNER.pbl_dzialy dz on dz.dz_dzial_id=z.za_dz_dzial1_id
                            join IBL_OWNER.pbl_rodzaje_zapisow rz on rz.rz_rodzaj_id=z.za_rz_rodzaj1_id
                            join IBL_OWNER.pbl_udzialy_osob uo on uo.uo_za_zapis_id = z.za_zapis_id
                            join IBL_OWNER.pbl_osoby os on uo.uo_os_osoba_id=os.os_osoba_id
                            join IBL_OWNER.pbl_funkcje_osob fo on fo.fo_symbol=uo.uo_fo_symbol
							where (z.za_status_imp is null OR z.za_status_imp like 'IOK')
							and z.za_type like 'KS'")
pbl_books6 <- dbGetQuery(PBL,
                            "select z.za_zapis_id \"rekord_id\", z.za_type \"typ\", rz.rz_rodzaj_id \"rodzaj_zapisu_id\", rz.rz_nazwa \"rodzaj_zapisu\", 
                                    dz.dz_dzial_id \"dzial_id\", dz.dz_nazwa \"dzial\", to_char(null) \"tworca_id\", to_char(null) \"tworca_nazwisko\",
                                    to_char(null) \"tworca_imie\", to_char(null) \"autor_id\", to_char(null) \"autor_nazwisko\", 
                                    to_char(null) \"autor_imie\", z.za_tytul \"tytul\", z.za_opis_wspoltworcow \"wspoltworcy\", fo.fo_nazwa \"funkcja_osoby\", 
                                    to_char(os.os_osoba_id) \"wspoltworca_id\", os.os_nazwisko \"wspoltworca_nazwisko\", os.os_imie \"wspoltworca_imie\", 
                                    z.za_adnotacje \"adnotacja\", to_char(null) \"wydawnictwo\", to_char(null) \"miejscowosc\", z.za_rok_wydania \"rok_wydania\", z.za_opis_fizyczny_ksiazki \"opis_fizyczny\", z.za_uzytk_wpisal, z.za_ro_rok, z.za_tytul_oryginalu, z.za_wydanie, z.za_instytucja, z.za_seria_wydawnicza, z.za_te_teatr_id,z.ZA_UZYTK_WPIS_DATA,z.ZA_UZYTK_MOD_DATA
                            from pbl_zapisy z
                            join IBL_OWNER.pbl_dzialy dz on dz.dz_dzial_id=z.za_dz_dzial1_id
                            join IBL_OWNER.pbl_rodzaje_zapisow rz on rz.rz_rodzaj_id=z.za_rz_rodzaj1_id
                            join IBL_OWNER.pbl_udzialy_osob uo on uo.uo_za_zapis_id = z.za_zapis_id
                            join IBL_OWNER.pbl_osoby os on uo.uo_os_osoba_id=os.os_osoba_id
                            join IBL_OWNER.pbl_funkcje_osob fo on fo.fo_symbol=uo.uo_fo_symbol
							              where (z.za_status_imp is null OR z.za_status_imp like 'IOK')
							              and z.za_type like 'KS'")
pbl_books7 <- dbGetQuery(PBL,
                            "select z.za_zapis_id \"rekord_id\", z.za_type \"typ\", rz.rz_rodzaj_id \"rodzaj_zapisu_id\", rz.rz_nazwa \"rodzaj_zapisu\", 
                                    dz.dz_dzial_id \"dzial_id\", dz.dz_nazwa \"dzial\", to_char(null) \"tworca_id\", to_char(null) \"tworca_nazwisko\",
                                    to_char(null) \"tworca_imie\", to_char(null) \"autor_id\", to_char(null) \"autor_nazwisko\", 
                                    to_char(null) \"autor_imie\", z.za_tytul \"tytul\", z.za_opis_wspoltworcow \"wspoltworcy\", to_char(null) \"funkcja_osoby\", 
                                    to_char(null) \"wspoltworca_id\", to_char(null) \"wspoltworca_nazwisko\", to_char(null) \"wspoltworca_imie\", 
                                    z.za_adnotacje \"adnotacja\", w.wy_nazwa \"wydawnictwo\", w.wy_miasto \"miejscowosc\", z.za_rok_wydania \"rok_wydania\", z.za_opis_fizyczny_ksiazki \"opis_fizyczny\", z.za_uzytk_wpisal, z.za_ro_rok, z.za_tytul_oryginalu, z.za_wydanie, z.za_instytucja, z.za_seria_wydawnicza, z.za_te_teatr_id,z.ZA_UZYTK_WPIS_DATA,z.ZA_UZYTK_MOD_DATA
                            from pbl_zapisy z
                            join IBL_OWNER.pbl_zapisy_wydawnictwa zw on zw.zawy_za_zapis_id=z.za_zapis_id 
							              join IBL_OWNER.pbl_wydawnictwa w on zw.zawy_wy_wydawnictwo_id=w.wy_wydawnictwo_id
                            join IBL_OWNER.pbl_dzialy dz on dz.dz_dzial_id=z.za_dz_dzial1_id
                            join IBL_OWNER.pbl_rodzaje_zapisow rz on rz.rz_rodzaj_id=z.za_rz_rodzaj1_id
							              where (z.za_status_imp is null OR z.za_status_imp like 'IOK')
							              and z.za_type like 'KS'")
pbl_books8 <- dbGetQuery(PBL,
                            "select z.za_zapis_id \"rekord_id\", z.za_type \"typ\", rz.rz_rodzaj_id \"rodzaj_zapisu_id\", rz.rz_nazwa \"rodzaj_zapisu\", 
                                    dz.dz_dzial_id \"dzial_id\", dz.dz_nazwa \"dzial\", to_char(null) \"tworca_id\", to_char(null) \"tworca_nazwisko\",
                                    to_char(null) \"tworca_imie\", to_char(null) \"autor_id\", to_char(null) \"autor_nazwisko\", 
                                    to_char(null) \"autor_imie\", z.za_tytul \"tytul\", z.za_opis_wspoltworcow \"wspoltworcy\", to_char(null) \"funkcja_osoby\", 
                                    to_char(null) \"wspoltworca_id\", to_char(null) \"wspoltworca_nazwisko\", to_char(null) \"wspoltworca_imie\", 
                                    z.za_adnotacje \"adnotacja\", to_char(null) \"wydawnictwo\", to_char(null) \"miejscowosc\", z.za_rok_wydania \"rok_wydania\", z.za_opis_fizyczny_ksiazki \"opis_fizyczny\", z.za_uzytk_wpisal, z.za_ro_rok, z.za_tytul_oryginalu, z.za_wydanie, z.za_instytucja, z.za_seria_wydawnicza, z.za_te_teatr_id,z.ZA_UZYTK_WPIS_DATA,z.ZA_UZYTK_MOD_DATA                          
                            from pbl_zapisy z
                            join IBL_OWNER.pbl_dzialy dz on dz.dz_dzial_id=z.za_dz_dzial1_id
                            join IBL_OWNER.pbl_rodzaje_zapisow rz on rz.rz_rodzaj_id=z.za_rz_rodzaj1_id
							where (z.za_status_imp is null OR z.za_status_imp like 'IOK')
							and z.za_type like 'KS'")

pbl_books1 <- sqldf("select *
              from pbl_books1 a
              UNION
              select *
              from pbl_books2 b
              where b.rekord_id not in (select a.rekord_id
              from pbl_books1 a)")
pbl_books1 <- sqldf("select *
                      from pbl_books1 a
                      UNION
                      select * 
                      from pbl_books3 b
                      where b.rekord_id not in (select a.rekord_id
                      from pbl_books1 a)")
pbl_books1 <- sqldf("select *
                      from pbl_books1 a
                      UNION
                      select *
                      from pbl_books4 b
                      where b.rekord_id not in (select a.rekord_id
                      from pbl_books1 a)")
pbl_books1 <- sqldf("select *
                      from pbl_books1 a
                      UNION
                      select *
                      from pbl_books5 b
                      where b.rekord_id not in (select a.rekord_id
                      from pbl_books1 a)")
pbl_books1 <- sqldf("select *
                      from pbl_books1 a
                      UNION
                      select *
                      from pbl_books6 b
                      where b.rekord_id not in (select a.rekord_id
                      from pbl_books1 a)")
pbl_books1 <- sqldf("select *
                      from pbl_books1 a
                      UNION
                      select *
                      from pbl_books7 b
                      where b.rekord_id not in (select a.rekord_id
                      from pbl_books1 a)")
pbl_books1 <- sqldf("select *
                      from pbl_books1 a
                      UNION
                      select *
                      from pbl_books8 b
                      where b.rekord_id not in (select a.rekord_id
                      from pbl_books1 a)")
pbl_books <- sqldf("select *
              from pbl_books a
              UNION
              select *
              from pbl_books1 b
              where b.rekord_id not in (select a.rekord_id
              from pbl_books a)")

hasla_przekrojowe <- dbGetQuery(PBL,
                                "select hpz.hz_za_zapis_id,hp.hp_nazwa,khp.kh_nazwa
from IBL_OWNER.pbl_hasla_przekrojowe hp
join IBL_OWNER.pbl_hasla_przekr_zapisow hpz on hpz.hz_hp_haslo_id=hp.hp_haslo_id
join IBL_OWNER.pbl_klucze_hasla_przekr khp on khp.kh_hp_haslo_id=hp.hp_haslo_id
join IBL_OWNER.pbl_hasla_zapisow_klucze hzk on hzk.hzkh_hz_hp_haslo_id=hp.hp_haslo_id and hzk.hzkh_kh_klucz_id=khp.kh_klucz_id and hzk.hzkh_hz_za_zapis_id=hpz.hz_za_zapis_id")

hasla_przekrojowe2 <- dbGetQuery(PBL,
                                 "select hpz.hz_za_zapis_id,hp.hp_nazwa,to_char(null) \"KH_NAZWA\"
from IBL_OWNER.pbl_hasla_przekrojowe hp
join IBL_OWNER.pbl_hasla_przekr_zapisow hpz on hpz.hz_hp_haslo_id=hp.hp_haslo_id")

hasla_przekrojowe <- sqldf("select *
              from hasla_przekrojowe a
              UNION
              select *
              from hasla_przekrojowe2 b
              where b.HZ_ZA_ZAPIS_ID||'|'||HP_NAZWA not in (select a.HZ_ZA_ZAPIS_ID||'|'||HP_NAZWA
              from hasla_przekrojowe a)")

indeks_osobowy <- dbGetQuery(PBL,
                             "select odi_za_zapis_id, odi_nazwisko, odi_imie
                              from IBL_OWNER.pbl_osoby_do_indeksu")

pbl_books <- merge(pbl_books,indeks_osobowy,by.x = "rekord_id",by.y = "ODI_ZA_ZAPIS_ID", all.x = TRUE)
pbl_books <- merge(pbl_books,hasla_przekrojowe,by.x = "rekord_id", by.y = "HZ_ZA_ZAPIS_ID", all.x = TRUE)
```

```{r creating pbl books person authority}
creators <- pbl_books %>%
  select(id = tworca_id,nazwisko = tworca_nazwisko,imie = tworca_imie) %>%
  unique() %>%
  mutate(source = "tworcy")
authors <- pbl_books %>%
  select(id = autor_id,nazwisko = autor_nazwisko,imie = autor_imie) %>%
  unique() %>%
  mutate(source = "autorzy")
contributors <- pbl_books %>%
  select(id = wspoltworca_id,nazwisko = wspoltworca_nazwisko,imie = wspoltworca_imie) %>%
  unique() %>%
  mutate(source = "współtwórcy")
index_of_people <- pbl_books %>%
  select(nazwisko = ODI_NAZWISKO,imie = ODI_IMIE) %>%
  unique() %>%
  mutate(id = seq.int(nrow(.))) %>%
  select(id,1:3) %>%
  mutate(source = "indeks osób")
pbl_people <- rbind(creators,authors,contributors,index_of_people) %>%
  filter(!is.na(id)) %>%
  mutate(name = paste(nazwisko,imie,sep = ", "), 
         name_simple = str_replace_all(str_to_lower(name), "\\W", "")) %>%
  select(id,name,name_simple,source) %>%
  group_by(name_simple) %>%
  mutate(id = paste(id,collapse = "|"),
         name = paste(unique(name), collapse = "|"),
         source = paste(source,collapse = "|")) %>%
  ungroup() %>%
  select(id,source,name,name_simple) %>%
  unique() %>%
  mutate(group_id = seq.int(nrow(.)))

```

```{r final marc books dataframe}
#empty data.frame
pbl_marc <- data.frame(LDR = character(), X001 = character(), X590 = character(), X964 = character(), X100 = character(), X600 = character(), X245 = character(), X700 = character(), X520 = character(), X240 = character(), X300 = character(), X250 = character(), X710 = character(), X490 = character(), X610 = character(), X630 = character(), X787 = character(), X650 = character(), X651 = character(), X655 = character(),  X611 = character(), X264 = character(), stringsAsFactors=FALSE) %>%
  select(noquote(order(colnames(.))))

#LDR
LDR <- "     nam         4u     "
#X001
X001 <- pbl_books %>%
  select(X001 = rekord_id) %>%
  unique() %>%
  mutate(X001 = paste("pl",sprintf("%09d", X001),sep = ""))

#X005
X005 <- pbl_books %>%
  select(rekord_id,ZA_UZYTK_MOD_DATA) %>%
  unique() %>%
  rename(X005 = ZA_UZYTK_MOD_DATA) %>%
  mutate(X005 = trim(str_replace(X005,"(\\d{4})(-)(\\d{2})(-)(\\d{2})(.*$)","\\1\\3\\5")))

#X008
X008 <- pbl_books %>%
  select(rekord_id,ZA_UZYTK_WPIS_DATA,ZA_RO_ROK) %>%
  unique() %>%
  rename(X008 = ZA_UZYTK_WPIS_DATA) %>%
  mutate(X008 = paste(str_replace(X008,"(\\d{2})(\\d{2})(-)(\\d{2})(-)(\\d{2})(.*$)","\\2\\4\\6"),"s",as.character(ZA_RO_ROK),"----                    -d",sep = "")) %>%
  select(rekord_id,X008)

#X040
X040 <- "$aIBL$bpol"

#X100
X100 <- pbl_books %>%
  select(rekord_id,rodzaj_zapisu,tworca_nazwisko,tworca_imie,autor_nazwisko,autor_imie) %>%
  unique() %>%
  mutate(tworca_nazwisko = ifelse(rodzaj_zapisu=="książka twórcy (podmiotowa)"&!is.na(tworca_nazwisko)&grepl(",",tworca_nazwisko)&tworca_imie=="*",as.character(autor_nazwisko),as.character(tworca_nazwisko)),
         tworca_imie = ifelse(rodzaj_zapisu=="książka twórcy (podmiotowa)"&!is.na(tworca_nazwisko)&tworca_nazwisko==autor_nazwisko&tworca_imie=="*",as.character(autor_imie),as.character(tworca_imie)),
         X100 = ifelse(rodzaj_zapisu=="książka twórcy (podmiotowa)",paste("1\\$a",tworca_nazwisko,", ",tworca_imie,"$4aut",sep = ""),
                       ifelse(!is.na(autor_nazwisko),paste("1 $a",autor_nazwisko,", ",autor_imie,"$4aut",sep = ""),NA))) %>%
  select(rekord_id,X100) %>%
  group_by(rekord_id) %>%
  mutate(X100 = paste(X100,collapse = "|")) %>%
  ungroup() %>%
  unique() %>%
  mutate(X700 = ifelse(grepl("\\|",X100),str_replace(X100,"^(.*?)(\\|)(.*$)","\\3"),NA),
         X100 = ifelse(grepl("\\|",X100),str_replace(X100,"^(.*?)(\\|)(.*$)","\\1"),as.character(X100)),
         X100 = trim(ifelse(X100=="NA",NA,as.character(X100))),
         X700 = trim(ifelse(X700==X100,NA,as.character(X700))))
#X240
X240 <- pbl_books %>%
  select(rekord_id,ZA_TYTUL_ORYGINALU) %>%
  unique() %>%
  rename(X240 = ZA_TYTUL_ORYGINALU) %>%
  mutate(X240 = trim(ifelse(is.na(X240),"",paste("\\\\$a",str_replace(X240,"^(.*?\\])(.*$)","\\1"),sep = ""))))

#X245
X245 <- pbl_books %>%
  select(rekord_id,autor_nazwisko,autor_imie,tytul,wspoltworcy,ZA_INSTYTUCJA) %>%
  unique() %>%
  mutate(tytul_ok = str_remove(paste("10$a",ifelse(substr(tytul,nchar(tytul),nchar(tytul))=="]",trim(str_replace(tytul,"(^.*?)(([\\.!?] {0,1})\\[.*?$)","\\1")),
                           ifelse(substr(tytul,1,1)=="[",trim(str_replace(tytul,"(^.*?\\])(.*?$)","\\2")),as.character(tytul)))," /",sep = ""),"10\\$a \\/"),
         autor = ifelse(!is.na(autor_nazwisko)&!is.na(autor_imie),paste("$c",autor_imie," ",autor_nazwisko,sep = ""),
                        ifelse(!is.na(autor_nazwisko)&is.na(autor_imie),paste("$c",autor_nazwisko,sep = ""),"")),
         wspoltworcy = ifelse(is.na(wspoltworcy),"",as.character(wspoltworcy)),
         ZA_INSTYTUCJA = ifelse(is.na(ZA_INSTYTUCJA),"",as.character(ZA_INSTYTUCJA))) %>%
  select(rekord_id,tytul_ok,autor,wspoltworcy,ZA_INSTYTUCJA) %>%
  group_by(rekord_id) %>%
  mutate(tytul_ok = paste(unique(tytul_ok),collapse = "|"),
         autor = str_replace_all(paste(unique(autor),collapse = "|"),"\\|\\$c",", "),
         wspoltworcy = paste(unique(wspoltworcy),collapse = "|"),
         ZA_INSTYTUCJA = paste(unique(ZA_INSTYTUCJA),collapse = "|")) %>%
  ungroup() %>%
  mutate(X245 = paste(tytul_ok,autor," ; ",wspoltworcy," ; ",ZA_INSTYTUCJA,".", sep = ""),
         X245 = trim(str_replace_all(X245,"( ;  ; )(\\.)|( ;   ; )(\\.)|( ; )(\\.)|","\\2"))) %>%
  select(rekord_id,X245) %>%
  unique()

#X250
X250 <- pbl_books %>%
  select(rekord_id,ZA_WYDANIE) %>%
  unique() %>%
  rename(X250 = ZA_WYDANIE) %>%
  mutate(X250 = trim(ifelse(is.na(X250),"",paste("\\\\$a",as.character(X250),sep = ""))))

#X264
X264 <- pbl_books %>%
  select(rekord_id,wydawnictwo,miejscowosc,ZA_RO_ROK) %>%
  unique() %>%
  mutate(X264 = paste("1\\$a",miejscowosc," : $b",wydawnictwo,sep = "")) %>%
  select(rekord_id,X264,ZA_RO_ROK) %>%
  group_by(rekord_id) %>%
  mutate(X264 = paste(X264,collapse = "; "),
         ZA_RO_ROK = paste(unique(ZA_RO_ROK),collapse = "|")) %>%
  ungroup() %>%
  unique() %>%
  mutate(X264 = trim(paste(X264,",$c",ZA_RO_ROK,sep = ""))) %>%
  select(rekord_id,X264)

#X300
X300 <- pbl_books %>%
  select(rekord_id,opis_fizyczny) %>%
  unique() %>%
  rename(X300 = opis_fizyczny) %>%
  mutate(X300 = trim(ifelse(is.na(X300),"",
                       ifelse(grepl("^\\[\\d{4}\\],|^\\[\\d{4}\\]\\.",X300),str_replace(X300,"^(\\[\\d{4}\\](,|\\.))(.*$)","\\3"),as.character(X300)))),
         X300 = ifelse(X300=="","",paste("\\\\$a",X300,sep = "")))

#X490
X490 <- pbl_books %>%
  select(rekord_id,ZA_SERIA_WYDAWNICZA) %>%
  unique() %>%
  rename(X490 = ZA_SERIA_WYDAWNICZA) %>%
  mutate(X490 = str_remove(str_remove(X490,"^\\("),"\\)\\.{0,1}$"),
         X490 = str_replace(X490,"\\) \\(","#"),
         X490 = str_replace_all(X490,"(\\d+)(\\. )","\\1\\2#")) %>%
  cSplit(.,"X490",sep = "#",direction = "long") %>%
  mutate(X490 = ifelse(grepl("\\d",X490),
                       ifelse(grepl("; ",X490),str_replace(X490,"; ","|"),str_replace(X490,", ","|")),as.character(X490))) %>%
  cSplit(.,"X490",sep = "|",direction = "wide") %>%
  mutate(X490 = trim(ifelse(is.na(X490_2)&!is.na(X490_1),paste("0\\$a",X490_1,sep = ""),
                       ifelse(!is.na(X490_1)&!is.na(X490_2),paste("0\\$a",X490_1," ; $v",X490_2,sep = ""),"")))) %>%
  select(rekord_id,X490) %>%
  group_by(rekord_id) %>%
  mutate(X490 = paste(X490,collapse = "|")) %>%
  ungroup() %>%
  unique()

#X520
X520 <- pbl_books %>%
  select(rekord_id,adnotacja) %>%
  unique() %>%
  rename(X520 = adnotacja) %>%
  mutate(X520 = trim(ifelse(is.na(X520),"",paste("2\\$a",X520,sep = ""))))

#X590
X590 <- pbl_books %>%
  select(rekord_id,rodzaj_zapisu) %>%
  unique() %>%
  rename(X590 = rodzaj_zapisu)

#X600
X600 <- pbl_books %>%
  select(rekord_id,rodzaj_zapisu,tworca_nazwisko,tworca_imie) %>%
  unique() %>%
  filter(rodzaj_zapisu=="książka o twórcy (przedmiotowa)") %>%
  mutate(tworca_nazwisko = ifelse(!is.na(tworca_nazwisko)&grepl(",",tworca_nazwisko)&tworca_imie=="*",str_replace_all(tworca_nazwisko,",","|"),as.character(tworca_nazwisko)),
         tworca_imie = ifelse(!is.na(tworca_nazwisko)&tworca_imie=="*","",as.character(tworca_imie))) %>%
  cSplit(.,"tworca_nazwisko",sep = "|",direction = "long") %>%
  mutate(X600 = trim(ifelse(tworca_imie!="",paste("14$a",tworca_nazwisko,", ",tworca_imie,sep = ""),paste("14$a",tworca_nazwisko,sep = "")))) %>%
  select(rekord_id,X600) %>%
  group_by(rekord_id) %>%
  mutate(X600 = paste(X600,collapse = "|")) %>%
  ungroup() %>%
  unique() %>%
  mutate(X600 = str_remove(X600," \\*$|\\*$")) %>%
  full_join(.,pbl_books %>% select(rekord_id) %>% unique(),by = "rekord_id") %>%
  arrange(rekord_id)
  
#X610
X610 <- pbl_books %>%
  select(rekord_id,HP_NAZWA,KH_NAZWA) %>%
  unique() %>% 
  inner_join(.,pbl_hp %>% filter(MARC_FIELD=="24.61"),by = c("HP_NAZWA","KH_NAZWA")) %>%
  mutate(X610 = trim(ifelse(!is.na(KH_NAZWA),paste("24$a",HP_NAZWA,", ",KH_NAZWA,sep = ""),paste("24$a",HP_NAZWA,sep = "")))) %>%
  select(rekord_id,X610) %>%
  group_by(rekord_id) %>%
  mutate(X610 = paste(X610,collapse = "|")) %>%
  ungroup() %>%
  unique() %>%
  full_join(.,pbl_books %>% select(rekord_id) %>% unique(),by = "rekord_id") %>%
  arrange(rekord_id)

#X611
X611 <- pbl_books %>%
  select(rekord_id,HP_NAZWA,KH_NAZWA) %>%
  unique() %>% 
  inner_join(.,pbl_hp %>% filter(MARC_FIELD=="24.611"),by = c("HP_NAZWA","KH_NAZWA")) %>%
  mutate(X611 = trim(ifelse(!is.na(KH_NAZWA),paste("24$a",HP_NAZWA,", ",KH_NAZWA,sep = ""),paste("24$a",HP_NAZWA,sep = "")))) %>%
  select(rekord_id,X611) %>%
  group_by(rekord_id) %>%
  mutate(X611 = paste(X611,collapse = "|")) %>%
  ungroup() %>%
  unique() %>%
  full_join(.,pbl_books %>% select(rekord_id) %>% unique(),by = "rekord_id") %>%
  arrange(rekord_id)

#X630
X630 <- pbl_books %>%
  select(rekord_id,HP_NAZWA,KH_NAZWA) %>%
  unique() %>% 
  inner_join(.,pbl_hp %>% filter(MARC_FIELD=="4.63"),by = c("HP_NAZWA","KH_NAZWA")) %>%
  mutate(X630 = trim(ifelse(!is.na(KH_NAZWA),paste("\\4$a",HP_NAZWA,", ",KH_NAZWA,sep = ""),paste("\\4$a",HP_NAZWA,sep = "")))) %>%
  select(rekord_id,X630) %>%
  group_by(rekord_id) %>%
  mutate(X630 = paste(X630,collapse = "|")) %>%
  ungroup() %>%
  unique() %>%
  full_join(.,pbl_books %>% select(rekord_id) %>% unique(),by = "rekord_id") %>%
  arrange(rekord_id)

#X650
X650 <- pbl_books %>%
  select(rekord_id,HP_NAZWA,KH_NAZWA) %>%
  unique() %>% 
  inner_join(.,pbl_hp %>% filter(MARC_FIELD=="4.65"|MARC_FIELD=="24.65"),by = c("HP_NAZWA","KH_NAZWA")) %>%
  mutate(X650 = trim(ifelse(MARC_FIELD=="4.65",
                            ifelse(!is.na(KH_NAZWA),paste("04$a",HP_NAZWA,", ",KH_NAZWA,sep = ""),paste("04$a",HP_NAZWA,sep = "")),
                       ifelse(MARC_FIELD=="24.65",
                              ifelse(!is.na(KH_NAZWA),paste("24$a",HP_NAZWA,", ",KH_NAZWA,sep = ""),paste("24$a",HP_NAZWA,sep = "")),"")))) %>%
  select(rekord_id,X650) %>%
  group_by(rekord_id) %>%
  mutate(X650 = paste(X650,collapse = "|")) %>%
  ungroup() %>%
  unique() %>%
  full_join(.,pbl_books %>% select(rekord_id) %>% unique(),by = "rekord_id") %>%
  arrange(rekord_id)

#X651
X651 <- pbl_books %>%
  select(rekord_id,HP_NAZWA,KH_NAZWA) %>%
  unique() %>% 
  inner_join(.,pbl_hp %>% filter(MARC_FIELD=="4.651"),by = c("HP_NAZWA","KH_NAZWA")) %>%
  mutate(X651 = trim(ifelse(!is.na(KH_NAZWA),paste("\\4$a",HP_NAZWA,", ",KH_NAZWA,sep = ""),paste("\\4$a",HP_NAZWA,sep = "")))) %>%
  select(rekord_id,X651) %>%
  group_by(rekord_id) %>%
  mutate(X651 = paste(X651,collapse = "|")) %>%
  ungroup() %>%
  unique() %>%
  full_join(.,pbl_books %>% select(rekord_id) %>% unique(),by = "rekord_id") %>%
  arrange(rekord_id)

#X655
X655 <- pbl_books %>%
  select(rekord_id,tytul) %>%
  unique() %>%
  group_by(rekord_id) %>%
  mutate(X655 = trim(paste(unlist(str_extract_all(tytul,"(?<!^.)(?<=\\[)(.*?)(?=\\])")),collapse = "|"))) %>%
  ungroup() %>%
  select(rekord_id,X655) %>%
  cSplit(.,"X655",sep = "|",direction = "long") %>%
  mutate(X655 = paste("\\4$a",X655,sep = "")) %>%
  group_by(rekord_id) %>%
  mutate(X655 = paste(X655,collapse = "|")) %>%
  ungroup() %>%
  unique() %>%
  full_join(.,pbl_books %>% select(rekord_id) %>% unique(),by = "rekord_id") %>%
  arrange(rekord_id)

#X700
X700 <- pbl_books %>%
  select(rekord_id,funkcja_osoby,wspoltworca_nazwisko,wspoltworca_imie) %>%
  unique() %>%
  mutate(X700 = trim(ifelse(is.na(wspoltworca_nazwisko),"",paste("1\\$a",wspoltworca_nazwisko,", ",wspoltworca_imie,"$e",funkcja_osoby,sep = "")))) %>%
  select(rekord_id,X700) %>%
  rbind(X100 %>% select(rekord_id,X700) %>% cSplit(.,"X700",sep = "|",direction = "long"),.) %>%
  arrange(rekord_id) %>%
  filter(!is.na(X700)&X700!="") %>%
  group_by(rekord_id) %>%
  mutate(X700 = paste(X700,collapse = "|")) %>%
  ungroup() %>%
  unique() %>%
  full_join(.,pbl_books %>% select(rekord_id) %>% unique(),by = "rekord_id") %>%
  arrange(rekord_id)
X100 <- X100 %>%
  select(rekord_id,X100)
  
#710
X710 <- pbl_books %>%
  select(rekord_id,ZA_INSTYTUCJA) %>%
  unique() %>%
  rename(X710 = ZA_INSTYTUCJA) %>%
  mutate(X710 = trim(ifelse(is.na(X710),NA,paste("24$a",X710,"$4isp",sep = ""))))

#X787
X787 <- pbl_books %>%
  select(rekord_id,HP_NAZWA,KH_NAZWA) %>%
  unique() %>% 
  inner_join(.,pbl_hp %>% filter(MARC_FIELD=="787"),by = c("HP_NAZWA","KH_NAZWA")) %>%
  mutate(X787 = trim(ifelse(!is.na(KH_NAZWA),paste(HP_NAZWA,", ",KH_NAZWA,sep = ""),as.character(HP_NAZWA)))) %>%
  select(rekord_id,X787) %>%
  group_by(rekord_id) %>%
  mutate(X787 = paste(X787,collapse = "|")) %>%
  ungroup() %>%
  unique() %>%
  full_join(.,pbl_books %>% select(rekord_id) %>% unique(),by = "rekord_id") %>%
  arrange(rekord_id)

#X964
X964 <- pbl_books %>%
  select(rekord_id,dzial) %>%
  unique() %>%
  rename(X964 = dzial) %>%
  mutate(X964 = trim(str_replace(X964,"(.*)( - .$)","\\1")))

pbl_marc_books <- X005 %>%
  full_join(.,X008,by = "rekord_id") %>%
  full_join(.,X100,by = "rekord_id") %>%
  full_join(.,X240,by = "rekord_id") %>%
  full_join(.,X245,by = "rekord_id") %>%
  full_join(.,X250,by = "rekord_id") %>%
  full_join(.,X264,by = "rekord_id") %>%
  full_join(.,X300,by = "rekord_id") %>%
  full_join(.,X490,by = "rekord_id") %>%
  full_join(.,X520,by = "rekord_id") %>%
  full_join(.,X590,by = "rekord_id") %>%
  full_join(.,X600,by = "rekord_id") %>%
  full_join(.,X610,by = "rekord_id") %>%
  full_join(.,X611,by = "rekord_id") %>%
  full_join(.,X630,by = "rekord_id") %>%
  full_join(.,X650,by = "rekord_id") %>%
  full_join(.,X651,by = "rekord_id") %>%
  full_join(.,X655,by = "rekord_id") %>%
  full_join(.,X700,by = "rekord_id") %>%
  full_join(.,X710,by = "rekord_id") %>%
  full_join(.,X787,by = "rekord_id") %>%
  full_join(.,X964,by = "rekord_id") %>%
  cbind(.,LDR,X040,X001) %>%
  select(noquote(order(colnames(.))))

long <- reshape(pbl_marc_books,
                direction = "long",
                varying = list(names(pbl_marc_books)[-2]),
                v.names = "Value",
                idvar = "rekord_id",
                timevar = "fields",
                times = names(pbl_marc_books)[-2]) %>%
  arrange(rekord_id) %>%
  mutate(Value = ifelse(is.na(Value)&fields=="X001",as.character(rekord_id),
                        ifelse(is.na(Value),"",as.character(Value))),
         fields = str_replace(fields,"^X{0,1}","=")) %>%
  cSplit(.,"Value",sep = "|",direction = "long") %>%
  mutate(Value = gsub("[\r\n]", " ",Value)) %>%
  select(fields,Value) %>%
  mutate(fields = ifelse(lead(fields=="=LDR"),paste(fields,"||",sep = ""),as.character(fields))) %>%
  mutate(Value = ifelse(lead(fields=="=LDR"),paste(Value,"||",sep = ""),as.character(Value))) %>%
  cSplit(.,c("fields","Value"),sep = "|",direction = "long") %>%
  write.table(., "pbl_marc_books.csv", append = FALSE, sep = "  ", dec = ",", row.names = FALSE, col.names = FALSE, quote = FALSE, fileEncoding = "UTF-8")

```

```{r pbl articles}
pbl_articles <- dbGetQuery(PBL,
                        "select z.za_zapis_id \"rekord_id\", z.za_type \"typ\", rz.rz_rodzaj_id \"rodzaj_zapisu_id\", rz.rz_nazwa \"rodzaj_zapisu\", 
                          dz.dz_dzial_id \"dzial_id\", dz.dz_nazwa \"dzial\", to_char(tw.tw_tworca_id) \"tworca_id\", tw.tw_nazwisko \"tworca_nazwisko\",
                          tw.tw_imie \"tworca_imie\", to_char(a.am_autor_id) \"autor_id\", a.am_nazwisko \"autor_nazwisko\", 
                          a.am_imie \"autor_imie\", z.za_tytul \"tytul\", z.za_opis_wspoltworcow \"wspoltworcy\", fo.fo_nazwa \"funkcja_osoby\", 
                          to_char(os.os_osoba_id) \"wspoltworca_id\", os.os_nazwisko \"wspoltworca_nazwisko\", os.os_imie \"wspoltworca_imie\", 
                          z.za_adnotacje \"adnotacja\", to_char(zr.zr_zrodlo_id) \"czasopismo_id\", zr.zr_tytul \"czasopismo\", 
                          z.za_zrodlo_rok \"rok\", z.za_zrodlo_nr \"numer\", z.za_zrodlo_str \"strony\",z.za_tytul_oryginalu,z.za_te_teatr_id,z.ZA_UZYTK_WPIS_DATA,z.ZA_UZYTK_MOD_DATA,z.ZA_TYPE
                        from pbl_zapisy z
                        full outer join IBL_OWNER.pbl_zapisy_tworcy zt on zt.zatw_za_zapis_id=z.za_zapis_id
                        full outer join IBL_OWNER.pbl_tworcy tw on zt.zatw_tw_tworca_id=tw.tw_tworca_id
                        full outer join IBL_OWNER.pbl_zapisy_autorzy za on za.zaam_za_zapis_id=z.za_zapis_id
                        full outer join IBL_OWNER.pbl_autorzy a on za.zaam_am_autor_id=a.am_autor_id
                        full outer join IBL_OWNER.pbl_zrodla zr on zr.zr_zrodlo_id=z.za_zr_zrodlo_id
                        full outer join IBL_OWNER.pbl_dzialy dz on dz.dz_dzial_id=z.za_dz_dzial1_id
                        full outer join IBL_OWNER.pbl_rodzaje_zapisow rz on rz.rz_rodzaj_id=z.za_rz_rodzaj1_id
                        full outer join IBL_OWNER.pbl_udzialy_osob uo on uo.uo_za_zapis_id = z.za_zapis_id
                        full outer join IBL_OWNER.pbl_osoby os on uo.uo_os_osoba_id=os.os_osoba_id
                        full outer join IBL_OWNER.pbl_funkcje_osob fo on fo.fo_symbol=uo.uo_fo_symbol
                        where z.za_type in ('IZA','PU')")
test <- pbl_articles %>%
  filter(is.na(tworca_nazwisko))

test2 <- as.data.frame(table(pbl_articles$rekord_id))

hasla_przekrojowe <- dbGetQuery(PBL,
                                "select hpz.hz_za_zapis_id,hp.hp_nazwa,khp.kh_nazwa
                                from IBL_OWNER.pbl_hasla_przekrojowe hp
                                join IBL_OWNER.pbl_hasla_przekr_zapisow hpz on hpz.hz_hp_haslo_id=hp.hp_haslo_id
                                join IBL_OWNER.pbl_klucze_hasla_przekr khp on khp.kh_hp_haslo_id=hp.hp_haslo_id
                                join IBL_OWNER.pbl_hasla_zapisow_klucze hzk on hzk.hzkh_hz_hp_haslo_id=hp.hp_haslo_id and hzk.hzkh_kh_klucz_id=khp.kh_klucz_id and hzk.hzkh_hz_za_zapis_id=hpz.hz_za_zapis_id")

hasla_przekrojowe2 <- dbGetQuery(PBL,
                                 "select hpz.hz_za_zapis_id,hp.hp_nazwa,to_char(null) \"KH_NAZWA\"
from IBL_OWNER.pbl_hasla_przekrojowe hp
join IBL_OWNER.pbl_hasla_przekr_zapisow hpz on hpz.hz_hp_haslo_id=hp.hp_haslo_id")

hasla_przekrojowe <- sqldf("select *
              from hasla_przekrojowe a
              UNION
              select *
              from hasla_przekrojowe2 b
              where b.HZ_ZA_ZAPIS_ID||'|'||HP_NAZWA not in (select a.HZ_ZA_ZAPIS_ID||'|'||HP_NAZWA
              from hasla_przekrojowe a)")

indeks_osobowy <- dbGetQuery(PBL,
                             "select odi_za_zapis_id, odi_nazwisko, odi_imie
                              from IBL_OWNER.pbl_osoby_do_indeksu")

pbl_articles <- merge(pbl_articles,indeks_osobowy,by.x = "rekord_id",by.y = "ODI_ZA_ZAPIS_ID", all.x = TRUE)
pbl_articles <- merge(pbl_articles,hasla_przekrojowe,by.x = "rekord_id", by.y = "HZ_ZA_ZAPIS_ID", all.x = TRUE)
```

```{r final marc articles dataframe}
#empty data.frame
pbl_marc <- data.frame(LDR = character(), X001 = character(), X590 = character(), X964 = character(), X100 = character(), X600 = character(), X245 = character(), X700 = character(), X520 = character(), X240 = character(), X710 = character(), X610 = character(), X630 = character(), X787 = character(), X650 = character(), X651 = character(), X655 = character(),  X611 = character(), X773 = character(), LKR = character(), stringsAsFactors=FALSE) %>%
  select(noquote(order(colnames(.))))

#LDR
LDR <- "     nab         4u     "
#X001
X001 <- pbl_articles %>%
  select(X001 = rekord_id) %>%
  unique() %>%
  mutate(X001 = paste("pl",sprintf("%09d", X001),sep = ""))

#X005
X005 <- pbl_articles %>%
  select(rekord_id,ZA_UZYTK_MOD_DATA) %>%
  unique() %>%
  rename(X005 = ZA_UZYTK_MOD_DATA) %>%
  mutate(X005 = trim(str_replace(X005,"(\\d{4})(-)(\\d{2})(-)(\\d{2})(.*$)","\\1\\3\\5")))

#X008
X008 <- pbl_articles %>%
  select(rekord_id,ZA_UZYTK_WPIS_DATA,rok) %>%
  unique() %>%
  rename(X008 = ZA_UZYTK_WPIS_DATA) %>%
  mutate(X008 = paste(str_replace(X008,"(\\d{2})(\\d{2})(-)(\\d{2})(-)(\\d{2})(.*$)","\\2\\4\\6"),"s",as.character(rok),"----                    -d",sep = "")) %>%
  select(rekord_id,X008)

#X040
X040 <- "$aIBL$bpol"

#X100
X100 <- pbl_articles %>%
  select(rekord_id,ZA_TYPE,tworca_nazwisko,tworca_imie,autor_nazwisko,autor_imie) %>%
  unique() %>%
  mutate(tworca_nazwisko = ifelse(ZA_TYPE=="PU"&!is.na(tworca_nazwisko)&grepl(",",tworca_nazwisko)&tworca_imie=="*",as.character(autor_nazwisko),as.character(tworca_nazwisko)),
         tworca_imie = ifelse(ZA_TYPE=="PU"&!is.na(tworca_nazwisko)&tworca_nazwisko==autor_nazwisko&tworca_imie=="*",as.character(autor_imie),as.character(tworca_imie)),
         X100 = ifelse(ZA_TYPE=="PU",paste("1\\$a",tworca_nazwisko,", ",tworca_imie,"$4aut",sep = ""),
                       ifelse(!is.na(autor_nazwisko),paste("1 $a",autor_nazwisko,", ",autor_imie,"$4aut",sep = ""),NA))) %>%
  select(rekord_id,X100) %>%
  group_by(rekord_id) %>%
  mutate(X100 = paste(X100,collapse = "|")) %>%
  ungroup() %>%
  unique() %>%
  mutate(X700 = ifelse(grepl("\\|",X100),str_replace(X100,"^(.*?)(\\|)(.*$)","\\3"),NA),
         X100 = ifelse(grepl("\\|",X100),str_replace(X100,"^(.*?)(\\|)(.*$)","\\1"),as.character(X100)),
         X100 = trim(ifelse(X100=="NA",NA,as.character(X100))),
         X700 = trim(ifelse(X700==X100,NA,as.character(X700))))
#X240
X240 <- pbl_articles %>%
  select(rekord_id,ZA_TYTUL_ORYGINALU) %>%
  unique() %>%
  rename(X240 = ZA_TYTUL_ORYGINALU) %>%
  mutate(X240 = trim(ifelse(is.na(X240),"",paste("\\\\$a",str_replace(X240,"^(.*?\\])(.*$)","\\1"),sep = ""))))

#X245
X245 <- pbl_articles %>%
  select(rekord_id,autor_nazwisko,autor_imie,tytul,wspoltworcy) %>%
  unique() %>%
  mutate(tytul_ok = ifelse(is.na(tytul),"",paste("10$a",tytul," /",sep = "")),
         autor = ifelse(!is.na(autor_nazwisko)&!is.na(autor_imie),paste("$c",autor_imie," ",autor_nazwisko,sep = ""),
                        ifelse(!is.na(autor_nazwisko)&is.na(autor_imie),paste("$c",autor_nazwisko,sep = ""),"")),
         wspoltworcy = ifelse(is.na(wspoltworcy),"",as.character(wspoltworcy))) %>%
  select(rekord_id,tytul_ok,autor,wspoltworcy) %>%
  group_by(rekord_id) %>%
  mutate(tytul_ok = paste(unique(tytul_ok),collapse = "|"),
         autor = str_replace_all(paste(unique(autor),collapse = "|"),"\\|\\$c",", "),
         wspoltworcy = paste(unique(wspoltworcy),collapse = "|")) %>%
  ungroup() %>%
  mutate(X245 = paste(tytul_ok,autor," ; ",wspoltworcy,".", sep = ""),
         X245 = trim(str_replace_all(X245,"( ;  ; )(\\.)|( ;   ; )(\\.)|( ; )(\\.)|","\\2"))) %>%
  select(rekord_id,X245) %>%
  unique()

#X520
X520 <- pbl_articles %>%
  select(rekord_id,adnotacja) %>%
  unique() %>%
  rename(X520 = adnotacja) %>%
  mutate(X520 = trim(ifelse(is.na(X520),"",paste("2\\$a",X520,sep = ""))))

#X600
X600 <- pbl_articles %>%
  select(rekord_id,ZA_TYPE,tworca_nazwisko,tworca_imie) %>%
  unique() %>%
  filter(ZA_TYPE=="IZA") %>%
  mutate(tworca_nazwisko = ifelse(is.na(tworca_nazwisko),"",
                                  ifelse(!is.na(tworca_nazwisko)&grepl(",",tworca_nazwisko)&tworca_imie=="*",str_replace_all(tworca_nazwisko,",","|"),as.character(tworca_nazwisko))),
         tworca_imie = ifelse(is.na(tworca_imie),"",
                              ifelse(!is.na(tworca_nazwisko)&tworca_imie=="*","",as.character(tworca_imie)))) %>%
  cSplit(.,"tworca_nazwisko",sep = "|",direction = "long") %>%
  mutate(X600 = trim(ifelse(tworca_imie!="",paste("14$a",tworca_nazwisko,", ",tworca_imie,sep = ""),paste("14$a",tworca_nazwisko,sep = "")))) %>%
  select(rekord_id,X600) %>%
  group_by(rekord_id) %>%
  mutate(X600 = paste(X600,collapse = "|")) %>%
  ungroup() %>%
  unique() %>%
  mutate(X600 = str_remove(X600," \\*$|\\*$")) %>%
  full_join(.,pbl_articles %>% select(rekord_id) %>% unique(),by = "rekord_id") %>%
  arrange(rekord_id)
  
#X610
X610 <- pbl_articles %>%
  select(rekord_id,HP_NAZWA,KH_NAZWA) %>%
  unique() %>% 
  inner_join(.,pbl_hp %>% filter(MARC_FIELD=="24.61"),by = c("HP_NAZWA","KH_NAZWA")) %>%
  mutate(X610 = trim(ifelse(!is.na(KH_NAZWA),paste("24$a",HP_NAZWA,", ",KH_NAZWA,sep = ""),paste("24$a",HP_NAZWA,sep = "")))) %>%
  select(rekord_id,X610) %>%
  group_by(rekord_id) %>%
  mutate(X610 = paste(X610,collapse = "|")) %>%
  ungroup() %>%
  unique() %>%
  full_join(.,pbl_articles %>% select(rekord_id) %>% unique(),by = "rekord_id") %>%
  arrange(rekord_id)

#X611
X611 <- pbl_articles %>%
  select(rekord_id,HP_NAZWA,KH_NAZWA) %>%
  unique() %>% 
  inner_join(.,pbl_hp %>% filter(MARC_FIELD=="24.611"),by = c("HP_NAZWA","KH_NAZWA")) %>%
  mutate(X611 = trim(ifelse(!is.na(KH_NAZWA),paste("24$a",HP_NAZWA,", ",KH_NAZWA,sep = ""),paste("24$a",HP_NAZWA,sep = "")))) %>%
  select(rekord_id,X611) %>%
  group_by(rekord_id) %>%
  mutate(X611 = paste(X611,collapse = "|")) %>%
  ungroup() %>%
  unique() %>%
  full_join(.,pbl_articles %>% select(rekord_id) %>% unique(),by = "rekord_id") %>%
  arrange(rekord_id)

#X630
X630 <- pbl_articles %>%
  select(rekord_id,HP_NAZWA,KH_NAZWA) %>%
  unique() %>% 
  inner_join(.,pbl_hp %>% filter(MARC_FIELD=="4.63"),by = c("HP_NAZWA","KH_NAZWA")) %>%
  mutate(X630 = trim(ifelse(!is.na(KH_NAZWA),paste("\\4$a",HP_NAZWA,", ",KH_NAZWA,sep = ""),paste("\\4$a",HP_NAZWA,sep = "")))) %>%
  select(rekord_id,X630) %>%
  group_by(rekord_id) %>%
  mutate(X630 = paste(X630,collapse = "|")) %>%
  ungroup() %>%
  unique() %>%
  full_join(.,pbl_articles %>% select(rekord_id) %>% unique(),by = "rekord_id") %>%
  arrange(rekord_id)

#X650
X650 <- pbl_articles %>%
  select(rekord_id,HP_NAZWA,KH_NAZWA) %>%
  unique() %>% 
  inner_join(.,pbl_hp %>% filter(MARC_FIELD=="4.65"|MARC_FIELD=="24.65"),by = c("HP_NAZWA","KH_NAZWA")) %>%
  mutate(X650 = trim(ifelse(MARC_FIELD=="4.65",
                            ifelse(!is.na(KH_NAZWA),paste("04$a",HP_NAZWA,", ",KH_NAZWA,sep = ""),paste("04$a",HP_NAZWA,sep = "")),
                       ifelse(MARC_FIELD=="24.65",
                              ifelse(!is.na(KH_NAZWA),paste("24$a",HP_NAZWA,", ",KH_NAZWA,sep = ""),paste("24$a",HP_NAZWA,sep = "")),"")))) %>%
  select(rekord_id,X650) %>%
  group_by(rekord_id) %>%
  mutate(X650 = paste(X650,collapse = "|")) %>%
  ungroup() %>%
  unique() %>%
  full_join(.,pbl_articles %>% select(rekord_id) %>% unique(),by = "rekord_id") %>%
  arrange(rekord_id)

#X651
X651 <- pbl_articles %>%
  select(rekord_id,HP_NAZWA,KH_NAZWA) %>%
  unique() %>% 
  inner_join(.,pbl_hp %>% filter(MARC_FIELD=="4.651"),by = c("HP_NAZWA","KH_NAZWA")) %>%
  mutate(X651 = trim(ifelse(!is.na(KH_NAZWA),paste("\\4$a",HP_NAZWA,", ",KH_NAZWA,sep = ""),paste("\\4$a",HP_NAZWA,sep = "")))) %>%
  select(rekord_id,X651) %>%
  group_by(rekord_id) %>%
  mutate(X651 = paste(X651,collapse = "|")) %>%
  ungroup() %>%
  unique() %>%
  full_join(.,pbl_articles %>% select(rekord_id) %>% unique(),by = "rekord_id") %>%
  arrange(rekord_id)

#X655
X655 <- pbl_articles %>%
  select(rekord_id,rodzaj_zapisu) %>%
  unique() %>%
  rename(X655 = rodzaj_zapisu) %>%
  mutate(X655 = trim(paste("\\4$a",X655,sep = "")))
  
#X700
X700 <- pbl_articles %>%
  select(rekord_id,funkcja_osoby,wspoltworca_nazwisko,wspoltworca_imie) %>%
  unique() %>%
  mutate(X700 = trim(ifelse(is.na(wspoltworca_nazwisko),"",paste("1\\$a",wspoltworca_nazwisko,", ",wspoltworca_imie,"$e",funkcja_osoby,sep = "")))) %>%
  select(rekord_id,X700) %>%
  rbind(X100 %>% select(rekord_id,X700) %>% cSplit(.,"X700",sep = "|",direction = "long"),.) %>%
  arrange(rekord_id) %>%
  filter(!is.na(X700)&X700!="") %>%
  group_by(rekord_id) %>%
  mutate(X700 = paste(X700,collapse = "|")) %>%
  ungroup() %>%
  unique() %>%
  full_join(.,pbl_articles %>% select(rekord_id) %>% unique(),by = "rekord_id") %>%
  arrange(rekord_id)
X100 <- X100 %>%
  select(rekord_id,X100)
  
#773
X773 <- pbl_articles %>%
  select(rekord_id,czasopismo,rok,numer,strony) %>%
  unique() %>%
  mutate(X773 = paste("0\\$t",czasopismo,"$gR. ",rok,", ",numer,", ",strony,"$9",rok,sep = "")) %>%
  select(rekord_id,X773)

#X787
X787 <- pbl_articles %>%
  select(rekord_id,HP_NAZWA,KH_NAZWA) %>%
  unique() %>% 
  inner_join(.,pbl_hp %>% filter(MARC_FIELD=="787"),by = c("HP_NAZWA","KH_NAZWA")) %>%
  mutate(X787 = trim(ifelse(!is.na(KH_NAZWA),paste(HP_NAZWA,", ",KH_NAZWA,sep = ""),as.character(HP_NAZWA)))) %>%
  select(rekord_id,X787) %>%
  group_by(rekord_id) %>%
  mutate(X787 = paste(X787,collapse = "|")) %>%
  ungroup() %>%
  unique() %>%
  full_join(.,pbl_articles %>% select(rekord_id) %>% unique(),by = "rekord_id") %>%
  arrange(rekord_id)

#X964
X964 <- pbl_articles %>%
  select(rekord_id,dzial) %>%
  unique() %>%
  rename(X964 = dzial) %>%
  mutate(X964 = trim(str_replace(X964,"(.*)( - .$)","\\1")))
#XLKR
XLKR <- dbGetQuery(PBL,
                   "select z.za_zapis_id \"rekord_id\", z.za_za_zapis_id \"XLKR\"
                    from pbl_zapisy z
                    where z.za_type in ('PU','IZA')") %>%
  mutate(XLKR = ifelse(!is.na(XLKR),paste("pl",sprintf("%09d", XLKR),sep = ""),"")) %>%
  arrange(rekord_id)

pbl_marc_articles <- X005 %>%
  full_join(.,X008,by = "rekord_id") %>%
  full_join(.,X100,by = "rekord_id") %>%
  full_join(.,X240,by = "rekord_id") %>%
  full_join(.,X245,by = "rekord_id") %>%
  full_join(.,X520,by = "rekord_id") %>%
  full_join(.,X600,by = "rekord_id") %>%
  full_join(.,X610,by = "rekord_id") %>%
  full_join(.,X611,by = "rekord_id") %>%
  full_join(.,X630,by = "rekord_id") %>%
  full_join(.,X650,by = "rekord_id") %>%
  full_join(.,X651,by = "rekord_id") %>%
  full_join(.,X655,by = "rekord_id") %>%
  full_join(.,X700,by = "rekord_id") %>%
  full_join(.,X773,by = "rekord_id") %>%
  full_join(.,X787,by = "rekord_id") %>%
  full_join(.,X964,by = "rekord_id") %>%
  full_join(.,XLKR,by = "rekord_id") %>%
  cbind(.,LDR,X040,X001) %>%
  select(noquote(order(colnames(.))))

long <- reshape(pbl_marc_articles,
                direction = "long",
                varying = list(names(pbl_marc_articles)[-2]),
                v.names = "Value",
                idvar = "rekord_id",
                timevar = "fields",
                times = names(pbl_marc_articles)[-2]) %>%
  arrange(rekord_id) %>%
  mutate(Value = ifelse(is.na(Value)&fields=="X001",as.character(rekord_id),
                        ifelse(is.na(Value),"",as.character(Value))),
         fields = str_replace(fields,"^X{0,1}","=")) %>%
  cSplit(.,"Value",sep = "|",direction = "long") %>%
  mutate(Value = gsub("[\r\n]", " ",Value)) %>%
  select(fields,Value) %>%
  mutate(fields = ifelse(lead(fields=="=LDR"),paste(fields,"||",sep = ""),as.character(fields))) %>%
  mutate(Value = ifelse(lead(fields=="=LDR"),paste(Value,"||",sep = ""),as.character(Value))) %>%
  cSplit(.,c("fields","Value"),sep = "|",direction = "long") %>%
  write.table(., "pbl_marc_articles.csv", append = FALSE, sep = "  ", dec = ",", row.names = FALSE, col.names = FALSE, quote = FALSE, fileEncoding = "UTF-8")

```
