---
title: "R Notebook"
output: html_notebook
---

```{r loading data}
pacman::p_load(stringr,tidyverse,RJDBC,sqldf,dplyr,splitstackshape,svMisc,data.table)

#downloading files
bn_books <- read.csv2("C:/Users/Cezary/Downloads/pw_ksiazki.csv", encoding = "Windows-1250", header = TRUE, stringsAsFactors = FALSE) 
bn_articles <- read.csv2("C:/Users/Cezary/Downloads/pw_czasopisma.csv", encoding = "Windows-1250", header = TRUE, stringsAsFactors = FALSE) 
cz_books <- read.csv2("C:/Users/Cezary/Downloads/cz_pw_file_1.csv", encoding = "Windows-1250", header = TRUE, stringsAsFactors = FALSE) 
cz_articles <- read.csv2("C:/Users/Cezary/Downloads/cz_pw_file_2.csv", encoding = "Windows-1250", header = TRUE, stringsAsFactors = FALSE) 

#connecting to PBL database
jdbcDriver = JDBC("oracle.jdbc.OracleDriver",classPath="C:/Users/Cezary/Downloads/ojdbc6.jar")
PBL <- dbConnect(jdbcDriver, "jdbc:oracle:thin:@//pbl.ibl.poznan.pl:1521/xe", "IBL_SELECT", "CR333444")
pbl_articles1 <- dbGetQuery(PBL,
                        "select z.za_zapis_id \"rekord_id\", z.za_type \"typ\", rz.rz_rodzaj_id \"rodzaj_zapisu_id\", rz.rz_nazwa \"rodzaj_zapisu\", 
                          dz.dz_dzial_id \"dzial_id\", dz.dz_nazwa \"dzial\", to_char(tw.tw_tworca_id) \"tworca_id\", tw.tw_nazwisko \"tworca_nazwisko\",
                          tw.tw_imie \"tworca_imie\", to_char(a.am_autor_id) \"autor_id\", a.am_nazwisko \"autor_nazwisko\", 
                          a.am_imie \"autor_imie\", z.za_tytul \"tytul\", z.za_opis_wspoltworcow \"wspoltworcy\", fo.fo_nazwa \"funkcja_osoby\", 
                          to_char(os.os_osoba_id) \"wspoltworca_id\", os.os_nazwisko \"wspoltworca_nazwisko\", os.os_imie \"wspoltworca_imie\", 
                          z.za_adnotacje \"adnotacja\", to_char(zr.zr_zrodlo_id) \"czasopismo_id\", zr.zr_tytul \"czasopismo\", 
                          z.za_zrodlo_rok \"rok\", z.za_zrodlo_nr \"numer\", z.za_zrodlo_str \"strony\"
                        from pbl_zapisy z
                        join IBL_OWNER.pbl_zapisy_tworcy zt on zt.zatw_za_zapis_id=z.za_zapis_id
                        join IBL_OWNER.pbl_tworcy tw on zt.zatw_tw_tworca_id=tw.tw_tworca_id
                        join IBL_OWNER.pbl_zapisy_autorzy za on za.zaam_za_zapis_id=z.za_zapis_id
                        join IBL_OWNER.pbl_autorzy a on za.zaam_am_autor_id=a.am_autor_id
                        join IBL_OWNER.pbl_zrodla zr on zr.zr_zrodlo_id=z.za_zr_zrodlo_id
                        join IBL_OWNER.pbl_dzialy dz on dz.dz_dzial_id=z.za_dz_dzial1_id
                        join IBL_OWNER.pbl_rodzaje_zapisow rz on rz.rz_rodzaj_id=z.za_rz_rodzaj1_id
                        join IBL_OWNER.pbl_udzialy_osob uo on uo.uo_za_zapis_id = z.za_zapis_id
                        join IBL_OWNER.pbl_osoby os on uo.uo_os_osoba_id=os.os_osoba_id
                        join IBL_OWNER.pbl_funkcje_osob fo on fo.fo_symbol=uo.uo_fo_symbol
                        where z.za_uzytk_wpis_data between '2019/05/01' and '2019/06/30'
                        and z.za_uzytk_wpisal like 'ANIA'
                        and z.za_ro_rok<2000")
pbl_articles2 <- dbGetQuery(PBL,
                          "select z.za_zapis_id \"rekord_id\", z.za_type \"typ\", rz.rz_rodzaj_id \"rodzaj_zapisu_id\", rz.rz_nazwa \"rodzaj_zapisu\", 
                            dz.dz_dzial_id \"dzial_id\", dz.dz_nazwa \"dzial\", to_char(tw.tw_tworca_id) \"tworca_id\", tw.tw_nazwisko \"tworca_nazwisko\",
                            tw.tw_imie \"tworca_imie\", to_char(a.am_autor_id) \"autor_id\", a.am_nazwisko \"autor_nazwisko\", 
                            a.am_imie \"autor_imie\", z.za_tytul \"tytul\", z.za_opis_wspoltworcow \"wspoltworcy\", to_char(null) \"funkcja_osoby\", 
                            to_char(null) \"wspoltworca_id\", to_char(null) \"wspoltworca_nazwisko\", to_char(null) \"wspoltworca_imie\", 
                            z.za_adnotacje \"adnotacja\", to_char(zr.zr_zrodlo_id) \"czasopismo_id\", zr.zr_tytul \"czasopismo\", 
                            z.za_zrodlo_rok \"rok\", z.za_zrodlo_nr \"numer\", z.za_zrodlo_str \"strony\"
                          from pbl_zapisy z
                          join IBL_OWNER.pbl_zapisy_tworcy zt on zt.zatw_za_zapis_id=z.za_zapis_id
                          join IBL_OWNER.pbl_tworcy tw on zt.zatw_tw_tworca_id=tw.tw_tworca_id
                          join IBL_OWNER.pbl_zapisy_autorzy za on za.zaam_za_zapis_id=z.za_zapis_id
                          join IBL_OWNER.pbl_autorzy a on za.zaam_am_autor_id=a.am_autor_id
                          join IBL_OWNER.pbl_zrodla zr on zr.zr_zrodlo_id=z.za_zr_zrodlo_id
                          join IBL_OWNER.pbl_dzialy dz on dz.dz_dzial_id=z.za_dz_dzial1_id
                          join IBL_OWNER.pbl_rodzaje_zapisow rz on rz.rz_rodzaj_id=z.za_rz_rodzaj1_id
                          where z.za_uzytk_wpis_data between '2019/05/01' and '2019/06/30'
                          and z.za_uzytk_wpisal like 'ANIA'
                          and z.za_ro_rok<2000")
pbl_articles3 <- dbGetQuery(PBL,
                            "select z.za_zapis_id \"rekord_id\", z.za_type \"typ\", rz.rz_rodzaj_id \"rodzaj_zapisu_id\", rz.rz_nazwa \"rodzaj_zapisu\", 
                                    dz.dz_dzial_id \"dzial_id\", dz.dz_nazwa \"dzial\", to_char(tw.tw_tworca_id) \"tworca_id\", tw.tw_nazwisko \"tworca_nazwisko\",
                                    tw.tw_imie \"tworca_imie\", to_char(null) \"autor_id\", to_char(null) \"autor_nazwisko\", 
                                    to_char(null) \"autor_imie\", z.za_tytul \"tytul\", z.za_opis_wspoltworcow \"wspoltworcy\", fo.fo_nazwa \"funkcja_osoby\", 
                                    to_char(os.os_osoba_id) \"wspoltworca_id\", os.os_nazwisko \"wspoltworca_nazwisko\", os.os_imie \"wspoltworca_imie\", 
                                    z.za_adnotacje \"adnotacja\", to_char(zr.zr_zrodlo_id) \"czasopismo_id\", zr.zr_tytul \"czasopismo\", 
                                    z.za_zrodlo_rok \"rok\", z.za_zrodlo_nr \"numer\", z.za_zrodlo_str \"strony\"
                            from pbl_zapisy z
                            join IBL_OWNER.pbl_zapisy_tworcy zt on zt.zatw_za_zapis_id=z.za_zapis_id
                            join IBL_OWNER.pbl_tworcy tw on zt.zatw_tw_tworca_id=tw.tw_tworca_id
                            join IBL_OWNER.pbl_zrodla zr on zr.zr_zrodlo_id=z.za_zr_zrodlo_id
                            join IBL_OWNER.pbl_dzialy dz on dz.dz_dzial_id=z.za_dz_dzial1_id
                            join IBL_OWNER.pbl_rodzaje_zapisow rz on rz.rz_rodzaj_id=z.za_rz_rodzaj1_id
                            join IBL_OWNER.pbl_udzialy_osob uo on uo.uo_za_zapis_id = z.za_zapis_id
                            join IBL_OWNER.pbl_osoby os on uo.uo_os_osoba_id=os.os_osoba_id
                            join IBL_OWNER.pbl_funkcje_osob fo on fo.fo_symbol=uo.uo_fo_symbol
                            where z.za_uzytk_wpis_data between '2019/05/01' and '2019/06/30'
                            and z.za_uzytk_wpisal like 'ANIA'
                            and z.za_ro_rok<2000")
pbl_articles4 <- dbGetQuery(PBL,
                            "select z.za_zapis_id \"rekord_id\", z.za_type \"typ\", rz.rz_rodzaj_id \"rodzaj_zapisu_id\", rz.rz_nazwa \"rodzaj_zapisu\", 
                                    dz.dz_dzial_id \"dzial_id\", dz.dz_nazwa \"dzial\", to_char(tw.tw_tworca_id) \"tworca_id\", tw.tw_nazwisko \"tworca_nazwisko\",
                                    tw.tw_imie \"tworca_imie\", to_char(null) \"autor_id\", to_char(null) \"autor_nazwisko\", 
                                    to_char(null) \"autor_imie\", z.za_tytul \"tytul\", z.za_opis_wspoltworcow \"wspoltworcy\", to_char(null) \"funkcja_osoby\", 
                                    to_char(null) \"wspoltworca_id\", to_char(null) \"wspoltworca_nazwisko\", to_char(null) \"wspoltworca_imie\", 
                                    z.za_adnotacje \"adnotacja\", to_char(zr.zr_zrodlo_id) \"czasopismo_id\", zr.zr_tytul \"czasopismo\", 
                                    z.za_zrodlo_rok \"rok\", z.za_zrodlo_nr \"numer\", z.za_zrodlo_str \"strony\"
                            from pbl_zapisy z
                            join IBL_OWNER.pbl_zapisy_tworcy zt on zt.zatw_za_zapis_id=z.za_zapis_id
                            join IBL_OWNER.pbl_tworcy tw on zt.zatw_tw_tworca_id=tw.tw_tworca_id
                            join IBL_OWNER.pbl_zrodla zr on zr.zr_zrodlo_id=z.za_zr_zrodlo_id
                            join IBL_OWNER.pbl_dzialy dz on dz.dz_dzial_id=z.za_dz_dzial1_id
                            join IBL_OWNER.pbl_rodzaje_zapisow rz on rz.rz_rodzaj_id=z.za_rz_rodzaj1_id
                            where z.za_uzytk_wpis_data between '2019/05/01' and '2019/06/30'
                            and z.za_uzytk_wpisal like 'ANIA'
                            and z.za_ro_rok<2000")

pbl_articles <- sqldf("select *
              from pbl_articles1 a
              UNION
              select *
              from pbl_articles2 b
              where b.rekord_id not in (select a.rekord_id
              from pbl_articles1 a)")
pbl_articles <- sqldf("select *
                      from pbl_articles a
                      UNION
                      select * 
                      from pbl_articles3 b
                      where b.rekord_id not in (select a.rekord_id
                      from pbl_articles a)")
pbl_articles <- sqldf("select *
                      from pbl_articles a
                      UNION
                      select *
                      from pbl_articles4 b
                      where b.rekord_id not in (select a.rekord_id
                      from pbl_articles a)")
pbl_articles1 <- dbGetQuery(PBL,
                        "select z.za_zapis_id \"rekord_id\", z.za_type \"typ\", rz.rz_rodzaj_id \"rodzaj_zapisu_id\", rz.rz_nazwa \"rodzaj_zapisu\", 
                          dz.dz_dzial_id \"dzial_id\", dz.dz_nazwa \"dzial\", to_char(null) \"tworca_id\", to_char(null) \"tworca_nazwisko\",
                          to_char(null) \"tworca_imie\", to_char(a.am_autor_id) \"autor_id\", a.am_nazwisko \"autor_nazwisko\", 
                          a.am_imie \"autor_imie\", z.za_tytul \"tytul\", z.za_opis_wspoltworcow \"wspoltworcy\", fo.fo_nazwa \"funkcja_osoby\", 
                          to_char(os.os_osoba_id) \"wspoltworca_id\", os.os_nazwisko \"wspoltworca_nazwisko\", os.os_imie \"wspoltworca_imie\", 
                          z.za_adnotacje \"adnotacja\", to_char(zr.zr_zrodlo_id) \"czasopismo_id\", zr.zr_tytul \"czasopismo\", 
                          z.za_zrodlo_rok \"rok\", z.za_zrodlo_nr \"numer\", z.za_zrodlo_str \"strony\"
                        from pbl_zapisy z
                        join IBL_OWNER.pbl_zapisy_autorzy za on za.zaam_za_zapis_id=z.za_zapis_id
                        join IBL_OWNER.pbl_autorzy a on za.zaam_am_autor_id=a.am_autor_id
                        join IBL_OWNER.pbl_zrodla zr on zr.zr_zrodlo_id=z.za_zr_zrodlo_id
                        join IBL_OWNER.pbl_dzialy dz on dz.dz_dzial_id=z.za_dz_dzial1_id
                        join IBL_OWNER.pbl_rodzaje_zapisow rz on rz.rz_rodzaj_id=z.za_rz_rodzaj1_id
                        join IBL_OWNER.pbl_udzialy_osob uo on uo.uo_za_zapis_id = z.za_zapis_id
                        join IBL_OWNER.pbl_osoby os on uo.uo_os_osoba_id=os.os_osoba_id
                        join IBL_OWNER.pbl_funkcje_osob fo on fo.fo_symbol=uo.uo_fo_symbol
                        where z.za_uzytk_wpis_data between '2019/05/01' and '2019/06/30'
                        and z.za_uzytk_wpisal like 'ANIA'
                        and z.za_ro_rok<2000")
pbl_articles2 <- dbGetQuery(PBL,
                          "select z.za_zapis_id \"rekord_id\", z.za_type \"typ\", rz.rz_rodzaj_id \"rodzaj_zapisu_id\", rz.rz_nazwa \"rodzaj_zapisu\", 
                            dz.dz_dzial_id \"dzial_id\", dz.dz_nazwa \"dzial\", to_char(null) \"tworca_id\", to_char(null) \"tworca_nazwisko\",
                            to_char(null) \"tworca_imie\", to_char(a.am_autor_id) \"autor_id\", a.am_nazwisko \"autor_nazwisko\", 
                            a.am_imie \"autor_imie\", z.za_tytul \"tytul\", z.za_opis_wspoltworcow \"wspoltworcy\", to_char(null) \"funkcja_osoby\", 
                            to_char(null) \"wspoltworca_id\", to_char(null) \"wspoltworca_nazwisko\", to_char(null) \"wspoltworca_imie\", 
                            z.za_adnotacje \"adnotacja\", to_char(zr.zr_zrodlo_id) \"czasopismo_id\", zr.zr_tytul \"czasopismo\", 
                            z.za_zrodlo_rok \"rok\", z.za_zrodlo_nr \"numer\", z.za_zrodlo_str \"strony\"
                          from pbl_zapisy z
                          join IBL_OWNER.pbl_zapisy_autorzy za on za.zaam_za_zapis_id=z.za_zapis_id
                          join IBL_OWNER.pbl_autorzy a on za.zaam_am_autor_id=a.am_autor_id
                          join IBL_OWNER.pbl_zrodla zr on zr.zr_zrodlo_id=z.za_zr_zrodlo_id
                          join IBL_OWNER.pbl_dzialy dz on dz.dz_dzial_id=z.za_dz_dzial1_id
                          join IBL_OWNER.pbl_rodzaje_zapisow rz on rz.rz_rodzaj_id=z.za_rz_rodzaj1_id
                          where z.za_uzytk_wpis_data between '2019/05/01' and '2019/06/30'
                          and z.za_uzytk_wpisal like 'ANIA'
                          and z.za_ro_rok<2000")
pbl_articles3 <- dbGetQuery(PBL,
                            "select z.za_zapis_id \"rekord_id\", z.za_type \"typ\", rz.rz_rodzaj_id \"rodzaj_zapisu_id\", rz.rz_nazwa \"rodzaj_zapisu\", 
                                    dz.dz_dzial_id \"dzial_id\", dz.dz_nazwa \"dzial\", to_char(null) \"tworca_id\", to_char(null) \"tworca_nazwisko\",
                                    to_char(null) \"tworca_imie\", to_char(null) \"autor_id\", to_char(null) \"autor_nazwisko\", 
                                    to_char(null) \"autor_imie\", z.za_tytul \"tytul\", z.za_opis_wspoltworcow \"wspoltworcy\", fo.fo_nazwa \"funkcja_osoby\", 
                                    to_char(os.os_osoba_id) \"wspoltworca_id\", os.os_nazwisko \"wspoltworca_nazwisko\", os.os_imie \"wspoltworca_imie\", 
                                    z.za_adnotacje \"adnotacja\", to_char(zr.zr_zrodlo_id) \"czasopismo_id\", zr.zr_tytul \"czasopismo\", 
                                    z.za_zrodlo_rok \"rok\", z.za_zrodlo_nr \"numer\", z.za_zrodlo_str \"strony\"
                            from pbl_zapisy z
                            join IBL_OWNER.pbl_zrodla zr on zr.zr_zrodlo_id=z.za_zr_zrodlo_id
                            join IBL_OWNER.pbl_dzialy dz on dz.dz_dzial_id=z.za_dz_dzial1_id
                            join IBL_OWNER.pbl_rodzaje_zapisow rz on rz.rz_rodzaj_id=z.za_rz_rodzaj1_id
                            join IBL_OWNER.pbl_udzialy_osob uo on uo.uo_za_zapis_id = z.za_zapis_id
                            join IBL_OWNER.pbl_osoby os on uo.uo_os_osoba_id=os.os_osoba_id
                            join IBL_OWNER.pbl_funkcje_osob fo on fo.fo_symbol=uo.uo_fo_symbol
                            where z.za_uzytk_wpis_data between '2019/05/01' and '2019/06/30'
                            and z.za_uzytk_wpisal like 'ANIA'
                            and z.za_ro_rok<2000")
pbl_articles4 <- dbGetQuery(PBL,
                            "select z.za_zapis_id \"rekord_id\", z.za_type \"typ\", rz.rz_rodzaj_id \"rodzaj_zapisu_id\", rz.rz_nazwa \"rodzaj_zapisu\", 
                                    dz.dz_dzial_id \"dzial_id\", dz.dz_nazwa \"dzial\", to_char(null) \"tworca_id\", to_char(null) \"tworca_nazwisko\",
                                    to_char(null) \"tworca_imie\", to_char(null) \"autor_id\", to_char(null) \"autor_nazwisko\", 
                                    to_char(null) \"autor_imie\", z.za_tytul \"tytul\", z.za_opis_wspoltworcow \"wspoltworcy\", to_char(null) \"funkcja_osoby\", 
                                    to_char(null) \"wspoltworca_id\", to_char(null) \"wspoltworca_nazwisko\", to_char(null) \"wspoltworca_imie\", 
                                    z.za_adnotacje \"adnotacja\", to_char(zr.zr_zrodlo_id) \"czasopismo_id\", zr.zr_tytul \"czasopismo\", 
                                    z.za_zrodlo_rok \"rok\", z.za_zrodlo_nr \"numer\", z.za_zrodlo_str \"strony\"
                            from pbl_zapisy z
                            join IBL_OWNER.pbl_zrodla zr on zr.zr_zrodlo_id=z.za_zr_zrodlo_id
                            join IBL_OWNER.pbl_dzialy dz on dz.dz_dzial_id=z.za_dz_dzial1_id
                            join IBL_OWNER.pbl_rodzaje_zapisow rz on rz.rz_rodzaj_id=z.za_rz_rodzaj1_id
                            where z.za_uzytk_wpis_data between '2019/05/01' and '2019/06/30'
                            and z.za_uzytk_wpisal like 'ANIA'
                            and z.za_ro_rok<2000")

pbl_articles1 <- sqldf("select *
              from pbl_articles1 a
              UNION
              select *
              from pbl_articles2 b
              where b.rekord_id not in (select a.rekord_id
              from pbl_articles1 a)")
pbl_articles1 <- sqldf("select *
                      from pbl_articles a
                      UNION
                      select * 
                      from pbl_articles3 b
                      where b.rekord_id not in (select a.rekord_id
                      from pbl_articles1 a)")
pbl_articles1 <- sqldf("select *
                      from pbl_articles a
                      UNION
                      select *
                      from pbl_articles4 b
                      where b.rekord_id not in (select a.rekord_id
                      from pbl_articles1 a)")
pbl_articles <- sqldf("select *
              from pbl_articles a
              UNION
              select *
              from pbl_articles1 b
              where b.rekord_id not in (select a.rekord_id
              from pbl_articles a)")

hasla_przekrojowe <- dbGetQuery(PBL,
                                "select hpz.hz_za_zapis_id,hp.hp_nazwa,khp.kh_nazwa
                                from IBL_OWNER.pbl_hasla_przekrojowe hp
                                join IBL_OWNER.pbl_hasla_przekr_zapisow hpz on hpz.hz_hp_haslo_id=hp.hp_haslo_id
                                join IBL_OWNER.pbl_klucze_hasla_przekr khp on khp.kh_hp_haslo_id=hp.hp_haslo_id
                                join IBL_OWNER.pbl_hasla_zapisow_klucze hzk on hzk.hzkh_hz_hp_haslo_id=hp.hp_haslo_id and hzk.hzkh_kh_klucz_id=khp.kh_klucz_id and hzk.hzkh_hz_za_zapis_id=hpz.hz_za_zapis_id")

hasla_przekrojowe2 <- dbGetQuery(PBL,
                                 "select hpz.hz_za_zapis_id,hp.hp_nazwa,to_char(null) \"KH_NAZWA\"
from IBL_OWNER.pbl_hasla_przekrojowe hp
join IBL_OWNER.pbl_hasla_przekr_zapisow hpz on hpz.hz_hp_haslo_id=hp.hp_haslo_id")

hasla_przekrojowe <- sqldf("select *
              from hasla_przekrojowe a
              UNION
              select *
              from hasla_przekrojowe2 b
              where b.HZ_ZA_ZAPIS_ID||'|'||HP_NAZWA not in (select a.HZ_ZA_ZAPIS_ID||'|'||HP_NAZWA
              from hasla_przekrojowe a)")

indeks_osobowy <- dbGetQuery(PBL,
                             "select odi_za_zapis_id, odi_nazwisko, odi_imie
                              from IBL_OWNER.pbl_osoby_do_indeksu")

pbl_articles <- merge(pbl_articles,indeks_osobowy,by.x = "rekord_id",by.y = "ODI_ZA_ZAPIS_ID", all.x = TRUE)
pbl_articles <- merge(pbl_articles,hasla_przekrojowe,by.x = "rekord_id", by.y = "HZ_ZA_ZAPIS_ID", all.x = TRUE)

#write.csv2(pbl_articles, "C:/Users/Cezary/Downloads/pbl_articles.csv", row.names = F, na = '', fileEncoding = 'Windows-1250')

pbl_books1 <- dbGetQuery(PBL,
                        "select z.za_zapis_id \"rekord_id\", z.za_type \"typ\", rz.rz_rodzaj_id \"rodzaj_zapisu_id\", rz.rz_nazwa \"rodzaj_zapisu\", 
                          dz.dz_dzial_id \"dzial_id\", dz.dz_nazwa \"dzial\", to_char(tw.tw_tworca_id) \"tworca_id\", tw.tw_nazwisko \"tworca_nazwisko\",
                          tw.tw_imie \"tworca_imie\", to_char(a.am_autor_id) \"autor_id\", a.am_nazwisko \"autor_nazwisko\", 
                          a.am_imie \"autor_imie\", z.za_tytul \"tytul\", z.za_opis_wspoltworcow \"wspoltworcy\", fo.fo_nazwa \"funkcja_osoby\", 
                          to_char(os.os_osoba_id) \"wspoltworca_id\", os.os_nazwisko \"wspoltworca_nazwisko\", os.os_imie \"wspoltworca_imie\", 
                          z.za_adnotacje \"adnotacja\", w.wy_nazwa \"wydawnictwo\", w.wy_miasto \"miejscowosc\", z.za_rok_wydania \"rok_wydania\", z.za_opis_fizyczny_ksiazki \"opis_fizyczny\", z.za_uzytk_wpisal, z.za_ro_rok
                        from pbl_zapisy z
                        join IBL_OWNER.pbl_zapisy_tworcy zt on zt.zatw_za_zapis_id=z.za_zapis_id
                        join IBL_OWNER.pbl_tworcy tw on zt.zatw_tw_tworca_id=tw.tw_tworca_id
                        join IBL_OWNER.pbl_zapisy_autorzy za on za.zaam_za_zapis_id=z.za_zapis_id
                        join IBL_OWNER.pbl_autorzy a on za.zaam_am_autor_id=a.am_autor_id
                        join IBL_OWNER.pbl_zapisy_wydawnictwa zw on zw.zawy_za_zapis_id=z.za_zapis_id 
						join IBL_OWNER.pbl_wydawnictwa w on zw.zawy_wy_wydawnictwo_id=w.wy_wydawnictwo_id
                        join IBL_OWNER.pbl_dzialy dz on dz.dz_dzial_id=z.za_dz_dzial1_id
                        join IBL_OWNER.pbl_rodzaje_zapisow rz on rz.rz_rodzaj_id=z.za_rz_rodzaj1_id
                        join IBL_OWNER.pbl_udzialy_osob uo on uo.uo_za_zapis_id = z.za_zapis_id
                        join IBL_OWNER.pbl_osoby os on uo.uo_os_osoba_id=os.os_osoba_id
                        join IBL_OWNER.pbl_funkcje_osob fo on fo.fo_symbol=uo.uo_fo_symbol
                        where z.za_uzytk_wpis_data between '2019/05/01' and '2019/06/30'
                        and z.za_uzytk_wpisal like 'ANIA'
                        and z.za_ro_rok<2000")
pbl_books2 <- dbGetQuery(PBL,
                          "select z.za_zapis_id \"rekord_id\", z.za_type \"typ\", rz.rz_rodzaj_id \"rodzaj_zapisu_id\", rz.rz_nazwa \"rodzaj_zapisu\", 
                            dz.dz_dzial_id \"dzial_id\", dz.dz_nazwa \"dzial\", to_char(tw.tw_tworca_id) \"tworca_id\", tw.tw_nazwisko \"tworca_nazwisko\",
                            tw.tw_imie \"tworca_imie\", to_char(a.am_autor_id) \"autor_id\", a.am_nazwisko \"autor_nazwisko\", 
                            a.am_imie \"autor_imie\", z.za_tytul \"tytul\", z.za_opis_wspoltworcow \"wspoltworcy\", to_char(null) \"funkcja_osoby\", 
                            to_char(null) \"wspoltworca_id\", to_char(null) \"wspoltworca_nazwisko\", to_char(null) \"wspoltworca_imie\", 
                            z.za_adnotacje \"adnotacja\", w.wy_nazwa \"wydawnictwo\", w.wy_miasto \"miejscowosc\", z.za_rok_wydania \"rok_wydania\", z.za_opis_fizyczny_ksiazki \"opis_fizyczny\", z.za_uzytk_wpisal, z.za_ro_rok
                          from pbl_zapisy z
                          join IBL_OWNER.pbl_zapisy_tworcy zt on zt.zatw_za_zapis_id=z.za_zapis_id
                          join IBL_OWNER.pbl_tworcy tw on zt.zatw_tw_tworca_id=tw.tw_tworca_id
                          join IBL_OWNER.pbl_zapisy_autorzy za on za.zaam_za_zapis_id=z.za_zapis_id
                          join IBL_OWNER.pbl_autorzy a on za.zaam_am_autor_id=a.am_autor_id
                          join IBL_OWNER.pbl_zapisy_wydawnictwa zw on zw.zawy_za_zapis_id=z.za_zapis_id 
						  join IBL_OWNER.pbl_wydawnictwa w on zw.zawy_wy_wydawnictwo_id=w.wy_wydawnictwo_id
                          join IBL_OWNER.pbl_dzialy dz on dz.dz_dzial_id=z.za_dz_dzial1_id
                          join IBL_OWNER.pbl_rodzaje_zapisow rz on rz.rz_rodzaj_id=z.za_rz_rodzaj1_id
                          where z.za_uzytk_wpis_data between '2019/05/01' and '2019/06/30'
                          and z.za_uzytk_wpisal like 'ANIA'
                          and z.za_ro_rok<2000")
pbl_books3 <- dbGetQuery(PBL,
                            "select z.za_zapis_id \"rekord_id\", z.za_type \"typ\", rz.rz_rodzaj_id \"rodzaj_zapisu_id\", rz.rz_nazwa \"rodzaj_zapisu\", 
                                    dz.dz_dzial_id \"dzial_id\", dz.dz_nazwa \"dzial\", to_char(tw.tw_tworca_id) \"tworca_id\", tw.tw_nazwisko \"tworca_nazwisko\",
                                    tw.tw_imie \"tworca_imie\", to_char(null) \"autor_id\", to_char(null) \"autor_nazwisko\", 
                                    to_char(null) \"autor_imie\", z.za_tytul \"tytul\", z.za_opis_wspoltworcow \"wspoltworcy\", fo.fo_nazwa \"funkcja_osoby\", 
                                    to_char(os.os_osoba_id) \"wspoltworca_id\", os.os_nazwisko \"wspoltworca_nazwisko\", os.os_imie \"wspoltworca_imie\", 
                                    z.za_adnotacje \"adnotacja\", w.wy_nazwa \"wydawnictwo\", w.wy_miasto \"miejscowosc\", z.za_rok_wydania \"rok_wydania\", z.za_opis_fizyczny_ksiazki \"opis_fizyczny\", z.za_uzytk_wpisal, z.za_ro_rok  
                            from pbl_zapisy z
                            join IBL_OWNER.pbl_zapisy_tworcy zt on zt.zatw_za_zapis_id=z.za_zapis_id
                            join IBL_OWNER.pbl_tworcy tw on zt.zatw_tw_tworca_id=tw.tw_tworca_id
                            join IBL_OWNER.pbl_zapisy_wydawnictwa zw on zw.zawy_za_zapis_id=z.za_zapis_id 
							join IBL_OWNER.pbl_wydawnictwa w on zw.zawy_wy_wydawnictwo_id=w.wy_wydawnictwo_id
                            join IBL_OWNER.pbl_dzialy dz on dz.dz_dzial_id=z.za_dz_dzial1_id
                            join IBL_OWNER.pbl_rodzaje_zapisow rz on rz.rz_rodzaj_id=z.za_rz_rodzaj1_id
                            join IBL_OWNER.pbl_udzialy_osob uo on uo.uo_za_zapis_id = z.za_zapis_id
                            join IBL_OWNER.pbl_osoby os on uo.uo_os_osoba_id=os.os_osoba_id
                            join IBL_OWNER.pbl_funkcje_osob fo on fo.fo_symbol=uo.uo_fo_symbol
                            where z.za_uzytk_wpis_data between '2019/05/01' and '2019/06/30'
                            and z.za_uzytk_wpisal like 'ANIA'
                            and z.za_ro_rok<2000")
pbl_books4 <- dbGetQuery(PBL,
                            "select z.za_zapis_id \"rekord_id\", z.za_type \"typ\", rz.rz_rodzaj_id \"rodzaj_zapisu_id\", rz.rz_nazwa \"rodzaj_zapisu\", 
                                    dz.dz_dzial_id \"dzial_id\", dz.dz_nazwa \"dzial\", to_char(tw.tw_tworca_id) \"tworca_id\", tw.tw_nazwisko \"tworca_nazwisko\",
                                    tw.tw_imie \"tworca_imie\", to_char(null) \"autor_id\", to_char(null) \"autor_nazwisko\", 
                                    to_char(null) \"autor_imie\", z.za_tytul \"tytul\", z.za_opis_wspoltworcow \"wspoltworcy\", to_char(null) \"funkcja_osoby\", 
                                    to_char(null) \"wspoltworca_id\", to_char(null) \"wspoltworca_nazwisko\", to_char(null) \"wspoltworca_imie\", 
                                    z.za_adnotacje \"adnotacja\", w.wy_nazwa \"wydawnictwo\", w.wy_miasto \"miejscowosc\", z.za_rok_wydania \"rok_wydania\", z.za_opis_fizyczny_ksiazki \"opis_fizyczny\", z.za_uzytk_wpisal, z.za_ro_rok 
                            from pbl_zapisy z
                            join IBL_OWNER.pbl_zapisy_tworcy zt on zt.zatw_za_zapis_id=z.za_zapis_id
                            join IBL_OWNER.pbl_tworcy tw on zt.zatw_tw_tworca_id=tw.tw_tworca_id
                            join IBL_OWNER.pbl_zapisy_wydawnictwa zw on zw.zawy_za_zapis_id=z.za_zapis_id 
							join IBL_OWNER.pbl_wydawnictwa w on zw.zawy_wy_wydawnictwo_id=w.wy_wydawnictwo_id
                            join IBL_OWNER.pbl_dzialy dz on dz.dz_dzial_id=z.za_dz_dzial1_id
                            join IBL_OWNER.pbl_rodzaje_zapisow rz on rz.rz_rodzaj_id=z.za_rz_rodzaj1_id
                            where z.za_uzytk_wpis_data between '2019/05/01' and '2019/06/30'
                            and z.za_uzytk_wpisal like 'ANIA'
                            and z.za_ro_rok<2000")

pbl_books <- sqldf("select *
              from pbl_books1 a
              UNION
              select *
              from pbl_books2 b
              where b.rekord_id not in (select a.rekord_id
              from pbl_books1 a)")
pbl_books <- sqldf("select *
                      from pbl_books a
                      UNION
                      select * 
                      from pbl_books3 b
                      where b.rekord_id not in (select a.rekord_id
                      from pbl_books a)")
pbl_books <- sqldf("select *
                      from pbl_books a
                      UNION
                      select *
                      from pbl_books4 b
                      where b.rekord_id not in (select a.rekord_id
                      from pbl_books a)")
pbl_books1 <- dbGetQuery(PBL,
                        "select z.za_zapis_id \"rekord_id\", z.za_type \"typ\", rz.rz_rodzaj_id \"rodzaj_zapisu_id\", rz.rz_nazwa \"rodzaj_zapisu\", 
                          dz.dz_dzial_id \"dzial_id\", dz.dz_nazwa \"dzial\", to_char(null) \"tworca_id\", to_char(null) \"tworca_nazwisko\",
                          to_char(null) \"tworca_imie\", to_char(a.am_autor_id) \"autor_id\", a.am_nazwisko \"autor_nazwisko\", 
                          a.am_imie \"autor_imie\", z.za_tytul \"tytul\", z.za_opis_wspoltworcow \"wspoltworcy\", fo.fo_nazwa \"funkcja_osoby\", 
                          to_char(os.os_osoba_id) \"wspoltworca_id\", os.os_nazwisko \"wspoltworca_nazwisko\", os.os_imie \"wspoltworca_imie\", 
                          z.za_adnotacje \"adnotacja\", w.wy_nazwa \"wydawnictwo\", w.wy_miasto \"miejscowosc\", z.za_rok_wydania \"rok_wydania\", z.za_opis_fizyczny_ksiazki \"opis_fizyczny\", z.za_uzytk_wpisal, z.za_ro_rok
                        from pbl_zapisy z
                        join IBL_OWNER.pbl_zapisy_autorzy za on za.zaam_za_zapis_id=z.za_zapis_id
                        join IBL_OWNER.pbl_autorzy a on za.zaam_am_autor_id=a.am_autor_id
                        join IBL_OWNER.pbl_zapisy_wydawnictwa zw on zw.zawy_za_zapis_id=z.za_zapis_id 
						join IBL_OWNER.pbl_wydawnictwa w on zw.zawy_wy_wydawnictwo_id=w.wy_wydawnictwo_id
                        join IBL_OWNER.pbl_dzialy dz on dz.dz_dzial_id=z.za_dz_dzial1_id
                        join IBL_OWNER.pbl_rodzaje_zapisow rz on rz.rz_rodzaj_id=z.za_rz_rodzaj1_id
                        join IBL_OWNER.pbl_udzialy_osob uo on uo.uo_za_zapis_id = z.za_zapis_id
                        join IBL_OWNER.pbl_osoby os on uo.uo_os_osoba_id=os.os_osoba_id
                        join IBL_OWNER.pbl_funkcje_osob fo on fo.fo_symbol=uo.uo_fo_symbol
                        where z.za_uzytk_wpis_data between '2019/05/01' and '2019/06/30'
                        and z.za_uzytk_wpisal like 'ANIA'
                        and z.za_ro_rok<2000")
pbl_books2 <- dbGetQuery(PBL,
                          "select z.za_zapis_id \"rekord_id\", z.za_type \"typ\", rz.rz_rodzaj_id \"rodzaj_zapisu_id\", rz.rz_nazwa \"rodzaj_zapisu\", 
                            dz.dz_dzial_id \"dzial_id\", dz.dz_nazwa \"dzial\", to_char(null) \"tworca_id\", to_char(null) \"tworca_nazwisko\",
                            to_char(null) \"tworca_imie\", to_char(a.am_autor_id) \"autor_id\", a.am_nazwisko \"autor_nazwisko\", 
                            a.am_imie \"autor_imie\", z.za_tytul \"tytul\", z.za_opis_wspoltworcow \"wspoltworcy\", to_char(null) \"funkcja_osoby\", 
                            to_char(null) \"wspoltworca_id\", to_char(null) \"wspoltworca_nazwisko\", to_char(null) \"wspoltworca_imie\", 
                            z.za_adnotacje \"adnotacja\", w.wy_nazwa \"wydawnictwo\", w.wy_miasto \"miejscowosc\", z.za_rok_wydania \"rok_wydania\", z.za_opis_fizyczny_ksiazki \"opis_fizyczny\", z.za_uzytk_wpisal, z.za_ro_rok
                          from pbl_zapisy z
                          join IBL_OWNER.pbl_zapisy_autorzy za on za.zaam_za_zapis_id=z.za_zapis_id
                          join IBL_OWNER.pbl_autorzy a on za.zaam_am_autor_id=a.am_autor_id
                          join IBL_OWNER.pbl_zapisy_wydawnictwa zw on zw.zawy_za_zapis_id=z.za_zapis_id 
						  join IBL_OWNER.pbl_wydawnictwa w on zw.zawy_wy_wydawnictwo_id=w.wy_wydawnictwo_id
                          join IBL_OWNER.pbl_dzialy dz on dz.dz_dzial_id=z.za_dz_dzial1_id
                          join IBL_OWNER.pbl_rodzaje_zapisow rz on rz.rz_rodzaj_id=z.za_rz_rodzaj1_id
                          where z.za_uzytk_wpis_data between '2019/05/01' and '2019/06/30'
                          and z.za_uzytk_wpisal like 'ANIA'
                          and z.za_ro_rok<2000")
pbl_books3 <- dbGetQuery(PBL,
                            "select z.za_zapis_id \"rekord_id\", z.za_type \"typ\", rz.rz_rodzaj_id \"rodzaj_zapisu_id\", rz.rz_nazwa \"rodzaj_zapisu\", 
                                    dz.dz_dzial_id \"dzial_id\", dz.dz_nazwa \"dzial\", to_char(null) \"tworca_id\", to_char(null) \"tworca_nazwisko\",
                                    to_char(null) \"tworca_imie\", to_char(null) \"autor_id\", to_char(null) \"autor_nazwisko\", 
                                    to_char(null) \"autor_imie\", z.za_tytul \"tytul\", z.za_opis_wspoltworcow \"wspoltworcy\", fo.fo_nazwa \"funkcja_osoby\", 
                                    to_char(os.os_osoba_id) \"wspoltworca_id\", os.os_nazwisko \"wspoltworca_nazwisko\", os.os_imie \"wspoltworca_imie\", 
                                    z.za_adnotacje \"adnotacja\", w.wy_nazwa \"wydawnictwo\", w.wy_miasto \"miejscowosc\", z.za_rok_wydania \"rok_wydania\", z.za_opis_fizyczny_ksiazki \"opis_fizyczny\", z.za_uzytk_wpisal, z.za_ro_rok
                            from pbl_zapisy z
                            join IBL_OWNER.pbl_zapisy_wydawnictwa zw on zw.zawy_za_zapis_id=z.za_zapis_id 
							join IBL_OWNER.pbl_wydawnictwa w on zw.zawy_wy_wydawnictwo_id=w.wy_wydawnictwo_id
                            join IBL_OWNER.pbl_dzialy dz on dz.dz_dzial_id=z.za_dz_dzial1_id
                            join IBL_OWNER.pbl_rodzaje_zapisow rz on rz.rz_rodzaj_id=z.za_rz_rodzaj1_id
                            join IBL_OWNER.pbl_udzialy_osob uo on uo.uo_za_zapis_id = z.za_zapis_id
                            join IBL_OWNER.pbl_osoby os on uo.uo_os_osoba_id=os.os_osoba_id
                            join IBL_OWNER.pbl_funkcje_osob fo on fo.fo_symbol=uo.uo_fo_symbol
                            where z.za_uzytk_wpis_data between '2019/05/01' and '2019/06/30'
                            and z.za_uzytk_wpisal like 'ANIA'
                            and z.za_ro_rok<2000")
pbl_books4 <- dbGetQuery(PBL,
                            "select z.za_zapis_id \"rekord_id\", z.za_type \"typ\", rz.rz_rodzaj_id \"rodzaj_zapisu_id\", rz.rz_nazwa \"rodzaj_zapisu\", 
                                    dz.dz_dzial_id \"dzial_id\", dz.dz_nazwa \"dzial\", to_char(null) \"tworca_id\", to_char(null) \"tworca_nazwisko\",
                                    to_char(null) \"tworca_imie\", to_char(null) \"autor_id\", to_char(null) \"autor_nazwisko\", 
                                    to_char(null) \"autor_imie\", z.za_tytul \"tytul\", z.za_opis_wspoltworcow \"wspoltworcy\", to_char(null) \"funkcja_osoby\", 
                                    to_char(null) \"wspoltworca_id\", to_char(null) \"wspoltworca_nazwisko\", to_char(null) \"wspoltworca_imie\", 
                                    z.za_adnotacje \"adnotacja\", w.wy_nazwa \"wydawnictwo\", w.wy_miasto \"miejscowosc\", z.za_rok_wydania \"rok_wydania\", z.za_opis_fizyczny_ksiazki \"opis_fizyczny\", z.za_uzytk_wpisal, z.za_ro_rok                               
                            from pbl_zapisy z
                            join IBL_OWNER.pbl_zapisy_wydawnictwa zw on zw.zawy_za_zapis_id=z.za_zapis_id 
							join IBL_OWNER.pbl_wydawnictwa w on zw.zawy_wy_wydawnictwo_id=w.wy_wydawnictwo_id
                            join IBL_OWNER.pbl_dzialy dz on dz.dz_dzial_id=z.za_dz_dzial1_id
                            join IBL_OWNER.pbl_rodzaje_zapisow rz on rz.rz_rodzaj_id=z.za_rz_rodzaj1_id
                            where z.za_uzytk_wpis_data between '2019/05/01' and '2019/06/30'
                            and z.za_uzytk_wpisal like 'ANIA'
                            and z.za_ro_rok<2000")

pbl_books1 <- sqldf("select *
              from pbl_books1 a
              UNION
              select *
              from pbl_books2 b
              where b.rekord_id not in (select a.rekord_id
              from pbl_books1 a)")
pbl_books1 <- sqldf("select *
                      from pbl_books1 a
                      UNION
                      select * 
                      from pbl_books3 b
                      where b.rekord_id not in (select a.rekord_id
                      from pbl_books1 a)")
pbl_books1 <- sqldf("select *
                      from pbl_books1 a
                      UNION
                      select *
                      from pbl_books4 b
                      where b.rekord_id not in (select a.rekord_id
                      from pbl_books1 a)")
pbl_books <- sqldf("select *
              from pbl_books a
              UNION
              select *
              from pbl_books1 b
              where b.rekord_id not in (select a.rekord_id
              from pbl_books a)")

hasla_przekrojowe <- dbGetQuery(PBL,
                                "select hpz.hz_za_zapis_id,hp.hp_nazwa,khp.kh_nazwa
                                from IBL_OWNER.pbl_hasla_przekrojowe hp
                                join IBL_OWNER.pbl_hasla_przekr_zapisow hpz on hpz.hz_hp_haslo_id=hp.hp_haslo_id
                                join IBL_OWNER.pbl_klucze_hasla_przekr khp on khp.kh_hp_haslo_id=hp.hp_haslo_id
                                join IBL_OWNER.pbl_hasla_zapisow_klucze hzk on hzk.hzkh_hz_hp_haslo_id=hp.hp_haslo_id and hzk.hzkh_kh_klucz_id=khp.kh_klucz_id and hzk.hzkh_hz_za_zapis_id=hpz.hz_za_zapis_id")

hasla_przekrojowe2 <- dbGetQuery(PBL,
                                 "select hpz.hz_za_zapis_id,hp.hp_nazwa,to_char(null) \"KH_NAZWA\"
from IBL_OWNER.pbl_hasla_przekrojowe hp
join IBL_OWNER.pbl_hasla_przekr_zapisow hpz on hpz.hz_hp_haslo_id=hp.hp_haslo_id")

hasla_przekrojowe <- sqldf("select *
              from hasla_przekrojowe a
              UNION
              select *
              from hasla_przekrojowe2 b
              where b.HZ_ZA_ZAPIS_ID||'|'||HP_NAZWA not in (select a.HZ_ZA_ZAPIS_ID||'|'||HP_NAZWA
              from hasla_przekrojowe a)")

indeks_osobowy <- dbGetQuery(PBL,
                             "select odi_za_zapis_id, odi_nazwisko, odi_imie
                              from IBL_OWNER.pbl_osoby_do_indeksu")

pbl_books <- merge(pbl_books,indeks_osobowy,by.x = "rekord_id",by.y = "ODI_ZA_ZAPIS_ID", all.x = TRUE)
pbl_books <- merge(pbl_books,hasla_przekrojowe,by.x = "rekord_id", by.y = "HZ_ZA_ZAPIS_ID", all.x = TRUE)

pbl_serie <- dbGetQuery(PBL,
                        "select z.za_zapis_id,z.za_seria_wydawnicza
                        from pbl_zapisy z
                        where z.za_type like 'KS'")
pbl_books <- merge(pbl_books,pbl_serie,by.x = "rekord_id", by.y = "ZA_ZAPIS_ID", all.x = TRUE)

#write.csv2(pbl_books, "C:/Users/Cezary/Downloads/pbl_books.csv", row.names = F, na = '', fileEncoding = 'Windows-1250')
```

```{r extracting personal data}
#bn_books
trim <- function (x) gsub("^\\s+|\\s+$", "", x)
#field X100
marc_field <- bn_books %>%
  select(id,X100)%>%
  filter(X100!="") %>%
  cSplit(.,"X100",sep = "|",direction = "long") %>%
  filter(X100!="")
subfield_list<- str_extract_all(bn_books$X100,"\\%.")
subfield_list<- unique(unlist(subfield_list))
empty_table<- data.frame(matrix(ncol = length(subfield_list),nrow = lengths(marc_field)[1]))
colnames(empty_table) <-subfield_list
marc_field<-cbind(marc_field,empty_table)
subfield_list_char <- paste("(",subfield_list,")",sep = "")
x <- 1:length(subfield_list)
for (i in x) {
  progress(match(i,x), max.value = length(x)) 
  marc_field$X100 <- str_replace(marc_field$X100,subfield_list_char[i],"|\\1")
}
subfield_list_char2 <- str_replace_all(subfield_list,"\\%","\\\\%")
for (i in x) {
  progress(match(i,x), max.value = length(x))
  string_a <- "(^)(.*?\\|"
  string_b <- subfield_list_char2[i]
  string_c <- ")(.*?)(\\,{0,1})((\\|\\%)(.*)|$)"
  string <- paste(string_a,string_b,string_c,sep = "")
  marc_field[,i+2] <- ifelse(grepl(subfield_list_char2[i],marc_field$X100),str_replace_all(gsub(string,"\\3",marc_field$X100),"\\%.", "~"),NA)
}

marc_field$`%1` <- trim(marc_field$`%1`)
marc_field$`%2` <- trim(marc_field$`%2`)
marc_field$`%d` <- trim(marc_field$`%d`)
marc_field$`%4` <- trim(marc_field$`%4`)
marc_field$`%3` <- trim(marc_field$`%3`)
marc_field$`%s` <- trim(marc_field$`%s`)
marc_field$`%w` <- trim(marc_field$`%w`)
marc_field$`%r` <- trim(marc_field$`%r`)
marc_field$`%m` <- trim(marc_field$`%m`)
marc_field$`%p` <- trim(marc_field$`%p`)
marc_field$`%k` <- trim(marc_field$`%k`)

bn_record_people_X100 <- marc_field %>%
  select(record_id = id, `%1`, `%2`, `%d`, `%4`, `%3`, `%s`,`%w`,`%p`,`%k`) %>%
  mutate(`%1` = paste(`%1`,`%3`,sep = " ")) %>%
  mutate(`%2` = paste(`%2`,`%4`,sep = " ")) %>%
  select(-`%3`,-`%4`) %>%
  mutate(data_set = "bn_books", field = "X100") %>%
  select(data_set, field, 1:8)
bn_record_people_X100[] <- lapply(bn_record_people_X100, gsub, pattern=' NA', replacement='')
bn_record_people_X100[] <- lapply(bn_record_people_X100, gsub, pattern='NANA', replacement='')
bn_record_people_X100[] <- lapply(bn_record_people_X100, gsub, pattern='NA$', replacement='')
bn_record_people_X100$name <- paste(bn_record_people_X100$`%1`,bn_record_people_X100$`%2`,bn_record_people_X100$`%d`,sep = "|")
bn_record_people_X100[] <- lapply(bn_record_people_X100, gsub, pattern='\\|NA', replacement='')
#field X700
marc_field <- bn_books %>%
  select(id,X700)%>%
  filter(X700!="") %>%
  cSplit(.,"X700",sep = "|",direction = "long") %>%
  filter(X700!="")
subfield_list<- str_extract_all(bn_books$X700,"\\%.")
subfield_list<- unique(unlist(subfield_list))
empty_table<- data.frame(matrix(ncol = length(subfield_list),nrow = lengths(marc_field)[1]))
colnames(empty_table) <-subfield_list
marc_field<-cbind(marc_field,empty_table)
subfield_list_char <- paste("(",subfield_list,")",sep = "")
x <- 1:length(subfield_list)
for (i in x) {
  progress(match(i,x), max.value = length(x)) 
  marc_field$X700 <- str_replace(marc_field$X700,subfield_list_char[i],"|\\1")
}
subfield_list_char2 <- str_replace_all(subfield_list,"\\%","\\\\%")
for (i in x) {
  progress(match(i,x), max.value = length(x))
  string_a <- "(^)(.*?\\|"
  string_b <- subfield_list_char2[i]
  string_c <- ")(.*?)(\\,{0,1})((\\|\\%)(.*)|$)"
  string <- paste(string_a,string_b,string_c,sep = "")
  marc_field[,i+2] <- ifelse(grepl(subfield_list_char2[i],marc_field$X700),str_replace_all(gsub(string,"\\3",marc_field$X700),"\\%.", "~"),NA)
}

marc_field$`%1` <- trim(marc_field$`%1`)
marc_field$`%2` <- trim(marc_field$`%2`)
marc_field$`%d` <- trim(marc_field$`%d`)
marc_field$`%4` <- trim(marc_field$`%4`)
marc_field$`%3` <- trim(marc_field$`%3`)
marc_field$`%s` <- trim(marc_field$`%s`)
marc_field$`%w` <- trim(marc_field$`%w`)
marc_field$`%r` <- trim(marc_field$`%r`)
marc_field$`%m` <- trim(marc_field$`%m`)
marc_field$`%p` <- trim(marc_field$`%p`)
marc_field$`%k` <- trim(marc_field$`%k`)

bn_record_people_X700 <- marc_field %>%
  select(record_id = id, `%1`, `%2`, `%d`, `%4`, `%3`, `%s`,`%w`,`%p`,`%k`) %>%
  mutate(`%1` = paste(`%1`,`%3`,sep = " ")) %>%
  mutate(`%2` = paste(`%2`,`%4`,sep = " ")) %>%
  select(-`%3`,-`%4`) %>%
  mutate(data_set = "bn_books", field = "X700") %>%
  select(data_set, field, 1:8)
bn_record_people_X700[] <- lapply(bn_record_people_X700, gsub, pattern=' NA', replacement='')
bn_record_people_X700[] <- lapply(bn_record_people_X700, gsub, pattern='NANA', replacement='')
bn_record_people_X700[] <- lapply(bn_record_people_X700, gsub, pattern='NA$', replacement='')
bn_record_people_X700$name <- paste(bn_record_people_X700$`%1`,bn_record_people_X700$`%2`,bn_record_people_X700$`%d`,sep = "|")
bn_record_people_X700[] <- lapply(bn_record_people_X700, gsub, pattern='\\|NA', replacement='')
#field X701
marc_field <- bn_books %>%
  select(id,X701)%>%
  filter(X701!="") %>%
  cSplit(.,"X701",sep = "|",direction = "long") %>%
  filter(X701!="")
subfield_list<- str_extract_all(bn_books$X701,"\\%.")
subfield_list<- unique(unlist(subfield_list))
empty_table<- data.frame(matrix(ncol = length(subfield_list),nrow = lengths(marc_field)[1]))
colnames(empty_table) <-subfield_list
marc_field<-cbind(marc_field,empty_table)
subfield_list_char <- paste("(",subfield_list,")",sep = "")
x <- 1:length(subfield_list)
for (i in x) {
  progress(match(i,x), max.value = length(x)) 
  marc_field$X701 <- str_replace(marc_field$X701,subfield_list_char[i],"|\\1")
}
subfield_list_char2 <- str_replace_all(subfield_list,"\\%","\\\\%")
for (i in x) {
  progress(match(i,x), max.value = length(x))
  string_a <- "(^)(.*?\\|"
  string_b <- subfield_list_char2[i]
  string_c <- ")(.*?)(\\,{0,1})((\\|\\%)(.*)|$)"
  string <- paste(string_a,string_b,string_c,sep = "")
  marc_field[,i+2] <- ifelse(grepl(subfield_list_char2[i],marc_field$X701),str_replace_all(gsub(string,"\\3",marc_field$X701),"\\%.", "~"),NA)
}

marc_field$`%1` <- trim(marc_field$`%1`)
marc_field$`%2` <- trim(marc_field$`%2`)
marc_field$`%d` <- trim(marc_field$`%d`)
marc_field$`%3` <- trim(marc_field$`%3`)
marc_field$`%s` <- trim(marc_field$`%s`)
marc_field$`%r` <- trim(marc_field$`%r`)
marc_field$`%p` <- trim(marc_field$`%p`)


bn_record_people_X701 <- marc_field %>%
  select(record_id = id, `%1`, `%2`, `%d`, `%3`, `%s`, `%p`) %>%
  mutate(`%4` = NA, `%w` = NA, `%k` = NA) %>%
  mutate(`%1` = paste(`%1`,`%3`,sep = " ")) %>%
  mutate(`%2` = paste(`%2`,`%4`,sep = " ")) %>%
  select(-`%3`,-`%4`) %>%
  mutate(data_set = "bn_books", field = "X701") %>%
  select(colnames(bn_record_people_X100)[1:10])
bn_record_people_X701[] <- lapply(bn_record_people_X701, gsub, pattern=' NA', replacement='')
bn_record_people_X701[] <- lapply(bn_record_people_X701, gsub, pattern='NANA', replacement='')
bn_record_people_X701[] <- lapply(bn_record_people_X701, gsub, pattern='NA$', replacement='')
bn_record_people_X701$name <- paste(bn_record_people_X701$`%1`,bn_record_people_X701$`%2`,bn_record_people_X701$`%d`,sep = "|")
bn_record_people_X701[] <- lapply(bn_record_people_X701, gsub, pattern='\\|NA', replacement='')

#concatenate bn

bn_record_people <- rbind(bn_record_people_X100,bn_record_people_X700,bn_record_people_X701) 
bn_record_people <- bn_record_people %>%
  mutate(id_osoby = paste("bnb",seq.int(nrow(bn_record_people)),sep = ""))

names_of_columns <- colnames(bn_record_people)

set1 <- bn_record_people %>%
  select(1:6,11:12) %>%
  mutate(`%1` = paste(`%1`,`%2`,`%d`, sep = " ")) %>% 
  select(data_set,field,record_id,`%1`,name,id_osoby)
set1 <- set1 %>%
  mutate(subfield = colnames(set1)[4])
colnames(set1)[4] <- "name_form"
set1[] <- lapply(set1, gsub, pattern=' NA', replacement='')
set1$name_form <- trim(set1$name_form)

set2 <- bn_record_people[c(1:3,7,11:12)] %>%
  filter(!is.na(`%s`))
set2 <- set2 %>%
  mutate(subfield = colnames(set2)[4])
colnames(set2)[4] <- "name_form"
set3 <- bn_record_people[c(1:3,8,11:12)] %>%
  filter(!is.na(`%w`))
set3 <- set3 %>%
  mutate(subfield = colnames(set3)[4])
colnames(set3)[4] <- "name_form"
set4 <- bn_record_people[c(1:3,9,11:12)] %>%
  filter(!is.na(`%p`))
set4 <- set4 %>%
  mutate(subfield = colnames(set4)[4])
colnames(set4)[4] <- "name_form"
set5 <- bn_record_people[c(1:3,10,11:12)] %>%
  filter(!is.na(`%k`))
set5 <- set5 %>%
  mutate(subfield = colnames(set5)[4])
colnames(set5)[4] <- "name_form"

bn_record_people <- rbind(set1,set2,set3,set4,set5)
bn_record_people <- bn_record_people %>%
  select(data_set,record_id,field,subfield,id_osoby,name_form,id_osoby) %>%
  mutate(name_form_id = paste(data_set,record_id,id_osoby,field,subfield,sep = "-")) %>%
  mutate(name_simple = str_replace_all(str_to_lower(name_form), "\\W", ""))

#cz_books
#field X100
marc_field <- cz_books %>%
  select(id,X100)%>%
  filter(X100!="") %>%
  cSplit(.,"X100",sep = "|",direction = "long") %>%
  filter(X100!="")
marc_field <- mutate(marc_field,
               indicator = str_replace_all(marc_field$X100,"(^.*?)(\\$.*)","\\1"))
subfield_list<- str_extract_all(cz_books$X100,"\\${2}.")
subfield_list<- unique(unlist(subfield_list))
empty_table<- data.frame(matrix(ncol = length(subfield_list),nrow = lengths(marc_field)[1]))
colnames(empty_table) <-subfield_list
marc_field<-cbind(marc_field,empty_table)
subfield_list_char <- paste("(",subfield_list,")",sep = "")
subfield_list_char <- str_replace_all(subfield_list_char,"\\$","\\\\$")
x <- 1:length(subfield_list)
for (i in x) {
  marc_field$X100 <- str_replace(marc_field$X100,subfield_list_char[i],"|\\1")
  progress(match(i,x), max.value = length(x)) 
}
for (i in x) {
  progress(match(i,x), max.value = length(x))
  subfield_list_char2 <- str_replace_all(subfield_list,"\\$","\\\\$")
  string_a <- "(^)(.*?\\|"
  string_b <- subfield_list_char2[i]
  string_c <- ")(.*?)(\\,{0,1})((\\|\\${2})(.*)|$)"
  string <- paste(string_a,string_b,string_c,sep = "")
  marc_field[,i+3] <- ifelse(grepl(subfield_list_char2[i],marc_field$X100),str_replace_all(gsub(string,"\\3",marc_field$X100),"\\${2}.", "~"),NA)
}

marc_field$`$$a` <- trim(marc_field$`$$a`)
marc_field$`$$d` <- trim(marc_field$`$$d`)
marc_field$`$$b` <- str_remove(trim(marc_field$`$$b`),"\\.$")

cz_record_people_X100 <- marc_field %>%
  select(record_id = id, `$$a`, `$$b`, `$$d`) %>%
  mutate(`$$a` = paste(`$$a`,`$$b`,sep = " ")) %>%
  mutate(name = paste(`$$a`,`$$d`,sep = "|")) %>%
  select(-3) %>%
  mutate(data_set = "cz_books", field = "X100") %>%
  select(data_set, field,1:4)
cz_record_people_X100[] <- lapply(cz_record_people_X100, gsub, pattern=' NA', replacement='')
cz_record_people_X100[] <- lapply(cz_record_people_X100, gsub, pattern='\\|NA', replacement='')

#field X600
marc_field <- cz_books %>%
  select(id,X600)%>%
  filter(X600!="") %>%
  cSplit(.,"X600",sep = "|",direction = "long") %>%
  filter(X600!="")
marc_field <- mutate(marc_field,
               indicator = str_replace_all(marc_field$X600,"(^.*?)(\\$.*)","\\1"))
subfield_list<- str_extract_all(cz_books$X600,"\\${2}.")
subfield_list<- unique(unlist(subfield_list))
empty_table<- data.frame(matrix(ncol = length(subfield_list),nrow = lengths(marc_field)[1]))
colnames(empty_table) <-subfield_list
marc_field<-cbind(marc_field,empty_table)
subfield_list_char <- paste("(",subfield_list,")",sep = "")
subfield_list_char <- str_replace_all(subfield_list_char,"\\$","\\\\$")
x <- 1:length(subfield_list)
for (i in x) {
  marc_field$X600 <- str_replace(marc_field$X600,subfield_list_char[i],"|\\1")
  progress(match(i,x), max.value = length(x)) 
}
for (i in x) {
  progress(match(i,x), max.value = length(x))
  subfield_list_char2 <- str_replace_all(subfield_list,"\\$","\\\\$")
  string_a <- "(^)(.*?\\|"
  string_b <- subfield_list_char2[i]
  string_c <- ")(.*?)(\\,{0,1})((\\|\\${2})(.*)|$)"
  string <- paste(string_a,string_b,string_c,sep = "")
  marc_field[,i+3] <- ifelse(grepl(subfield_list_char2[i],marc_field$X600),str_replace_all(gsub(string,"\\3",marc_field$X600),"\\${2}.", "~"),NA)
}

marc_field$`$$a` <- trim(marc_field$`$$a`)
marc_field$`$$d` <- trim(marc_field$`$$d`)
marc_field$`$$b` <- str_remove(trim(marc_field$`$$b`),"\\.$")

cz_record_people_X600 <- marc_field %>%
  select(record_id = id, `$$a`, `$$b`, `$$d`) %>%
  mutate(`$$a` = paste(`$$a`,`$$b`,sep = " ")) %>%
  mutate(name = paste(`$$a`,`$$d`,sep = "|")) %>%
  select(-3) %>%
  mutate(data_set = "cz_books", field = "X600") %>%
  select(data_set, field,1:4)
cz_record_people_X600[] <- lapply(cz_record_people_X600, gsub, pattern=' NA', replacement='')
cz_record_people_X600[] <- lapply(cz_record_people_X600, gsub, pattern='\\|NA', replacement='')

#field X700
marc_field <- cz_books %>%
  select(id,X700)%>%
  filter(X700!="") %>%
  cSplit(.,"X700",sep = "|",direction = "long") %>%
  filter(X700!="")
marc_field <- mutate(marc_field,
               indicator = str_replace_all(marc_field$X700,"(^.*?)(\\$.*)","\\1"))
subfield_list<- str_extract_all(cz_books$X700,"\\${2}.")
subfield_list<- unique(unlist(subfield_list))
empty_table<- data.frame(matrix(ncol = length(subfield_list),nrow = lengths(marc_field)[1]))
colnames(empty_table) <-subfield_list
marc_field<-cbind(marc_field,empty_table)
subfield_list_char <- paste("(",subfield_list,")",sep = "")
subfield_list_char <- str_replace_all(subfield_list_char,"\\$","\\\\$")
x <- 1:length(subfield_list)
for (i in x) {
  marc_field$X700 <- str_replace(marc_field$X700,subfield_list_char[i],"|\\1")
  progress(match(i,x), max.value = length(x)) 
}
for (i in x) {
  progress(match(i,x), max.value = length(x))
  subfield_list_char2 <- str_replace_all(subfield_list,"\\$","\\\\$")
  string_a <- "(^)(.*?\\|"
  string_b <- subfield_list_char2[i]
  string_c <- ")(.*?)(\\,{0,1})((\\|\\${2})(.*)|$)"
  string <- paste(string_a,string_b,string_c,sep = "")
  marc_field[,i+3] <- ifelse(grepl(subfield_list_char2[i],marc_field$X700),str_replace_all(gsub(string,"\\3",marc_field$X700),"\\${2}.", "~"),NA)
}

marc_field$`$$a` <- trim(marc_field$`$$a`)
marc_field$`$$d` <- trim(marc_field$`$$d`)
marc_field$`$$b` <- str_remove(trim(marc_field$`$$b`),"\\.$")

cz_record_people_X700 <- marc_field %>%
  select(record_id = id, `$$a`, `$$b`, `$$d`) %>%
  mutate(`$$a` = paste(`$$a`,`$$b`,sep = " ")) %>%
  mutate(name = paste(`$$a`,`$$d`,sep = "|")) %>%
  select(-3) %>%
  mutate(data_set = "cz_books", field = "X700") %>%
  select(data_set, field,1:4)
cz_record_people_X700[] <- lapply(cz_record_people_X700, gsub, pattern=' NA', replacement='')
cz_record_people_X700[] <- lapply(cz_record_people_X700, gsub, pattern='\\|NA', replacement='')

#concatenate all cz books
cz_record_people <- rbind(cz_record_people_X100,cz_record_people_X600,cz_record_people_X700)
cz_record_people <- cz_record_people %>%
  mutate(id_osoby = paste("czb",seq.int(nrow(cz_record_people)),sep = ""))
names_of_columns <- colnames(cz_record_people)


cz_record_people <- cz_record_people %>%
  select(names_of_columns,id_osoby) %>%
  arrange(field,as.integer(record_id))
cz_record_people <- cz_record_people %>%
  mutate(name_form = paste(`$$a`, `$$d`, sep = " ")) %>% 
  select(data_set,field,record_id,name_form,name,id_osoby)
cz_record_people <- cz_record_people %>%
  mutate(subfield = "$$a")
cz_record_people[] <- lapply(cz_record_people, gsub, pattern=' NA', replacement='')
cz_record_people$name_form <- trim(cz_record_people$name_form)
cz_record_people <- cz_record_people %>%
  select(data_set,record_id,field,subfield,id_osoby,name_form) %>%
  mutate(name_form_id = paste(data_set,record_id,id_osoby,field,subfield,sep = "-")) %>%
  mutate(name_simple = str_replace_all(str_to_lower(name_form), "\\W", ""))

#cz_articles
#field X100
marc_field <- cz_articles %>%
  select(id,X100)%>%
  filter(X100!="") %>%
  cSplit(.,"X100",sep = "|",direction = "long") %>%
  filter(X100!="")
marc_field <- mutate(marc_field,
               indicator = str_replace_all(marc_field$X100,"(^.*?)(\\$.*)","\\1"))
subfield_list<- str_extract_all(cz_articles$X100,"\\${2}.")
subfield_list<- unique(unlist(subfield_list))
empty_table<- data.frame(matrix(ncol = length(subfield_list),nrow = lengths(marc_field)[1]))
colnames(empty_table) <-subfield_list
marc_field<-cbind(marc_field,empty_table)
subfield_list_char <- paste("(",subfield_list,")",sep = "")
subfield_list_char <- str_replace_all(subfield_list_char,"\\$","\\\\$")
x <- 1:length(subfield_list)
for (i in x) {
  marc_field$X100 <- str_replace(marc_field$X100,subfield_list_char[i],"|\\1")
  progress(match(i,x), max.value = length(x)) 
}
for (i in x) {
  progress(match(i,x), max.value = length(x))
  subfield_list_char2 <- str_replace_all(subfield_list,"\\$","\\\\$")
  string_a <- "(^)(.*?\\|"
  string_b <- subfield_list_char2[i]
  string_c <- ")(.*?)(\\,{0,1})((\\|\\${2})(.*)|$)"
  string <- paste(string_a,string_b,string_c,sep = "")
  marc_field[,i+3] <- ifelse(grepl(subfield_list_char2[i],marc_field$X100),str_replace_all(gsub(string,"\\3",marc_field$X100),"\\${2}.", "~"),NA)
}

marc_field$`$$a` <- trim(marc_field$`$$a`)
marc_field$`$$d` <- trim(marc_field$`$$d`)
marc_field$`$$b` <- str_remove(trim(marc_field$`$$b`),"\\.$")

cz_record_people_art_X100 <- marc_field %>%
  select(record_id = id, `$$a`, `$$b`, `$$d`) %>%
  mutate(`$$a` = paste(`$$a`,`$$b`,sep = " ")) %>%
  mutate(name = paste(`$$a`,`$$d`,sep = "|")) %>%
  select(-3) %>%
  mutate(data_set = "cz_articles", field = "X100") %>%
  select(data_set, field,1:4)
cz_record_people_art_X100[] <- lapply(cz_record_people_art_X100, gsub, pattern=' NA', replacement='')
cz_record_people_art_X100[] <- lapply(cz_record_people_art_X100, gsub, pattern='\\|NA', replacement='')

#field X600
marc_field <- cz_articles %>%
  select(id,X600)%>%
  filter(X600!="") %>%
  cSplit(.,"X600",sep = "|",direction = "long") %>%
  filter(X600!="")
marc_field <- mutate(marc_field,
               indicator = str_replace_all(marc_field$X600,"(^.*?)(\\$.*)","\\1"))
subfield_list<- str_extract_all(cz_articles$X600,"\\${2}.")
subfield_list<- unique(unlist(subfield_list))
empty_table<- data.frame(matrix(ncol = length(subfield_list),nrow = lengths(marc_field)[1]))
colnames(empty_table) <-subfield_list
marc_field<-cbind(marc_field,empty_table)
subfield_list_char <- paste("(",subfield_list,")",sep = "")
subfield_list_char <- str_replace_all(subfield_list_char,"\\$","\\\\$")
x <- 1:length(subfield_list)
for (i in x) {
  marc_field$X600 <- str_replace(marc_field$X600,subfield_list_char[i],"|\\1")
  progress(match(i,x), max.value = length(x)) 
}
for (i in x) {
  progress(match(i,x), max.value = length(x))
  subfield_list_char2 <- str_replace_all(subfield_list,"\\$","\\\\$")
  string_a <- "(^)(.*?\\|"
  string_b <- subfield_list_char2[i]
  string_c <- ")(.*?)(\\,{0,1})((\\|\\${2})(.*)|$)"
  string <- paste(string_a,string_b,string_c,sep = "")
  marc_field[,i+3] <- ifelse(grepl(subfield_list_char2[i],marc_field$X600),str_replace_all(gsub(string,"\\3",marc_field$X600),"\\${2}.", "~"),NA)
}

marc_field$`$$a` <- trim(marc_field$`$$a`)
marc_field$`$$d` <- trim(marc_field$`$$d`)
marc_field$`$$b` <- str_remove(trim(marc_field$`$$b`),"\\.$")

cz_record_people_art_X600 <- marc_field %>%
  select(record_id = id, `$$a`, `$$b`, `$$d`) %>%
  mutate(`$$a` = paste(`$$a`,`$$b`,sep = " ")) %>%
  mutate(name = paste(`$$a`,`$$d`,sep = "|")) %>%
  select(-3) %>%
  mutate(data_set = "cz_articles", field = "X600") %>%
  select(data_set, field,1:4)
cz_record_people_art_X600[] <- lapply(cz_record_people_art_X600, gsub, pattern=' NA', replacement='')
cz_record_people_art_X600[] <- lapply(cz_record_people_art_X600, gsub, pattern='\\|NA', replacement='')

#field X700
marc_field <- cz_articles %>%
  select(id,X700)%>%
  filter(X700!="") %>%
  cSplit(.,"X700",sep = "|",direction = "long") %>%
  filter(X700!="")
marc_field <- mutate(marc_field,
               indicator = str_replace_all(marc_field$X700,"(^.*?)(\\$.*)","\\1"))
subfield_list<- str_extract_all(cz_articles$X700,"\\${2}.")
subfield_list<- unique(unlist(subfield_list))
empty_table<- data.frame(matrix(ncol = length(subfield_list),nrow = lengths(marc_field)[1]))
colnames(empty_table) <-subfield_list
marc_field<-cbind(marc_field,empty_table)
subfield_list_char <- paste("(",subfield_list,")",sep = "")
subfield_list_char <- str_replace_all(subfield_list_char,"\\$","\\\\$")
x <- 1:length(subfield_list)
for (i in x) {
  marc_field$X700 <- str_replace(marc_field$X700,subfield_list_char[i],"|\\1")
  progress(match(i,x), max.value = length(x)) 
}
for (i in x) {
  progress(match(i,x), max.value = length(x))
  subfield_list_char2 <- str_replace_all(subfield_list,"\\$","\\\\$")
  string_a <- "(^)(.*?\\|"
  string_b <- subfield_list_char2[i]
  string_c <- ")(.*?)(\\,{0,1})((\\|\\${2})(.*)|$)"
  string <- paste(string_a,string_b,string_c,sep = "")
  marc_field[,i+3] <- ifelse(grepl(subfield_list_char2[i],marc_field$X700),str_replace_all(gsub(string,"\\3",marc_field$X700),"\\${2}.", "~"),NA)
}

marc_field$`$$a` <- trim(marc_field$`$$a`)
marc_field$`$$d` <- trim(marc_field$`$$d`)

cz_record_people_art_X700 <- marc_field %>%
  select(record_id = id, `$$a`,`$$d`) %>%
  mutate(name = paste(`$$a`,`$$d`,sep = "|")) %>%
  mutate(data_set = "cz_articles", field = "X700") %>%
  select(data_set, field,1:4)
cz_record_people_art_X700[] <- lapply(cz_record_people_art_X700, gsub, pattern=' NA', replacement='')
cz_record_people_art_X700[] <- lapply(cz_record_people_art_X700, gsub, pattern='\\|NA', replacement='')

#concatenate all cz art
cz_record_people_art <- rbind(cz_record_people_art_X100,cz_record_people_art_X600,cz_record_people_art_X700)
cz_record_people_art <- cz_record_people_art %>%
  mutate(id_osoby = paste("cza",seq.int(nrow(cz_record_people_art)),sep = ""))
names_of_columns <- colnames(cz_record_people_art)

cz_record_people_art <- cz_record_people_art %>%
  select(names_of_columns,id_osoby) %>%
  arrange(field,as.integer(record_id))
cz_record_people_art <- cz_record_people_art %>%
  mutate(name_form = paste(`$$a`, `$$d`, sep = " ")) %>% 
  select(data_set,field,record_id,name_form,name,id_osoby)
cz_record_people_art <- cz_record_people_art %>%
  mutate(subfield = "$$a")
cz_record_people_art[] <- lapply(cz_record_people_art, gsub, pattern=' NA', replacement='')
cz_record_people_art$name_form <- trim(cz_record_people_art$name_form)
cz_record_people_art <- cz_record_people_art %>%
  select(data_set,record_id,field,subfield,id_osoby,name_form) %>%
  mutate(name_form_id = paste(data_set,record_id,id_osoby,field,subfield,sep = "-")) %>%
  mutate(name_simple = str_replace_all(str_to_lower(name_form), "\\W", ""))

#pbl books

pbl_record_people_books_creators <- pbl_books %>%
  select(rekord_id,tworca_id,tworca_nazwisko,tworca_imie) %>%
  filter(!is.na(tworca_id))

pbl_record_people_books_creators <- pbl_record_people_books_creators %>%
  mutate(data_set = "pbl_books") %>%
  mutate(field = "tworcy") %>%
  mutate(name = paste(tworca_nazwisko,tworca_imie,sep = "|")) %>%
  mutate(name_form = paste(tworca_nazwisko,tworca_imie,sep = ", ")) %>%
  mutate(subfield = NA) %>%
  mutate(id_osoby = paste("pblt",tworca_id, sep = "")) %>%
  mutate(name_form_id = paste(data_set,rekord_id,id_osoby,field,subfield,sep = "-")) %>%
  mutate(name_simple = str_replace_all(str_to_lower(name_form), "\\W", "")) %>%
  select(data_set, record_id = rekord_id, field, subfield, id_osoby, name_form, name_form_id, name_simple)

pbl_record_people_books_authors <- pbl_books %>%
  select(rekord_id,autor_id,autor_nazwisko,autor_imie) %>%
  filter(!is.na(autor_id))

pbl_record_people_books_authors <- pbl_record_people_books_authors %>%
  mutate(data_set = "pbl_books") %>%
  mutate(field = "tworcy") %>%
  mutate(name = paste(autor_nazwisko,autor_imie,sep = "|")) %>%
  mutate(name_form = paste(autor_nazwisko,autor_imie,sep = ", ")) %>%
  mutate(subfield = NA) %>%
  mutate(id_osoby = paste("pbla",autor_id, sep = "")) %>%
  mutate(name_form_id = paste(data_set,rekord_id,id_osoby,field,subfield,sep = "-")) %>%
  mutate(name_simple = str_replace_all(str_to_lower(name_form), "\\W", "")) %>%
  select(data_set, record_id = rekord_id, field, subfield, id_osoby, name_form, name_form_id, name_simple)

pbl_record_people_books_coworkers <- pbl_books %>%
  select(rekord_id,wspoltworca_id,wspoltworca_nazwisko,wspoltworca_imie) %>%
  filter(!is.na(wspoltworca_id))

pbl_record_people_books_coworkers <- pbl_record_people_books_coworkers %>%
  mutate(data_set = "pbl_books") %>%
  mutate(field = "tworcy") %>%
  mutate(name = paste(wspoltworca_nazwisko,wspoltworca_imie,sep = "|")) %>%
  mutate(name_form = paste(wspoltworca_nazwisko,wspoltworca_imie,sep = ", ")) %>%
  mutate(subfield = NA) %>%
  mutate(id_osoby = paste("pblw",wspoltworca_id, sep = "")) %>%
  mutate(name_form_id = paste(data_set,rekord_id,id_osoby,field,subfield,sep = "-")) %>%
  mutate(name_simple = str_replace_all(str_to_lower(name_form), "\\W", "")) %>%
  select(data_set, record_id = rekord_id, field, subfield, id_osoby, name_form, name_form_id, name_simple)

pbl_record_people_books <- rbind(pbl_record_people_books_creators,pbl_record_people_books_authors,pbl_record_people_books_coworkers)


#pbl_articles

pbl_record_people_art_creators <- pbl_articles %>%
  select(rekord_id,tworca_id,tworca_nazwisko,tworca_imie) %>%
  filter(!is.na(tworca_id))

pbl_record_people_art_creators <- pbl_record_people_art_creators %>%
  mutate(data_set = "pbl_articles") %>%
  mutate(field = "tworcy") %>%
  mutate(name = paste(tworca_nazwisko,tworca_imie,sep = "|")) %>%
  mutate(name_form = paste(tworca_nazwisko,tworca_imie,sep = ", ")) %>%
  mutate(subfield = NA) %>%
  mutate(id_osoby = paste("pblt",tworca_id, sep = "")) %>%
  mutate(name_form_id = paste(data_set,rekord_id,id_osoby,field,subfield,sep = "-")) %>%
  mutate(name_simple = str_replace_all(str_to_lower(name_form), "\\W", "")) %>%
  select(data_set, record_id = rekord_id, field, subfield, id_osoby, name_form, name_form_id, name_simple)

pbl_record_people_art_authors <- pbl_articles %>%
  select(rekord_id,autor_id,autor_nazwisko,autor_imie) %>%
  filter(!is.na(autor_id))

pbl_record_people_art_authors <- pbl_record_people_art_authors %>%
  mutate(data_set = "pbl_articles") %>%
  mutate(field = "tworcy") %>%
  mutate(name = paste(autor_nazwisko,autor_imie,sep = "|")) %>%
  mutate(name_form = paste(autor_nazwisko,autor_imie,sep = ", ")) %>%
  mutate(subfield = NA) %>%
  mutate(id_osoby = paste("pbla",autor_id, sep = "")) %>%
  mutate(name_form_id = paste(data_set,rekord_id,id_osoby,field,subfield,sep = "-")) %>%
  mutate(name_simple = str_replace_all(str_to_lower(name_form), "\\W", "")) %>%
  select(data_set, record_id = rekord_id, field, subfield, id_osoby, name_form, name_form_id, name_simple)

pbl_record_people_art_coworkers <- pbl_articles %>%
  select(rekord_id,wspoltworca_id,wspoltworca_nazwisko,wspoltworca_imie) %>%
  filter(!is.na(wspoltworca_id))

pbl_record_people_art_coworkers <- pbl_record_people_art_coworkers %>%
  mutate(data_set = "pbl_articles") %>%
  mutate(field = "tworcy") %>%
  mutate(name = paste(wspoltworca_nazwisko,wspoltworca_imie,sep = "|")) %>%
  mutate(name_form = paste(wspoltworca_nazwisko,wspoltworca_imie,sep = ", ")) %>%
  mutate(subfield = NA) %>%
  mutate(id_osoby = paste("pblw",wspoltworca_id, sep = "")) %>%
  mutate(name_form_id = paste(data_set,rekord_id,id_osoby,field,subfield,sep = "-")) %>%
  mutate(name_simple = str_replace_all(str_to_lower(name_form), "\\W", "")) %>%
  select(data_set, record_id = rekord_id, field, subfield, id_osoby, name_form, name_form_id, name_simple)

pbl_record_people_art <- rbind(pbl_record_people_art_creators,pbl_record_people_art_authors,pbl_record_people_art_coworkers)

```

```{r merge personal data}
#putting all together
record_people <- rbind(bn_record_people,cz_record_people,cz_record_people_art,pbl_record_people_books,pbl_record_people_art)

#test <- record_people %>%
#  filter(grepl("Amsterdamski|erski",name_form))

#id tymczas, nazwa, id nazwy, id osoby
tab_2 <- record_people %>%
  select(name_form,name_form_id,name_simple,id_osoby) %>%
  group_by(name_simple) %>%
  mutate(name_form_id = paste(unique(name_form_id),collapse = "|")) %>%
  mutate(name_form = paste(unique(name_form), collapse = "|")) %>%
  mutate(id_osoby = paste(unique(id_osoby), collapse = "|")) %>%
  ungroup() %>%
  unique()
tab_2$temp_id <- seq.int(nrow(tab_2))
tab_2 <- tab_2 %>%
  select(temp_id,name_form, name_simple, name_form_id, id_osoby)
# czenie po id osoby

tab_3 <- tab_2 %>%
  mutate(name_simple_short = str_extract(name_simple,"(^[a-zaeiiouycdgklnrsstz]+)")) %>%
  group_by(name_simple_short) %>%
  mutate(temp_id = paste(unique(temp_id),collapse = "|")) %>%
  mutate(name_form_id = paste(unique(name_form_id),collapse = "|")) %>%
  mutate(name_form = paste(unique(name_form), collapse = "|")) %>%
  mutate(id_osoby = paste(unique(id_osoby), collapse = "|")) %>%
  mutate(name_simple = paste(unique(name_simple), collapse = "|")) %>%
  ungroup() %>%
  unique() %>%
  select(-name_simple_short)

id_osoby <- tab_3 %>%
  select(id_osoby,temp_id2 = temp_id)

id_osoby <- cSplit(id_osoby,"id_osoby",sep = "|",direction = "long") %>%
  group_by(id_osoby) %>%
  mutate(temp_id2 = paste(temp_id2,collapse = "|")) %>%
  ungroup() %>%
  unique() %>%
  mutate(id_osoby = paste(id_osoby,"|",sep = ""))
tab_3$id_osoby <- paste(tab_3$id_osoby,"|",sep = "")

tab_4 <- sqldf::sqldf("select *
                     from tab_3 a
                     join id_osoby b on a.id_osoby like ('%'||b.id_osoby||'%')") %>%
  select(-temp_id,-id_osoby..6) %>%
  unique() %>%
  mutate(temp_id2 = str_extract(temp_id2,"(^\\d+)(?=\\||$)")) %>%
  group_by(temp_id2) %>%
  mutate(name_form = paste(unique(name_form),collapse = "|")) %>%
  mutate(name_simple = paste(unique(name_simple),collapse = "|")) %>%
  mutate(name_form_id = paste(unique(name_form_id),collapse = "|")) %>%
  mutate(id_osoby = paste(unique(id_osoby),collapse = "")) %>%
  ungroup() %>%
  unique()

x <- 1:length(tab_4$temp_id2)
for (i in x) {
  progress(match(i,x), max.value = length(x)) 
  tab_4$id_osoby[i] <- paste(paste(unique(unlist(strsplit(tab_4$id_osoby[i],"\\|"))),collapse = "|"),"|",sep = "")
}

tab_4 <- tab_4 %>%
  select(id = temp_id2,name_form,name_simple,name_form_id,id_osoby)

write.csv2(tab_4, "C:/Users/Cezary/Desktop/samizdat_kartoteka_osb.csv", row.names = F, na = '', fileEncoding = 'UTF-8')
```

```{r preparing file for institutions}
#bn_books
trim <- function (x) gsub("^\\s+|\\s+$", "", x)
#field X110
marc_field <- bn_books %>%
  select(id,X110)%>%
  filter(X110!="") %>%
  cSplit(.,"X110",sep = "|",direction = "long") %>%
  filter(X110!="")
subfield_list<- str_extract_all(bn_books$X110,"\\%.")
subfield_list<- unique(unlist(subfield_list))
empty_table<- data.frame(matrix(ncol = length(subfield_list),nrow = lengths(marc_field)[1]))
colnames(empty_table) <-subfield_list
marc_field<-cbind(marc_field,empty_table)
subfield_list_char <- paste("(",subfield_list,")",sep = "")
x <- 1:length(subfield_list)
for (i in x) {
  progress(match(i,x), max.value = length(x)) 
  marc_field$X110 <- str_replace(marc_field$X110,subfield_list_char[i],"|\\1")
}
subfield_list_char2 <- str_replace_all(subfield_list,"\\%","\\\\%")
for (i in x) {
  progress(match(i,x), max.value = length(x))
  string_a <- "(^)(.*?\\|"
  string_b <- subfield_list_char2[i]
  string_c <- ")(.*?)(\\,{0,1})((\\|\\%)(.*)|$)"
  string <- paste(string_a,string_b,string_c,sep = "")
  marc_field[,i+2] <- ifelse(grepl(subfield_list_char2[i],marc_field$X110),str_replace_all(gsub(string,"\\3",marc_field$X110),"\\%.", "~"),NA)
}
bn_institutions_110 <- marc_field %>%
  mutate(MRC = "110",
         Entity_Name = `%1`,
         Related_Entity_Sub_Entity = `%2`,
         Related_Entity_Main_Entity = NA,
         Located_Location = `%6`,
         subfield = "%1") %>%
  select(id,MRC,Entity_Name,Related_Entity_Sub_Entity,Related_Entity_Main_Entity,Located_Location,subfield)
sub_institutions <- marc_field %>%
  filter(!is.na(`%2`)) %>%
  mutate(MRC = "110",
         Entity_Name = `%2`,
         Related_Entity_Sub_Entity = NA,
         Related_Entity_Main_Entity = `%1`,
         Located_Location = `%7`,
         subfield = "%2") %>%
  select(id,MRC,Entity_Name,Related_Entity_Sub_Entity,Related_Entity_Main_Entity,Located_Location,subfield)
bn_institutions_110 <- rbind(bn_institutions_110,sub_institutions)

#field X120
marc_field <- bn_books %>%
  select(id,X120)%>%
  filter(X120!="") %>%
  cSplit(.,"X120",sep = "|",direction = "long") %>%
  filter(X120!="")
subfield_list<- str_extract_all(bn_books$X120,"\\%.")
subfield_list<- unique(unlist(subfield_list))
empty_table<- data.frame(matrix(ncol = length(subfield_list),nrow = lengths(marc_field)[1]))
colnames(empty_table) <-subfield_list
marc_field<-cbind(marc_field,empty_table)
subfield_list_char <- paste("(",subfield_list,")",sep = "")
x <- 1:length(subfield_list)
for (i in x) {
  progress(match(i,x), max.value = length(x)) 
  marc_field$X120 <- str_replace(marc_field$X120,subfield_list_char[i],"|\\1")
}
subfield_list_char2 <- str_replace_all(subfield_list,"\\%","\\\\%")
for (i in x) {
  progress(match(i,x), max.value = length(x))
  string_a <- "(^)(.*?\\|"
  string_b <- subfield_list_char2[i]
  string_c <- ")(.*?)(\\,{0,1})((\\|\\%)(.*)|$)"
  string <- paste(string_a,string_b,string_c,sep = "")
  marc_field[,i+2] <- ifelse(grepl(subfield_list_char2[i],marc_field$X120),str_replace_all(gsub(string,"\\3",marc_field$X120),"\\%.", "~"),NA)
}

bn_institutions_120 <- marc_field %>%
  mutate(MRC = "120",
         Entity_Name = `%1`,
         Related_Entity_Sub_Entity = `%2`,
         Related_Entity_Main_Entity = NA,
         Located_Location = NA,
         subfield = "%1") %>%
  select(id,MRC,Entity_Name,Related_Entity_Sub_Entity,Related_Entity_Main_Entity,Located_Location,subfield)
sub_institutions <- marc_field %>%
  filter(!is.na(`%2`)) %>%
  mutate(MRC = "120",
         Entity_Name = `%2`,
         Related_Entity_Sub_Entity = NA,
         Related_Entity_Main_Entity = `%1`,
         Located_Location = NA,
         subfield = "%2") %>%
  select(id,MRC,Entity_Name,Related_Entity_Sub_Entity,Related_Entity_Main_Entity,Located_Location,subfield)
bn_institutions_120 <- rbind(bn_institutions_120,sub_institutions)

#field X210
marc_field <- bn_books %>%
  select(id,X210)%>%
  filter(X210!="") %>%
  cSplit(.,"X210",sep = "|",direction = "long") %>%
  filter(X210!="")
subfield_list<- str_extract_all(bn_books$X210,"\\%.")
subfield_list<- unique(unlist(subfield_list))
empty_table<- data.frame(matrix(ncol = length(subfield_list),nrow = lengths(marc_field)[1]))
colnames(empty_table) <-subfield_list
marc_field<-cbind(marc_field,empty_table)
subfield_list_char <- paste("(",subfield_list,")",sep = "")
x <- 1:length(subfield_list)
for (i in x) {
  progress(match(i,x), max.value = length(x)) 
  marc_field$X210 <- str_replace(marc_field$X210,subfield_list_char[i],"|\\1")
}
subfield_list_char2 <- str_replace_all(subfield_list,"\\%","\\\\%")
for (i in x) {
  progress(match(i,x), max.value = length(x))
  string_a <- "(^)(.*?\\|"
  string_b <- subfield_list_char2[i]
  string_c <- ")(.*?)(\\,{0,1})((\\|\\%)(.*)|$)"
  string <- paste(string_a,string_b,string_c,sep = "")
  marc_field[,i+2] <- ifelse(grepl(subfield_list_char2[i],marc_field$X210),str_replace_all(gsub(string,"\\3",marc_field$X210),"\\%.", "~"),NA)
}

bn_institutions_210 <- marc_field %>%
  mutate(MRC = "210",
         Entity_Name = `%c`,
         Related_Entity_Sub_Entity = NA,
         Related_Entity_Main_Entity = NA,
         Located_Location = `%a`,
         subfield = "%c") %>%
  select(id,MRC,Entity_Name,Related_Entity_Sub_Entity,Related_Entity_Main_Entity,Located_Location,subfield)
sub_institutions <- marc_field %>%
  filter(!is.na(`%g`)) %>%
  mutate(MRC = "210",
         Entity_Name = `%g`,
         Related_Entity_Sub_Entity = NA,
         Related_Entity_Main_Entity = NA,
         Located_Location = `%e`,
         subfield = "%g") %>%
  select(id,MRC,Entity_Name,Related_Entity_Sub_Entity,Related_Entity_Main_Entity,Located_Location,subfield)
bn_institutions_210 <- rbind(bn_institutions_210,sub_institutions)
#field X225
marc_field <- bn_books %>%
  select(id,X225)%>%
  filter(X225!="") %>%
  cSplit(.,"X225",sep = "|",direction = "long") %>%
  filter(X225!="")
subfield_list<- str_extract_all(bn_books$X225,"\\%.")
subfield_list<- unique(unlist(subfield_list))
empty_table<- data.frame(matrix(ncol = length(subfield_list),nrow = lengths(marc_field)[1]))
colnames(empty_table) <-subfield_list
marc_field<-cbind(marc_field,empty_table)
subfield_list_char <- paste("(",subfield_list,")",sep = "")
x <- 1:length(subfield_list)
for (i in x) {
  progress(match(i,x), max.value = length(x)) 
  marc_field$X225 <- str_replace(marc_field$X225,subfield_list_char[i],"|\\1")
}
subfield_list_char2 <- str_replace_all(subfield_list,"\\%","\\\\%")
for (i in x) {
  progress(match(i,x), max.value = length(x))
  string_a <- "(^)(.*?\\|"
  string_b <- subfield_list_char2[i]
  string_c <- ")(.*?)(\\,{0,1})((\\|\\%)(.*)|$)"
  string <- paste(string_a,string_b,string_c,sep = "")
  marc_field[,i+2] <- ifelse(grepl(subfield_list_char2[i],marc_field$X225),str_replace_all(gsub(string,"\\3",marc_field$X225),"\\%.", "~"),NA)
}
bn_institutions_225 <- marc_field %>%
  mutate(MRC = "225",
         Entity_Name = `%f`,
         Related_Entity_Sub_Entity = NA,
         Related_Entity_Main_Entity = NA,
         Located_Location = NA,
         subfield = "%f") %>%
  select(id,MRC,Entity_Name,Related_Entity_Sub_Entity,Related_Entity_Main_Entity,Located_Location,subfield)

#field X710
marc_field <- bn_books %>%
  select(id,X710)%>%
  filter(X710!="") %>%
  cSplit(.,"X710",sep = "|",direction = "long") %>%
  filter(X710!="")
subfield_list<- str_extract_all(bn_books$X710,"\\%.")
subfield_list<- unique(unlist(subfield_list))
empty_table<- data.frame(matrix(ncol = length(subfield_list),nrow = lengths(marc_field)[1]))
colnames(empty_table) <-subfield_list
marc_field<-cbind(marc_field,empty_table)
subfield_list_char <- paste("(",subfield_list,")",sep = "")
x <- 1:length(subfield_list)
for (i in x) {
  progress(match(i,x), max.value = length(x)) 
  marc_field$X710 <- str_replace(marc_field$X710,subfield_list_char[i],"|\\1")
}
subfield_list_char2 <- str_replace_all(subfield_list,"\\%","\\\\%")
for (i in x) {
  progress(match(i,x), max.value = length(x))
  string_a <- "(^)(.*?\\|"
  string_b <- subfield_list_char2[i]
  string_c <- ")(.*?)(\\,{0,1})((\\|\\%)(.*)|$)"
  string <- paste(string_a,string_b,string_c,sep = "")
  marc_field[,i+2] <- ifelse(grepl(subfield_list_char2[i],marc_field$X710),str_replace_all(gsub(string,"\\3",marc_field$X710),"\\%.", "~"),NA)
}
bn_institutions_710 <- marc_field %>%
  mutate(MRC = "710",
         Entity_Name = `%1`,
         Related_Entity_Sub_Entity = NA,
         Related_Entity_Main_Entity = NA,
         Located_Location = NA,
         subfield = "%1") %>%
  select(id,MRC,Entity_Name,Related_Entity_Sub_Entity,Related_Entity_Main_Entity,Located_Location,subfield)
#field X711
marc_field <- bn_books %>%
  select(id,X711)%>%
  filter(X711!="") %>%
  cSplit(.,"X711",sep = "|",direction = "long") %>%
  filter(X711!="")
subfield_list<- str_extract_all(bn_books$X711,"\\%.")
subfield_list<- unique(unlist(subfield_list))
empty_table<- data.frame(matrix(ncol = length(subfield_list),nrow = lengths(marc_field)[1]))
colnames(empty_table) <-subfield_list
marc_field<-cbind(marc_field,empty_table)
subfield_list_char <- paste("(",subfield_list,")",sep = "")
x <- 1:length(subfield_list)
for (i in x) {
  progress(match(i,x), max.value = length(x)) 
  marc_field$X711 <- str_replace(marc_field$X711,subfield_list_char[i],"|\\1")
}
subfield_list_char2 <- str_replace_all(subfield_list,"\\%","\\\\%")
for (i in x) {
  progress(match(i,x), max.value = length(x))
  string_a <- "(^)(.*?\\|"
  string_b <- subfield_list_char2[i]
  string_c <- ")(.*?)(\\,{0,1})((\\|\\%)(.*)|$)"
  string <- paste(string_a,string_b,string_c,sep = "")
  marc_field[,i+2] <- ifelse(grepl(subfield_list_char2[i],marc_field$X711),str_replace_all(gsub(string,"\\3",marc_field$X711),"\\%.", "~"),NA)
}
bn_institutions_711 <- marc_field %>%
  mutate(MRC = "711",
         Entity_Name = `%1`,
         Related_Entity_Sub_Entity = NA,
         Related_Entity_Main_Entity = NA,
         Located_Location = NA,
         subfield = "%1") %>%
  select(id,MRC,Entity_Name,Related_Entity_Sub_Entity,Related_Entity_Main_Entity,Located_Location,subfield)
#connecting bn institutions
bn_books_institutions <- rbind(bn_institutions_110,bn_institutions_120,bn_institutions_210,bn_institutions_225,bn_institutions_710,bn_institutions_711) %>%
  mutate(source = "bn_books")

#cz_books 110, 264, 610, 710, 787(?)
#field X110
marc_field <- cz_books %>%
  select(id,X110)%>%
  filter(X110!="") %>%
  cSplit(.,"X110",sep = "|",direction = "long") %>%
  filter(X110!="")
marc_field <- mutate(marc_field,
               indicator = str_replace_all(marc_field$X110,"(^.*?)(\\$.*)","\\1"))
subfield_list<- str_extract_all(cz_books$X110,"\\${2}.")
subfield_list<- unique(unlist(subfield_list))
empty_table<- data.frame(matrix(ncol = length(subfield_list),nrow = lengths(marc_field)[1]))
colnames(empty_table) <-subfield_list
marc_field<-cbind(marc_field,empty_table)
subfield_list_char <- paste("(",subfield_list,")",sep = "")
subfield_list_char <- str_replace_all(subfield_list_char,"\\$","\\\\$")
x <- 1:length(subfield_list)
for (i in x) {
  marc_field$X110 <- str_replace(marc_field$X110,subfield_list_char[i],"|\\1")
  progress(match(i,x), max.value = length(x)) 
}
for (i in x) {
  progress(match(i,x), max.value = length(x))
  subfield_list_char2 <- str_replace_all(subfield_list,"\\$","\\\\$")
  string_a <- "(^)(.*?\\|"
  string_b <- subfield_list_char2[i]
  string_c <- ")(.*?)(\\,{0,1})((\\|\\${2})(.*)|$)"
  string <- paste(string_a,string_b,string_c,sep = "")
  marc_field[,i+3] <- ifelse(grepl(subfield_list_char2[i],marc_field$X110),str_replace_all(gsub(string,"\\3",marc_field$X110),"\\${2}.", "~"),NA)
}
cz_institutions_110 <- marc_field %>%
  mutate(MRC = "110",
         Entity_Name = `$$a`,
         Related_Entity_Sub_Entity = NA,
         Related_Entity_Main_Entity = NA,
         Located_Location = NA,
         subfield = "$$a") %>%
  select(id,MRC,Entity_Name,Related_Entity_Sub_Entity,Related_Entity_Main_Entity,Located_Location,subfield)

#field X264
marc_field <- cz_books %>%
  select(id,X264)%>%
  filter(X264!="") %>%
  cSplit(.,"X264",sep = "|",direction = "long") %>%
  filter(X264!="")
marc_field <- mutate(marc_field,
               indicator = str_replace_all(marc_field$X264,"(^.*?)(\\$.*)","\\1"))
subfield_list<- str_extract_all(cz_books$X264,"\\${2}.")
subfield_list<- unique(unlist(subfield_list))
empty_table<- data.frame(matrix(ncol = length(subfield_list),nrow = lengths(marc_field)[1]))
colnames(empty_table) <-subfield_list
marc_field<-cbind(marc_field,empty_table)
subfield_list_char <- paste("(",subfield_list,")",sep = "")
subfield_list_char <- str_replace_all(subfield_list_char,"\\$","\\\\$")
x <- 1:length(subfield_list)
for (i in x) {
  marc_field$X264 <- str_replace(marc_field$X264,subfield_list_char[i],"|\\1")
  progress(match(i,x), max.value = length(x)) 
}
for (i in x) {
  progress(match(i,x), max.value = length(x))
  subfield_list_char2 <- str_replace_all(subfield_list,"\\$","\\\\$")
  string_a <- "(^)(.*?\\|"
  string_b <- subfield_list_char2[i]
  string_c <- ")(.*?)(\\,{0,1})((\\|\\${2})(.*)|$)"
  string <- paste(string_a,string_b,string_c,sep = "")
  marc_field[,i+3] <- ifelse(grepl(subfield_list_char2[i],marc_field$X264),str_replace_all(gsub(string,"\\3",marc_field$X264),"\\${2}.", "~"),NA)
}
cz_institutions_264 <- marc_field %>%
  mutate(MRC = "264",
         Entity_Name = `$$b`,
         Related_Entity_Sub_Entity = NA,
         Related_Entity_Main_Entity = NA,
         Located_Location = `$$a`,
         subfield = "$$b") %>%
  select(id,MRC,Entity_Name,Related_Entity_Sub_Entity,Related_Entity_Main_Entity,Located_Location,subfield)

#field X610
marc_field <- cz_books %>%
  select(id,X610)%>%
  filter(X610!="") %>%
  cSplit(.,"X610",sep = "|",direction = "long") %>%
  filter(X610!="")
marc_field <- mutate(marc_field,
               indicator = str_replace_all(marc_field$X610,"(^.*?)(\\$.*)","\\1"))
subfield_list<- str_extract_all(cz_books$X610,"\\${2}.")
subfield_list<- unique(unlist(subfield_list))
empty_table<- data.frame(matrix(ncol = length(subfield_list),nrow = lengths(marc_field)[1]))
colnames(empty_table) <-subfield_list
marc_field<-cbind(marc_field,empty_table)
subfield_list_char <- paste("(",subfield_list,")",sep = "")
subfield_list_char <- str_replace_all(subfield_list_char,"\\$","\\\\$")
x <- 1:length(subfield_list)
for (i in x) {
  marc_field$X610 <- str_replace(marc_field$X610,subfield_list_char[i],"|\\1")
  progress(match(i,x), max.value = length(x)) 
}
for (i in x) {
  progress(match(i,x), max.value = length(x))
  subfield_list_char2 <- str_replace_all(subfield_list,"\\$","\\\\$")
  string_a <- "(^)(.*?\\|"
  string_b <- subfield_list_char2[i]
  string_c <- ")(.*?)(\\,{0,1})((\\|\\${2})(.*)|$)"
  string <- paste(string_a,string_b,string_c,sep = "")
  marc_field[,i+3] <- ifelse(grepl(subfield_list_char2[i],marc_field$X610),str_replace_all(gsub(string,"\\3",marc_field$X610),"\\${2}.", "~"),NA)
}
cz_institutions_610 <- marc_field %>%
  mutate(MRC = "610",
         Entity_Name = `$$a`,
         Related_Entity_Sub_Entity = NA,
         Related_Entity_Main_Entity = NA,
         Located_Location = NA,
         subfield = "$$a") %>%
  select(id,MRC,Entity_Name,Related_Entity_Sub_Entity,Related_Entity_Main_Entity,Located_Location,subfield)
#field X710
marc_field <- cz_books %>%
  select(id,X710)%>%
  filter(X710!="") %>%
  cSplit(.,"X710",sep = "|",direction = "long") %>%
  filter(X710!="")
marc_field <- mutate(marc_field,
               indicator = str_replace_all(marc_field$X710,"(^.*?)(\\$.*)","\\1"))
subfield_list<- str_extract_all(cz_books$X710,"\\${2}.")
subfield_list<- unique(unlist(subfield_list))
empty_table<- data.frame(matrix(ncol = length(subfield_list),nrow = lengths(marc_field)[1]))
colnames(empty_table) <-subfield_list
marc_field<-cbind(marc_field,empty_table)
subfield_list_char <- paste("(",subfield_list,")",sep = "")
subfield_list_char <- str_replace_all(subfield_list_char,"\\$","\\\\$")
x <- 1:length(subfield_list)
for (i in x) {
  marc_field$X710 <- str_replace(marc_field$X710,subfield_list_char[i],"|\\1")
  progress(match(i,x), max.value = length(x)) 
}
for (i in x) {
  progress(match(i,x), max.value = length(x))
  subfield_list_char2 <- str_replace_all(subfield_list,"\\$","\\\\$")
  string_a <- "(^)(.*?\\|"
  string_b <- subfield_list_char2[i]
  string_c <- ")(.*?)(\\,{0,1})((\\|\\${2})(.*)|$)"
  string <- paste(string_a,string_b,string_c,sep = "")
  marc_field[,i+3] <- ifelse(grepl(subfield_list_char2[i],marc_field$X710),str_replace_all(gsub(string,"\\3",marc_field$X710),"\\${2}.", "~"),NA)
}
cz_institutions_710 <- marc_field %>%
  mutate(MRC = "710",
         Entity_Name = `$$a`,
         Related_Entity_Sub_Entity = NA,
         Related_Entity_Main_Entity = NA,
         Located_Location = NA,
         subfield = "$$a") %>%
  select(id,MRC,Entity_Name,Related_Entity_Sub_Entity,Related_Entity_Main_Entity,Located_Location,subfield)
#connecting cz books institutions
cz_books_institutions <- rbind(cz_institutions_110,cz_institutions_264,cz_institutions_610,cz_institutions_710) %>%
  mutate(source = "cz_books")
#cz_articles 110, 610, 710

#field X110
marc_field <- cz_articles %>%
  select(id,X110)%>%
  filter(X110!="") %>%
  cSplit(.,"X110",sep = "|",direction = "long") %>%
  filter(X110!="")
marc_field <- mutate(marc_field,
               indicator = str_replace_all(marc_field$X110,"(^.*?)(\\$.*)","\\1"))
subfield_list<- str_extract_all(cz_articles$X110,"\\${2}.")
subfield_list<- unique(unlist(subfield_list))
empty_table<- data.frame(matrix(ncol = length(subfield_list),nrow = lengths(marc_field)[1]))
colnames(empty_table) <-subfield_list
marc_field<-cbind(marc_field,empty_table)
subfield_list_char <- paste("(",subfield_list,")",sep = "")
subfield_list_char <- str_replace_all(subfield_list_char,"\\$","\\\\$")
x <- 1:length(subfield_list)
for (i in x) {
  marc_field$X110 <- str_replace(marc_field$X110,subfield_list_char[i],"|\\1")
  progress(match(i,x), max.value = length(x)) 
}
for (i in x) {
  progress(match(i,x), max.value = length(x))
  subfield_list_char2 <- str_replace_all(subfield_list,"\\$","\\\\$")
  string_a <- "(^)(.*?\\|"
  string_b <- subfield_list_char2[i]
  string_c <- ")(.*?)(\\,{0,1})((\\|\\${2})(.*)|$)"
  string <- paste(string_a,string_b,string_c,sep = "")
  marc_field[,i+3] <- ifelse(grepl(subfield_list_char2[i],marc_field$X110),str_replace_all(gsub(string,"\\3",marc_field$X110),"\\${2}.", "~"),NA)
}
cz_institutions_110 <- marc_field %>%
  mutate(MRC = "110",
         Entity_Name = `$$a`,
         Related_Entity_Sub_Entity = NA,
         Related_Entity_Main_Entity = NA,
         Located_Location = NA,
         subfield = "$$a") %>%
  select(id,MRC,Entity_Name,Related_Entity_Sub_Entity,Related_Entity_Main_Entity,Located_Location,subfield)
#field X610
marc_field <- cz_articles %>%
  select(id,X610)%>%
  filter(X610!="") %>%
  cSplit(.,"X610",sep = "|",direction = "long") %>%
  filter(X610!="")
marc_field <- mutate(marc_field,
               indicator = str_replace_all(marc_field$X610,"(^.*?)(\\$.*)","\\1"))
subfield_list<- str_extract_all(cz_articles$X610,"\\${2}.")
subfield_list<- unique(unlist(subfield_list))
empty_table<- data.frame(matrix(ncol = length(subfield_list),nrow = lengths(marc_field)[1]))
colnames(empty_table) <-subfield_list
marc_field<-cbind(marc_field,empty_table)
subfield_list_char <- paste("(",subfield_list,")",sep = "")
subfield_list_char <- str_replace_all(subfield_list_char,"\\$","\\\\$")
x <- 1:length(subfield_list)
for (i in x) {
  marc_field$X610 <- str_replace(marc_field$X610,subfield_list_char[i],"|\\1")
  progress(match(i,x), max.value = length(x)) 
}
for (i in x) {
  progress(match(i,x), max.value = length(x))
  subfield_list_char2 <- str_replace_all(subfield_list,"\\$","\\\\$")
  string_a <- "(^)(.*?\\|"
  string_b <- subfield_list_char2[i]
  string_c <- ")(.*?)(\\,{0,1})((\\|\\${2})(.*)|$)"
  string <- paste(string_a,string_b,string_c,sep = "")
  marc_field[,i+3] <- ifelse(grepl(subfield_list_char2[i],marc_field$X610),str_replace_all(gsub(string,"\\3",marc_field$X610),"\\${2}.", "~"),NA)
}
cz_institutions_610 <- marc_field %>%
  mutate(MRC = "610",
         Entity_Name = `$$a`,
         Related_Entity_Sub_Entity = NA,
         Related_Entity_Main_Entity = NA,
         Located_Location = NA,
         subfield = "$$a") %>%
  select(id,MRC,Entity_Name,Related_Entity_Sub_Entity,Related_Entity_Main_Entity,Located_Location,subfield)
#field X710
marc_field <- cz_articles %>%
  select(id,X710)%>%
  filter(X710!="") %>%
  cSplit(.,"X710",sep = "|",direction = "long") %>%
  filter(X710!="")
marc_field <- mutate(marc_field,
               indicator = str_replace_all(marc_field$X710,"(^.*?)(\\$.*)","\\1"))
subfield_list<- str_extract_all(cz_articles$X710,"\\${2}.")
subfield_list<- unique(unlist(subfield_list))
empty_table<- data.frame(matrix(ncol = length(subfield_list),nrow = lengths(marc_field)[1]))
colnames(empty_table) <-subfield_list
marc_field<-cbind(marc_field,empty_table)
subfield_list_char <- paste("(",subfield_list,")",sep = "")
subfield_list_char <- str_replace_all(subfield_list_char,"\\$","\\\\$")
x <- 1:length(subfield_list)
for (i in x) {
  marc_field$X710 <- str_replace(marc_field$X710,subfield_list_char[i],"|\\1")
  progress(match(i,x), max.value = length(x)) 
}
for (i in x) {
  progress(match(i,x), max.value = length(x))
  subfield_list_char2 <- str_replace_all(subfield_list,"\\$","\\\\$")
  string_a <- "(^)(.*?\\|"
  string_b <- subfield_list_char2[i]
  string_c <- ")(.*?)(\\,{0,1})((\\|\\${2})(.*)|$)"
  string <- paste(string_a,string_b,string_c,sep = "")
  marc_field[,i+3] <- ifelse(grepl(subfield_list_char2[i],marc_field$X710),str_replace_all(gsub(string,"\\3",marc_field$X710),"\\${2}.", "~"),NA)
}
cz_institutions_710 <- marc_field %>%
  mutate(MRC = "710",
         Entity_Name = `$$a`,
         Related_Entity_Sub_Entity = NA,
         Related_Entity_Main_Entity = NA,
         Located_Location = NA,
         subfield = "$$a") %>%
  select(id,MRC,Entity_Name,Related_Entity_Sub_Entity,Related_Entity_Main_Entity,Located_Location,subfield)
#connecting cz articles institutions
cz_articles_institutions <- rbind(cz_institutions_110,cz_institutions_610,cz_institutions_710) %>%
  mutate(source = "cz_articles")

#pbl_books
#publishing house
pbl_books_publishing_house <- pbl_books %>%
  select(rekord_id,wydawnictwo,miejscowosc) %>%
  unique() %>%
  mutate(MRC = NA,
         Entity_Name = wydawnictwo,
         Related_Entity_Sub_Entity = NA,
         Related_Entity_Main_Entity = NA,
         Located_Location = miejscowosc,
         subfield = "publishing_house",
         id = rekord_id) %>%
  select(id,MRC,Entity_Name,Related_Entity_Sub_Entity,Related_Entity_Main_Entity,Located_Location,subfield)
#subject headings
pbl_books_sh <- pbl_books %>%
  select(rekord_id,HP_NAZWA,KH_NAZWA) %>%
  unique() %>%
  filter(HP_NAZWA %in% c("Biblioteki","Filmowe instytucje, kluby, przedsibiorstwa","Fundacje, fundusze kulturalne, stypendia","Grupy literackie i artystyczne","Instytucje kulturalne, pastwowe, spoeczne obce","Instytucje kulturalne, pastwowe, spoeczne polskie","Instytuty pozauczelniane, komitety i towarzystwa naukowe w Polsce","Instytuty pozauczelniane, komitety i towarzystwa naukowe za granic","Muzea obce","Muzea polskie","Teatry obce","Teatry polskie historia","Teatry polskie wspczesne","Uczelniane instytuty (wydziay, zakady, orodki badawcze) obce","Uczelniane instytuty (wydziay, zakady, orodki badawcze) polskie","Uniwersytety, szkoy wysze i inne uczelnie obce","Uniwersytety, szkoy wysze i inne uczelnie polskie","Wydawnictwa polskie do 1945 roku","Wydawnictwa polskie po 1945 roku","Zwizki, kluby, koa, stowarzyszenia twrcze obce","Zwizki, kluby, koa, stowarzyszenia twrcze polskie")) %>%
  mutate(MRC = NA,
         Entity_Name = KH_NAZWA,
         Related_Entity_Sub_Entity = NA,
         Related_Entity_Main_Entity = NA,
         Located_Location = NA,
         subfield = "subject_heading",
         id = rekord_id) %>%
  select(id,MRC,Entity_Name,Related_Entity_Sub_Entity,Related_Entity_Main_Entity,Located_Location,subfield)
pbl_books_institutions <- rbind(pbl_books_publishing_house,pbl_books_sh) %>%
  mutate(source = "pbl_books")
#pbl_articles
#subject headings
pbl_articles_institutions <- pbl_articles %>%
  select(rekord_id,HP_NAZWA,KH_NAZWA) %>%
  unique() %>%
  filter(HP_NAZWA %in% c("Biblioteki","Filmowe instytucje, kluby, przedsibiorstwa","Fundacje, fundusze kulturalne, stypendia","Grupy literackie i artystyczne","Instytucje kulturalne, pastwowe, spoeczne obce","Instytucje kulturalne, pastwowe, spoeczne polskie","Instytuty pozauczelniane, komitety i towarzystwa naukowe w Polsce","Instytuty pozauczelniane, komitety i towarzystwa naukowe za granic","Muzea obce","Muzea polskie","Teatry obce","Teatry polskie historia","Teatry polskie wspczesne","Uczelniane instytuty (wydziay, zakady, orodki badawcze) obce","Uczelniane instytuty (wydziay, zakady, orodki badawcze) polskie","Uniwersytety, szkoy wysze i inne uczelnie obce","Uniwersytety, szkoy wysze i inne uczelnie polskie","Wydawnictwa polskie do 1945 roku","Wydawnictwa polskie po 1945 roku","Zwizki, kluby, koa, stowarzyszenia twrcze obce","Zwizki, kluby, koa, stowarzyszenia twrcze polskie")) %>%
  mutate(MRC = NA,
         Entity_Name = KH_NAZWA,
         Related_Entity_Sub_Entity = NA,
         Related_Entity_Main_Entity = NA,
         Located_Location = NA,
         subfield = "subject_heading",
         id = rekord_id) %>%
  select(id,MRC,Entity_Name,Related_Entity_Sub_Entity,Related_Entity_Main_Entity,Located_Location,subfield) %>%
  mutate(source = "pbl_articles")
#merge all institutions
institutions <- rbind(bn_books_institutions,cz_books_institutions,cz_articles_institutions,pbl_books_institutions,pbl_articles_institutions) %>%
  mutate(Located_Location = str_remove(str_remove(trim(Located_Location),"^\\["),"\\]$")) %>%
  group_by(Entity_Name,Related_Entity_Sub_Entity,Related_Entity_Main_Entity,Located_Location) %>%
  mutate(group = paste(paste(source,MRC,subfield,id,sep = ""),collapse = "|")) %>%
  ungroup() %>%
  select(Entity_Name,Related_Entity_Sub_Entity,Related_Entity_Main_Entity,Located_Location,group) %>%
  unique() %>%
  arrange(Entity_Name,Related_Entity_Sub_Entity,Related_Entity_Main_Entity)


write.csv2(institutions, "C:/Users/Cezary/Desktop/samizdat_kartoteka_instytucji.csv", row.names = F, na = '', fileEncoding = 'UTF-8')
```

```{r preparing file for events}
#bn_books
trim <- function (x) gsub("^\\s+|\\s+$", "", x)
#field X120
marc_field <- bn_books %>%
  select(id,X120)%>%
  filter(X120!="") %>%
  cSplit(.,"X120",sep = "|",direction = "long") %>%
  filter(X120!="")
subfield_list<- str_extract_all(bn_books$X120,"\\%.")
subfield_list<- unique(unlist(subfield_list))
empty_table<- data.frame(matrix(ncol = length(subfield_list),nrow = lengths(marc_field)[1]))
colnames(empty_table) <-subfield_list
marc_field<-cbind(marc_field,empty_table)
subfield_list_char <- paste("(",subfield_list,")",sep = "")
x <- 1:length(subfield_list)
for (i in x) {
  progress(match(i,x), max.value = length(x)) 
  marc_field$X120 <- str_replace(marc_field$X120,subfield_list_char[i],"|\\1")
}
subfield_list_char2 <- str_replace_all(subfield_list,"\\%","\\\\%")
for (i in x) {
  progress(match(i,x), max.value = length(x))
  string_a <- "(^)(.*?\\|"
  string_b <- subfield_list_char2[i]
  string_c <- ")(.*?)(\\,{0,1})((\\|\\%)(.*)|$)"
  string <- paste(string_a,string_b,string_c,sep = "")
  marc_field[,i+2] <- ifelse(grepl(subfield_list_char2[i],marc_field$X120),str_replace_all(gsub(string,"\\3",marc_field$X120),"\\%.", "~"),NA)
}

bn_events <- marc_field %>%
  mutate(MRC = "120",
         Event_Name = `%3`,
         Event_Other_Names = `%r`,
         Event_Number = `%4`,
         Event_Number_Arabic = `%n`,
         Event_Year = `%5`,
         Located = `%8`,
         Organiser_Main = `%1`,
         Organiser_Sub = `%2`,
         subfield = "%3") %>%
  select(id,MRC,Event_Name,Event_Other_Names,Event_Number,Event_Number_Arabic,Event_Year,Located,Organiser_Main,Organiser_Sub,subfield) %>%
  mutate(source = "bn_books")

#cz_books
#field X611
marc_field <- cz_books %>%
  select(id,X611)%>%
  filter(X611!="") %>%
  cSplit(.,"X611",sep = "|",direction = "long") %>%
  filter(X611!="")
marc_field <- mutate(marc_field,
               indicator = str_replace_all(marc_field$X611,"(^.*?)(\\$.*)","\\1"))
subfield_list<- str_extract_all(cz_books$X611,"\\${2}.")
subfield_list<- unique(unlist(subfield_list))
empty_table<- data.frame(matrix(ncol = length(subfield_list),nrow = lengths(marc_field)[1]))
colnames(empty_table) <-subfield_list
marc_field<-cbind(marc_field,empty_table)
subfield_list_char <- paste("(",subfield_list,")",sep = "")
subfield_list_char <- str_replace_all(subfield_list_char,"\\$","\\\\$")
x <- 1:length(subfield_list)
for (i in x) {
  marc_field$X611 <- str_replace(marc_field$X611,subfield_list_char[i],"|\\1")
  progress(match(i,x), max.value = length(x)) 
}
for (i in x) {
  progress(match(i,x), max.value = length(x))
  subfield_list_char2 <- str_replace_all(subfield_list,"\\$","\\\\$")
  string_a <- "(^)(.*?\\|"
  string_b <- subfield_list_char2[i]
  string_c <- ")(.*?)(\\,{0,1})((\\|\\${2})(.*)|$)"
  string <- paste(string_a,string_b,string_c,sep = "")
  marc_field[,i+3] <- ifelse(grepl(subfield_list_char2[i],marc_field$X611),str_replace_all(gsub(string,"\\3",marc_field$X611),"\\${2}.", "~"),NA)
}
cz_books_events <- marc_field %>%
  mutate(MRC = "611",
         Event_Name = `$$a`,
         Event_Other_Names = NA,
         Event_Number = NA,
         Event_Number_Arabic = NA,
         Event_Year = `$$d`,
         Located = `$$c`,
         Organiser_Main = NA,
         Organiser_Sub = NA,
         subfield = "$$a") %>%
  select(id,MRC,Event_Name,Event_Other_Names,Event_Number,Event_Number_Arabic,Event_Year,Located,Organiser_Main,Organiser_Sub,subfield) %>%
  mutate(source = "cz_books")
#cz_articles
#field X611
marc_field <- cz_articles %>%
  select(id,X611)%>%
  filter(X611!="") %>%
  cSplit(.,"X611",sep = "|",direction = "long") %>%
  filter(X611!="")
marc_field <- mutate(marc_field,
               indicator = str_replace_all(marc_field$X611,"(^.*?)(\\$.*)","\\1"))
subfield_list<- str_extract_all(cz_articles$X611,"\\${2}.")
subfield_list<- unique(unlist(subfield_list))
empty_table<- data.frame(matrix(ncol = length(subfield_list),nrow = lengths(marc_field)[1]))
colnames(empty_table) <-subfield_list
marc_field<-cbind(marc_field,empty_table)
subfield_list_char <- paste("(",subfield_list,")",sep = "")
subfield_list_char <- str_replace_all(subfield_list_char,"\\$","\\\\$")
x <- 1:length(subfield_list)
for (i in x) {
  marc_field$X611 <- str_replace(marc_field$X611,subfield_list_char[i],"|\\1")
  progress(match(i,x), max.value = length(x)) 
}
for (i in x) {
  progress(match(i,x), max.value = length(x))
  subfield_list_char2 <- str_replace_all(subfield_list,"\\$","\\\\$")
  string_a <- "(^)(.*?\\|"
  string_b <- subfield_list_char2[i]
  string_c <- ")(.*?)(\\,{0,1})((\\|\\${2})(.*)|$)"
  string <- paste(string_a,string_b,string_c,sep = "")
  marc_field[,i+3] <- ifelse(grepl(subfield_list_char2[i],marc_field$X611),str_replace_all(gsub(string,"\\3",marc_field$X611),"\\${2}.", "~"),NA)
}
cz_articles_events <- marc_field %>%
  mutate(MRC = "611",
         Event_Name = `$$a`,
         Event_Other_Names = NA,
         Event_Number = NA,
         Event_Number_Arabic = `$$n`,
         Event_Year = `$$d`,
         Located = `$$c`,
         Organiser_Main = NA,
         Organiser_Sub = NA,
         subfield = "$$a") %>%
  select(id,MRC,Event_Name,Event_Other_Names,Event_Number,Event_Number_Arabic,Event_Year,Located,Organiser_Main,Organiser_Sub,subfield) %>%
  mutate(source = "cz_articles")
cz_events <- rbind(cz_books_events,cz_articles_events)

#merge all events
events <- rbind(bn_events,cz_books_events,cz_articles_events) %>%
  group_by(Event_Name,Event_Other_Names,Event_Number,Event_Number_Arabic,Event_Year,Located,Organiser_Main,Organiser_Sub) %>%
  mutate(group = paste(paste(source,MRC,subfield,id,sep = ""),collapse = "|")) %>%
  ungroup() %>%
  select(Event_Name,Event_Other_Names,Event_Number,Event_Number_Arabic,Event_Year,Located,Organiser_Main,Organiser_Sub,group) %>%
  unique() %>%
  arrange(Event_Name,Event_Year)

write.csv2(events, "C:/Users/Cezary/Desktop/samizdat_kartoteka_wydarze.csv", row.names = F, na = '', fileEncoding = 'UTF-8')

```

```{r preparing file for series}
#bn_books
trim <- function (x) gsub("^\\s+|\\s+$", "", x)
#field X225
marc_field <- bn_books %>%
  select(id,X225)%>%
  filter(X225!="") %>%
  cSplit(.,"X225",sep = "|",direction = "long") %>%
  filter(X225!="")
subfield_list<- str_extract_all(bn_books$X225,"\\%.")
subfield_list<- unique(unlist(subfield_list))
empty_table<- data.frame(matrix(ncol = length(subfield_list),nrow = lengths(marc_field)[1]))
colnames(empty_table) <-subfield_list
marc_field<-cbind(marc_field,empty_table)
subfield_list_char <- paste("(",subfield_list,")",sep = "")
x <- 1:length(subfield_list)
for (i in x) {
  progress(match(i,x), max.value = length(x)) 
  marc_field$X225 <- str_replace(marc_field$X225,subfield_list_char[i],"|\\1")
}
subfield_list_char2 <- str_replace_all(subfield_list,"\\%","\\\\%")
for (i in x) {
  progress(match(i,x), max.value = length(x))
  string_a <- "(^)(.*?\\|"
  string_b <- subfield_list_char2[i]
  string_c <- ")(.*?)(\\,{0,1})((\\|\\%)(.*)|$)"
  string <- paste(string_a,string_b,string_c,sep = "")
  marc_field[,i+2] <- ifelse(grepl(subfield_list_char2[i],marc_field$X225),str_replace_all(gsub(string,"\\3",marc_field$X225),"\\%.", "~"),NA)
}

bn_series_225 <- marc_field %>%
  mutate(MRC = "225",
         Series_Title = `%a`,
         Addition_to_Title = `%e`,
         Creator = `%f`,
         Sub_Series = `%c`,
         Main_Series = NA,
         subfield = "%a") %>%
  select(id,MRC,Series_Title,Addition_to_Title,Creator,Sub_Series,Main_Series,subfield)
bn_more_series <- marc_field %>%
  filter(!is.na(`%c`)) %>%
  mutate(MRC = "225",
         Series_Title = `%c`,
         Addition_to_Title = NA,
         Creator = `%f`,
         Sub_Series = NA,
         Main_Series = `%a`,
         subfield = "%c") %>%
  select(id,MRC,Series_Title,Addition_to_Title,Creator,Sub_Series,Main_Series,subfield)
#field X226
marc_field <- bn_books %>%
  select(id,X226)%>%
  filter(X226!="") %>%
  cSplit(.,"X226",sep = "|",direction = "long") %>%
  filter(X226!="")
subfield_list<- str_extract_all(bn_books$X226,"\\%.")
subfield_list<- unique(unlist(subfield_list))
empty_table<- data.frame(matrix(ncol = length(subfield_list),nrow = lengths(marc_field)[1]))
colnames(empty_table) <-subfield_list
marc_field<-cbind(marc_field,empty_table)
subfield_list_char <- paste("(",subfield_list,")",sep = "")
x <- 1:length(subfield_list)
for (i in x) {
  progress(match(i,x), max.value = length(x)) 
  marc_field$X226 <- str_replace(marc_field$X226,subfield_list_char[i],"|\\1")
}
subfield_list_char2 <- str_replace_all(subfield_list,"\\%","\\\\%")
for (i in x) {
  progress(match(i,x), max.value = length(x))
  string_a <- "(^)(.*?\\|"
  string_b <- subfield_list_char2[i]
  string_c <- ")(.*?)(\\,{0,1})((\\|\\%)(.*)|$)"
  string <- paste(string_a,string_b,string_c,sep = "")
  marc_field[,i+2] <- ifelse(grepl(subfield_list_char2[i],marc_field$X226),str_replace_all(gsub(string,"\\3",marc_field$X226),"\\%.", "~"),NA)
}
bn_series_226 <- marc_field %>%
  mutate(MRC = "226",
         Series_Title = `%a`,
         Addition_to_Title = NA,
         Creator = NA,
         Sub_Series = NA,
         Main_Series = NA,
         subfield = "%a") %>%
  select(id,MRC,Series_Title,Addition_to_Title,Creator,Sub_Series,Main_Series,subfield)


bn_series <- rbind(bn_series_225,bn_more_series,bn_series_226) %>%
  mutate(source = "bn_books")

#cz_books
#field X490
marc_field <- cz_books %>%
  select(id,X490)%>%
  filter(X490!="") %>%
  cSplit(.,"X490",sep = "|",direction = "long") %>%
  filter(X490!="")
marc_field <- mutate(marc_field,
               indicator = str_replace_all(marc_field$X490,"(^.*?)(\\$.*)","\\1"))
subfield_list<- str_extract_all(cz_books$X490,"\\${2}.")
subfield_list<- unique(unlist(subfield_list))
empty_table<- data.frame(matrix(ncol = length(subfield_list),nrow = lengths(marc_field)[1]))
colnames(empty_table) <-subfield_list
marc_field<-cbind(marc_field,empty_table)
subfield_list_char <- paste("(",subfield_list,")",sep = "")
subfield_list_char <- str_replace_all(subfield_list_char,"\\$","\\\\$")
x <- 1:length(subfield_list)
for (i in x) {
  marc_field$X490 <- str_replace(marc_field$X490,subfield_list_char[i],"|\\1")
  progress(match(i,x), max.value = length(x)) 
}
for (i in x) {
  progress(match(i,x), max.value = length(x))
  subfield_list_char2 <- str_replace_all(subfield_list,"\\$","\\\\$")
  string_a <- "(^)(.*?\\|"
  string_b <- subfield_list_char2[i]
  string_c <- ")(.*?)(\\,{0,1})((\\|\\${2})(.*)|$)"
  string <- paste(string_a,string_b,string_c,sep = "")
  marc_field[,i+3] <- ifelse(grepl(subfield_list_char2[i],marc_field$X490),str_replace_all(gsub(string,"\\3",marc_field$X490),"\\${2}.", "~"),NA)
}
cz_series_490 <- marc_field %>%
  mutate(MRC = "490",
         Series_Title = str_remove(`$$a`," ;$"),
         Addition_to_Title = NA,
         Creator = NA,
         Sub_Series = NA,
         Main_Series = NA,
         subfield = "$$a") %>%
  select(id,MRC,Series_Title,Addition_to_Title,Creator,Sub_Series,Main_Series,subfield)
#field X830
marc_field <- cz_books %>%
  select(id,X830)%>%
  filter(X830!="") %>%
  cSplit(.,"X830",sep = "|",direction = "long") %>%
  filter(X830!="")
marc_field <- mutate(marc_field,
               indicator = str_replace_all(marc_field$X830,"(^.*?)(\\$.*)","\\1"))
subfield_list<- str_extract_all(cz_books$X830,"\\${2}.")
subfield_list<- unique(unlist(subfield_list))
empty_table<- data.frame(matrix(ncol = length(subfield_list),nrow = lengths(marc_field)[1]))
colnames(empty_table) <-subfield_list
marc_field<-cbind(marc_field,empty_table)
subfield_list_char <- paste("(",subfield_list,")",sep = "")
subfield_list_char <- str_replace_all(subfield_list_char,"\\$","\\\\$")
x <- 1:length(subfield_list)
for (i in x) {
  marc_field$X830 <- str_replace(marc_field$X830,subfield_list_char[i],"|\\1")
  progress(match(i,x), max.value = length(x)) 
}
for (i in x) {
  progress(match(i,x), max.value = length(x))
  subfield_list_char2 <- str_replace_all(subfield_list,"\\$","\\\\$")
  string_a <- "(^)(.*?\\|"
  string_b <- subfield_list_char2[i]
  string_c <- ")(.*?)(\\,{0,1})((\\|\\${2})(.*)|$)"
  string <- paste(string_a,string_b,string_c,sep = "")
  marc_field[,i+3] <- ifelse(grepl(subfield_list_char2[i],marc_field$X830),str_replace_all(gsub(string,"\\3",marc_field$X830),"\\${2}.", "~"),NA)
}
cz_series_830 <- marc_field %>%
  mutate(MRC = "830",
         Series_Title = str_remove(`$$a`," ;$"),
         Addition_to_Title = NA,
         Creator = NA,
         Sub_Series = NA,
         Main_Series = NA,
         subfield = "$$a") %>%
  select(id,MRC,Series_Title,Addition_to_Title,Creator,Sub_Series,Main_Series,subfield)
cz_series <- rbind(cz_series_490,cz_series_830) %>%
  mutate(source = "cz_books")
#pbl_books
pbl_series <- pbl_books %>%
  select(rekord_id,ZA_SERIA_WYDAWNICZA) %>%
  unique() %>%
  mutate(MRC = NA,
         Series_Title = str_remove(str_remove(ZA_SERIA_WYDAWNICZA,"^\\("),"\\)$"),
         Addition_to_Title = NA,
         Creator = NA,
         Sub_Series = NA,
         Main_Series = NA,
         subfield = "za_seria_wydawnicza",
         id = rekord_id) %>%
  select(id,MRC,Series_Title,Addition_to_Title,Creator,Sub_Series,Main_Series,subfield) %>%
  mutate(source = "pbl_books")

#merge all series
series <- rbind(bn_series,cz_series,pbl_series) %>%
  group_by(Series_Title,Addition_to_Title,Creator,Sub_Series,Main_Series) %>%
  mutate(group = paste(paste(source,MRC,subfield,id,sep = ""),collapse = "|")) %>%
  ungroup() %>%
  select(Series_Title,Addition_to_Title,Creator,Sub_Series,Main_Series,group) %>%
  unique() %>%
  arrange(Series_Title,Addition_to_Title)

write.csv2(series, "C:/Users/Cezary/Desktop/samizdat_kartoteka_serii.csv", row.names = F, na = '', fileEncoding = 'UTF-8')

```


```{r}
bn_people_record_id_X701 <- bn_people_record_id_X701 %>%
  group_by(name_total) %>%
  mutate(record_id_group = paste(record_id,collapse = "|")) %>%
  mutate(record_id_group = paste("bn_X701",record_id_group,sep = "|")) %>%
  ungroup() %>%
  select(last_name,first_name,years,name_total,record_id_group) %>%
  unique()

#concatenate all bn
bn_people_record_id <- rbind(bn_people_record_id_X100,bn_people_record_id_X700,bn_people_record_id_X701)
bn_people_record_id <- bn_people_record_id %>%
  group_by(name_total) %>%
  mutate(record_id_group = paste(record_id_group,collapse = "~")) %>%
  ungroup() %>%
  mutate(person_id = paste("bn_b_",seq.int(nrow(bn_people_record_id)),sep = "")) %>%
  select(person_id,1:5)
```


